### ISSUE TITLE
Export fails

### ISSUE THREAD

**Issue by O2-AC** [retorquere/zotero-better-bibtex#1567] opened 2020-07-08 14:24 UTC
*Please verify **all** of the below before submitting*:

1. you have picked the right category for the issue in the previous screen.
2. You are on the latest release of Zotero
3. in the Zotero addons screen you can see that you have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest)
4. you are posting a single bug or feature request.
5. the issue has a subject that succinctly describes the problem or question.
6. you are available for follow-up questions and testing.
7. you have included an error-report ID here generated by reproducing the problem, selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu, **not** from the `Help` menu.
8. you have included the *actual output* you got from exporting the items you sent in the debug log, not simplified fictional output or a description of the output, and a sample (*not* a description) of how you want it to look instead, again based on the actual items you selected in the previous step.

Picking the right issue category is really important. Each category (`Export`, `General error`, `Import`, `Key generation`, `Question`) has different instructions for gathering the data necessary required to resolve the issue you are experiencing

The error report is important; it gives me your current BBT settings and a copy of the problematic reference as a test case so I can best replicate your problem. Without it, I'm effectively blind.

**Report ID: P3DILE6F-euc**

**Exporter used: Better BibLaTex**

**Expected behavior: Exports a .bib file**

**Actual behavior: Shows generic error: An error occurred while trying to export the selected file**

This problem occurs since today. I am not able to export to a .bib file anymore. I haven't changed anything besides some Journal Abbreviations.

**Comment by retorquere** [comment] 2020-07-08 14:29
Thank you for including the log! This looks to be a duplicate of #1565; I have a fix that's running through the tests as we speak. Can you join that issue? A fix will appear there in 10 minutes or so.

**Comment by O2-AC** [comment] 2020-07-08 14:34
Great. Thank you so much for the quick response! I'll watch #1565 for a fix.

**Closed** 2020-07-08 14:42 UTC
Labels: bug, duplicate
