### ISSUE TITLE
Error for slash and apostrophes in export: / ' '

### ISSUE THREAD

**Issue by roboloni** [retorquere/zotero-better-bibtex#647] opened 2017-02-15 14:06 UTC
If the title (or any other field as far as I can tell) contains the combination of characters "/ ' '" (without leading and trailing double-quotes, possibly with other characters interleaved) the export (BibTeX and BibLaTeX) fails with: "An error occurred while trying to export the selected file."

As a side note: I tried to "Send Better BibTeX Error" (now apparently called "Report Better BibTeX Error") but the interface froze for minutes after clicking "Next". Much later the message "TypeError: wizard.advance is not a function" popped up – I don't know if this is of any help/relevance.

I'm on Firefox 49.0.2, Better Bib(La)TeX 1.6.94

**Comment by retorquere** [comment] 2017-02-15 14:14
Can you export such a reference to "BetterBibTeX JSON format", rename the resulting file to have a `.txt` extension, and attach it here?

**Comment by roboloni** [comment] 2017-02-15 14:32
Wow, that's fast :) Here you go:
[items.txt](https://github.com/retorquere/zotero-better-bibtex/files/777334/items.txt)

**Comment by retorquere** [comment] 2017-02-15 14:54
OK, that reproduces the bug. Looking into it.

**Comment by retorquere** [comment] 2017-02-18 15:51
OK, it looks like the problem happens deep in citeproc, which is either a bug in citeproc (BBT has been know to exercise citeproc in novel ways) or an inappropriate way of calling citeproc. The discussion on that will be happening [here](https://github.com/Juris-M/citeproc-js/issues/35). I have a proposed workaround in there which is implemented in BBT [here](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.94-br647-3601.xpi) -- it passes the one test case you gave me and all my existing tests, and I'm curious how it will do on the rest it failed on for you.

**Comment by roboloni** [comment] 2017-02-18 16:11
Thanks for looking into this! Actually, there was only one Item that caused problems (containing something like '98/'99 in the proceedings title) even though it took a while to spot it and the weird thing is that I'm pretty sure I didn't edit that Item for a long time. I think the problem occurred after a recent update (I have auto-updating enabled). I know I'm probably not beeing very helpful here but this is a good sign: I've been using better bibtex happily and free from worries – very helpful piece of software, indeed! Thanks a lot!

**Comment by retorquere** [comment] 2017-02-18 16:17
It's very helpful -- you found an edge case that I wouldn't have found myself. If I were a betting man I'd say it's an edge case in citeproc actually, but only Frank (citeproc's author) can confirm that. The place where the error happens is a dark mystery to me, but the workaround seems to do its thing safely, at least according to my regression tests. The recent update also picked up a new citeproc, which looks like introduced this problem. The pre-release I linked to should be safe to use (it's just the release + the workaround), and you'll be auto-updated to the proper release when it goes out automatically.

Please don't close this yet, I want to know what Frank thinks.

**Comment by retorquere** [comment] 2017-02-20 08:46
Too many people are going to be affected by this, so I'm going to schedule a release including this workaround. When Frank chimes in I may adjust the workaround, but we'll see about that when it happens.

**Closed by retorquere** 2017-02-20 08:46 UTC
Labels: awaiting feedback from user, bug
