### ISSUE TITLE
High CPU usage when idle

### ISSUE THREAD

**Issue by doncip** [retorquere/zotero-better-bibtex#1354] opened 2019-12-06 13:29 UTC
I am experiencing a high CPU usage (around 50%) on my Mac 10.14.6 and the latest version of Zotero 5.0.80. This is due to Better-BibTeX because the issue goes away if I disable the addon.

**Comment by doncip** [comment] 2019-12-06 13:32
Debug report: 37GR72TS-euc

**Comment by retorquere** [comment] 2019-12-06 13:53
Duplicate of #1352 - I'd appreciate it if you could test whether the proposed solution works for you too.

**Comment by doncip** [comment] 2019-12-06 13:59
Sorry for duplicate. Yes, the solution solved my problem.

**Comment by retorquere** [comment] 2019-12-06 14:42
Cool, and no worries. A release build is running which will drop in 30 minutes or so (the full test suite takes a while)

**Closed by retorquere** 2019-12-06 14:42 UTC
Labels: duplicate
