### ISSUE TITLE
Import Jabref fileDirectory, unexpected reference type

### ISSUE THREAD

**Issue by TiagoAMarques** [retorquere/zotero-better-bibtex#1058] opened 2018-08-28 09:31 UTC
(this is a thread started in the Zotero forum, but transfererred here following the advice from Emiliano) 
I have used the latext BBT version (28/08/2018) and my file is now read completely after the tweak included in the latest release, but my original question remains: the information contained in the field "File" (which is the link to pdf's in a local folder in the computer) is not imported.

**Comment by retorquere** [comment] 2018-08-28 09:55
Can you isolate one entry that does not import attachments, zip that up with the attachment (making sure to keep the trimmed bib file and the attachment in the same place), and get me a copy?

**Comment by TiagoAMarques** [comment] 2018-08-28 09:56
I just realized what is going on, but not sure how to solve it. It is related to the fact that my .bib file is used within JABREF, and there, the default folder for the pdf files is stored in the preferences. Then, the actual field file is simply the file, e.g. "file          = {:ManyAnalistsOneDataSet2018.pdf:PDF},". So actually, BBT has no way to get from the .bib the path information. However, if I add the information manually, say edit the File field to look like "file     = {C://Users//tam2//Dropbox//Trabalho//pdf//ManyAnalistsOneDataSet2018.pdf}" the import works fine. I wonder if there's a way to fix this somehow?

**Comment by retorquere** [comment] 2018-08-28 10:00
Do you know where JabRef saves its preferences?

**Comment by TiagoAMarques** [comment] 2018-08-28 10:03
LOL - I was just thinking that. If the info was in the file itself it would be possible to read it in. But as far as I can tell, it is not in the file, so it must be somewhere in the installation directory, which means that this becomes tricky. I'll try to find it. Damn, it would be so great if I managed... I guess as a work around I could build a script that adds the path to each file field before I do the import, say.

**Comment by TiagoAMarques** [comment] 2018-08-28 10:03
By the way, thanks so much for the prompt feedback. If I can ever pay back with BBT testing let me know!

**Comment by retorquere** [comment] 2018-08-28 10:11
No worries, what we're doing now is part of it. I found mine at `~/.java/.userPrefs/net/sf/jabref/prefs.xml` but I don't know how universal that is across platforms.

**Comment by TiagoAMarques** [comment] 2018-08-28 10:34
Yes, not sure either. I guess a very clumsy way would be for one to have a stage where as part of the import one could tell BBT the path of the default folder for files. But then again I also note that you not only need to add the file location to the .bib file, as you need to clean the field a bit. In general JABREF will format the file field as " file = {A:thefile.pdf:B},", so there's info A : the path : info B, where if I understand correctly info B is the file type and info A is the user file description (e.g. a preprint). An example from my bib file woul be say " file      = {The file:Goffeetal1994.pdf:PDF},". I wonder what's the easiest way to deal with this, or even if it makes sense for you to care about this since this is no longer related to bibtex import but to import of a file that was formated via JABREF and hence it has some peculiarities!

**Comment by retorquere** [comment] 2018-08-28 10:56
If you go into `File` -> `Database properties`, you can set the "general file directory". I can add support for reading that.

**Comment by retorquere** [comment] 2018-08-28 10:57
The `A` and `B` thing is already supported.

**Comment by TiagoAMarques** [comment] 2018-08-28 11:06
you are fast! OK, sorry for being daft here, but neither in Zotero nor in Jabref I find the File -> Database properties. What am I missing?

**Comment by retorquere** [comment] 2018-08-28 12:59
It's in jabref (in 3.8.2 in my case)

**Comment by blip-bloop** [comment] 2018-08-28 13:40
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.195.2668](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.195.2668.xpi) ("fixes #1058").

**Comment by TiagoAMarques** [comment] 2018-08-28 13:46
I am on JABREF 4.3.1 and can't find it there... will search for where it might be. I wonder if this might be now under Options -> Preferences -> (External file links) Main File Directory?

**Comment by retorquere** [comment] 2018-08-28 14:12
Maybe -- see if it put something in the bib file in a @comment. I'm currently trying to get JabRef 4.3.1 to run under linux (which I use) but it's a bit of a mess.

**Comment by TiagoAMarques** [comment] 2018-08-28 14:47
aha - gotcha!

**Comment by TiagoAMarques** [comment] 2018-08-28 14:49
and yes, it added  this to the .bib

@Comment{jabref-meta: fileDirectory:C:\\Users\\tam2\\Dropbox\\Trabalho\\pdf;}

so now this can be read in by you presumably!

**Comment by retorquere** [comment] 2018-08-28 14:51
A new version will be posted here in a few minutes -- that one should have it (plus it can read the old file with `@talk`)

**Comment by TiagoAMarques** [comment] 2018-08-28 14:56
You rock !

**Comment by blip-bloop** [comment] 2018-08-28 14:57
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.195.2675](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.195.2675.xpi) ("adjust tests for #1058").

**Comment by retorquere** [comment] 2018-08-28 15:03
Give 2675 a try.

**Comment by TiagoAMarques** [comment] 2018-08-28 15:13
How can I force the install? Because I already am with 5.0.195 it tells me I am up to date, but I suspect that is not with 2675 as nothing happens.

**Comment by retorquere** [comment] 2018-08-28 15:14
Builds posted on the issue tracker have to be manually installed, in the same way you installed BBT initially, so through add-ons, gear menu, install from file.

**Comment by TiagoAMarques** [comment] 2018-08-28 15:16
OK - will do and will report back!

**Comment by TiagoAMarques** [comment] 2018-08-28 15:56
hummm... did not work. Is this the right file to fetch I wonder?

https://github.com/retorquere/zotero-better-bibtex/releases/tag/v5.0.195

**Comment by retorquere** [comment] 2018-08-28 16:17
No, you want https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.195.2675.xpi (the one @blip-bloop linked to)

**Comment by TiagoAMarques** [comment] 2018-08-28 16:55
aha - did that, but apparently something failed. Installed new 2675 file ok but... Now it simply does not start the import, it just hangs. I tested on a much smaller file (about 15 references) to make sure it was not something with the big file, and it does not work either. Hummm - I guess you're starting to hate me by now!

**Comment by retorquere** [comment] 2018-08-28 16:57
Not at all - this is the only way I can improve BBT. Can you submit a BBT error log after the failed import?

**Comment by retorquere** [comment] 2018-08-28 17:34
(or after it stalls)

**Comment by retorquere** [comment] 2018-08-28 17:51
Also if you could get me a zip of that smaller file + refs I could test for myself.

**Comment by retorquere** [comment] 2018-08-28 21:26
Found at least one error, please try 2680.

**Comment by blip-bloop** [comment] 2018-08-29 05:32
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.195.2682](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.195.2682.xpi) ("adjust tests for #1058").

**Comment by retorquere** [comment] 2018-08-29 16:27
And a debug log after the hang please.

**Comment by TiagoAMarques** [comment] 2018-08-29 16:30
I don't get any debug log. It hangs and does nothing until I close the import window...? Is there a procedure to force a debug report?

Bib file:
https://www.dropbox.com/s/m2yk69v6msmu8hz/teste.bib?dl=0
(4 references, 3 with pdf links)
PDFs:
https://www.dropbox.com/s/0e42g3w2z4czh7h/Redfern_et_al-2017-Diversity_and_Distributions.pdf?dl=0
https://www.dropbox.com/s/ezvcxo3kl4qvp20/ManyAnalistsOneDataSet2018.pdf?dl=0
https://www.dropbox.com/s/sfegjbp0kpejece/Buckland%20et%20al%20monitoring%20regional%20biodiversity%20230212.pdf?dl=0

**Comment by retorquere** [comment] 2018-08-29 17:01
You can close the window. All that matters is that the log is sent after the failure.

**Comment by retorquere** [comment] 2018-08-29 17:10
I mean after you close the import you can go into the help menu and submit a better bibtex error report.

**Comment by TiagoAMarques** [comment] 2018-08-29 17:18
But there's actually no indication of a failure. I am running in debug mode, I don't see any log being created? Any way, maybe Ijust did it: D1893799825

**Comment by retorquere** [comment] 2018-08-29 18:33
It may be something windows-specific that I need to deal with because at my end (Linux) it imports without an issue. The log will tell me more.

**Comment by retorquere** [comment] 2018-08-29 18:59
The import getting stuck counts as a failure BTW.

**Comment by blip-bloop** [comment] 2018-08-29 19:00
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.195.2684](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.195.2684.xpi) ("grab title from filename as fallback").

**Comment by TiagoAMarques** [comment] 2018-08-29 19:46
How dumb can one be :) ok here it is: HFGKWBWT-euc

**Comment by retorquere** [comment] 2018-08-29 20:12
This was straight after a hang? I see `Twenty-nine teams involving 61 analysts used the same data set` as the last bit parsed before you sent the error report (probably from an abstract) but no error whatsoever.

**Comment by TiagoAMarques** [comment] 2018-08-30 12:06
Yes, that was after I closed the "Importing" window which had hanged for a while... Any thoughts?

**Comment by TiagoAMarques** [comment] 2018-08-30 12:11
I deleted manually the "abstract" field where the text above ("Twenty-nine teams involving 61 analysts used the same data set") was and re run. Still hangs, report 6S3TNDPA-euc

**Comment by retorquere** [comment] 2018-08-30 15:26
It's not the abstract field. I can see it's trying to process `:ManyAnalistsOneDataSet2018.pdf:PDF`, then after that there's nothing in the error log -- no activity of any kind, errors or otherwise -- until you open the debug report window. Which is strange, because these hangs usually are because I failed to handle an error, but that error would then show up in the log.

I can't reproduce any of this unfortunately. Can you try 2687 and get me a new log? It adds some logging around where it gets stuck.

**Comment by TiagoAMarques** [comment] 2018-08-31 10:36
Finaly, it did not hang, but it failed the import. Just imported 1 of 4 references. Any ideas... I feel we are slowly getting there - what confuses me is that before it was already importing all the references (despite with not the file info). error report F3X2G33Y-euc

**Comment by blip-bloop** [comment] 2018-08-31 13:18
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.195.2693](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.195.2693.xpi) ("what is going *on*?!").

**Comment by retorquere** [comment] 2018-08-31 13:30
This is still `teste.bib` you're importing yeah?

**Comment by retorquere** [comment] 2018-08-31 13:32
I'm asking because `teste.bib` imports flawlessly for me. This is driving me nuts.

**Comment by TiagoAMarques** [comment] 2018-08-31 14:44
OK, let me know if there's anything I should try at this moment.

**Comment by blip-bloop** [comment] 2018-08-31 14:48
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.195.2695](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.195.2695.xpi) ("nothing changed, now it works?").

**Comment by retorquere** [comment] 2018-08-31 14:49
I've removed a line of debug logging that should have absolutely no effect and now it works on my end... try 2695.

**Comment by TiagoAMarques** [comment] 2018-08-31 15:30
I have attempetd with 2695. Only 1 ref comes in. I get 
Import errors found:

    Unhandled Better BibTeX error: 'TypeError: this.jabref is undefined'
    Unhandled Better BibTeX error: 'TypeError: this.jabref is undefined'
    Unhandled Better BibTeX error: 'TypeError: this.jabref is undefined'
and Report-ID: TJNW5TTU-euc

och well...

**Comment by retorquere** [comment] 2018-08-31 16:55
Fucking hell. This is still teste.bib you linked to above?

**Comment by retorquere** [comment] 2018-08-31 16:59
Wait how the hell can one come in? this.jabref is used across all of them. Ugh.

**Comment by blip-bloop** [comment] 2018-08-31 21:43
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.195.2697](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.195.2697.xpi) ("why is this getting unset?").

**Comment by retorquere** [comment] 2018-08-31 22:07
2697 adds more logging -- would appreciate a log, as I cannot currently reproduce the problem you're seeing.

**Comment by blip-bloop** [comment] 2018-09-01 21:29
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.195.2699](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.195.2699.xpi) ("update bibtex parser").

**Comment by retorquere** [comment] 2018-09-01 21:37
2669 has an updated version of the bibtex parser -- again I cannot reproduce the error on Linux or Win10, would appreciate a log.

**Comment by blip-bloop** [comment] 2018-09-01 22:03
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.195.2702](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.195.2702.xpi) ("async parse").

**Comment by blip-bloop** [comment] 2018-09-02 10:15
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.195.2703](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.195.2703.xpi) ("just skip unparsable attachments").

**Comment by retorquere** [comment] 2018-09-02 10:16
I've tried it in various combinations on Win10 and it always works for me. 2703 further simplifies the attachment parsing (where it seems to flame out on your import), let's see how far that gets us.

**Comment by retorquere** [comment] 2018-09-03 07:15
So if you could try 2703 and get me a log I can look further -- as it stands, I can import `teste.bib` on Win10 and Linux without any errors, so I have nothing to go on.

**Comment by TiagoAMarques** [comment] 2018-09-03 09:19
Success Emiliano - working like a charm! Many many thanks for you perseverance :)

**Comment by TiagoAMarques** [comment] 2018-09-03 10:38
Hi Emiliano, Just to let you know that the pdf files appear to all benamed "Attachment", while I suspect that was not the objective. I would have expected these to keep their original name. See screenshot here to see what I mean: https://www.dropbox.com/s/hwv7g6w4wsankg4/Capture.PNG?dl=0

**Comment by retorquere** [comment] 2018-09-03 11:17
This is what it looks like for me... 2715 will drop in a few minutes, please enable debug logging, import teste.bib again, and get me a new debug log. Really strange how these things do not reproduce for me.

![capture](https://user-images.githubusercontent.com/132108/44983846-f967cb00-af7a-11e8-95e7-b8a6a5f4ee8d.PNG)

**Comment by retorquere** [comment] 2018-09-03 11:33
BTW the current behavior of BBT is "if no title is specified, take the filename"; the `file` fields in `teste.bib` do not actually specify a title (the title is in the `A` part, and that's empty in `teste.bib`); if no attachment title is set, Zotero calls it just "Attachment". But as you see in my screenshot, I do set the title. I hope to learn more from the new log.

**Comment by TiagoAMarques** [comment] 2018-09-04 08:45
Just did that, Report ID: 6WXAA4HK-euc

I note that the file name is correctly parsed at some level,  see screenshot below where the filename metadata filed in Zotero is correct

![image](https://user-images.githubusercontent.com/22343390/45020539-2bcf0200-b027-11e8-8d08-4e23d2e6f3e5.png)

**Comment by retorquere** [comment] 2018-09-04 09:33
Errr.... did this import anything at all? I see a strange error very early in the log that would indicate that BBT would not have gotten to import the bib file at all.

**Comment by retorquere** [comment] 2018-09-04 09:43
Yeah this was imported using the stock translator of Zotero because BBT errorred out early on your system. What the crap. I cannot replicate any of the problems you are seeing on my Windows VM.

Wait what. The stock Zotero translator does not support the filedirectory. How did it import the attachments at all? What is going on here? I'll retest again on my VM -- it would be so good if I could just reproduce this locally.

**Comment by retorquere** [comment] 2018-09-04 09:51
Hallelujah, I have this reproducible.

**Comment by TiagoAMarques** [comment] 2018-09-04 09:52
:)

**Comment by blip-bloop** [comment] 2018-09-04 11:36
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.196.2724](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.196.2724.xpi) ("Merge branch 'master' into 1058")

Install in Zotero by opening the "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File..."..

**Comment by retorquere** [comment] 2018-09-04 12:04
Try 2724

**Comment by TiagoAMarques** [comment] 2018-09-04 14:26
It worked! Fantastic :^)

**Comment by retorquere** [comment] 2018-09-04 15:02
Finally.

So remember when I said I must be overseeing something stupid simple? Turns out I have updated external dependencies locally, and the cache of the automated build system I'm using (Travis) was not updated... so while the code I write myself was the same in the version you had and the version I build locally, the dependencies were incompatibly different. That's fixed now, the cache is now always updated.

.197 will drop in a few minutes, but as always, it's just a rebrand of what you have now, and you will be automatically upgraded somewhere in the next few days (I don't know the update schedule that Zotero has set for plugins). You can also manually force the upgrade from the addons screen (`Check for Updates` under the gear menu).

**Comment by retorquere** [comment] 2018-09-04 15:05
Thanks for sticking this one out BTW.

**Comment by TiagoAMarques** [comment] 2018-09-04 15:32
Great we got to a happy conclusion. Many thanks for your help on this (and all he explanations along the process!)!

**Comment by retorquere** [comment] 2018-09-04 15:47
My pleasure.

**Closed by retorquere** 2018-09-04 15:47 UTC
Labels: bug
