### ISSUE TITLE
Refresh BibTeX key doesn't work (after removing a related entry?)

### ISSUE THREAD

**Issue by ryofurue** [retorquere/zotero-better-bibtex#2401] opened 2023-02-03 08:01 UTC
### Debug log ID

5HM4UJER-refs-apse

### What happened?

0. I had four entries that had automatically generated bibtex keys "BerloffPS:2005", "BerloffPS:2005a", "BerloffPS:2005b", and "BerloffPS:2005c".
1. I removed (moved to trash bin) the second entry.
2. From the middle-click menu on the third entry, I select "Better BibTeX" > "Unpin BibTeX key" and then "Better BibTeX" > "Refresh BibTeX key".
3. The BibTeX key doesn't change.

 I want to shift the a, b, c, . . . suffixes.

[By the way, perhaps I should abandon these alphabetical suffices.Perhaps I should manually attach a very short keyword for these entries.]

**Comment by retorquere** [comment] 2023-02-03 08:40
There are 3 items in `5HM4UJER-refs-apse`:

* `BerloffPS:2005` (dynamic key)
* `BerloffPS:2005b` (pinned)
* `BerloffPS:2005c` (pinned)

`BerloffPS:2005` doesn't shift because it doesn't have to; `BerloffPS:2005b` and `BerloffPS:2005c` do not shift because you have pinned them. If you first unpin them and then refresh, they should shift.

**Comment by ryofurue** [comment] 2023-02-03 13:34
> `BerloffPS:2005b` and `BerloffPS:2005c` do not shift because you have pinned them.

You missed that bit in my initial report.  I unpinned it and then I immediately tried to refreshed it.

It reverted to the pinned status because I have set automatic pinning after 30 seconds or so.

**Comment by ryofurue** [comment] 2023-02-03 13:45
CCWJW853-refs-apse

I've made a fresh test.  This time I've switched off automatic pinning.

0. I had four entries that had automatically generated cite-keys "BerloffPS:2005", "BerloffPS:2005a", "BerloffPS:2005b", and "BerloffPS:2005c".
1. I removed (moved to trash bin) the first entry.
2. From the middle-click menu on the second entry, I selected "Better BibTeX" > "Refresh BibTeX key".
3. The BibTeX key doesn't change.
4. I tried to refresh the third and fourth entry, but none worked.

**Comment by retorquere** [comment] 2023-02-03 14:03
I can't replicate this, for me the scenario describe above does refresh the keys. A new build will drop in 10 minutes or so that adds more logging for diagnosis.

A restart really shouldn't have affected this behavior.

**Comment by ryofurue** [comment] 2023-02-05 07:33
VEQ6EEQ7-refs-apse
PZU2UHUU-refs-apse

0. I've installed [test build 6.7.54.3760](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.54.3760.xpi) and restarted Zotero.
1. Imported one paper paper twice: `IlligS.etal:2018` and `IlligS.etal:2018a`
2. Move the first entry to the trash bin.
3. Unpinned the second (Right click -> "Better BibTeX" -> "Unpin BibTeX key").
4. Immediately tried to refresh the cite key (Right click -> "Better BibTeX" -> "Refresh BibTeX key").

I repeated 3 & 4 a few times but it didn't work.

The first debug log was produced after step 1 for the two entries.  The second log was after step 4.

By the way, the above test was carried out with "Automatically pin citation key" feature. It was set to 30 seconds.  At that time, the slider was at the leftmost position even though the text box showed "30".  I couldn't change "30".

Now, I can change the setting.  I set it to "0".  "Unpin" & "Refresh"  still didn't work.

I then restarted Zotero.  Now, "Refresh" refreshes the cite key.

**Comment by retorquere** [comment] 2023-02-06 07:24
Debug logging is off, so there isn't much in the logs. Please go into the `Help` menu, then `Debug output logging`, select `enable`, recreate the problem, and then send a debug log.

Are you closing Zotero using the red close button at the top left, or by cmd-Q? BBT has a known problem on MacOS that things will flake out when you close using the red button and then reopen (while Zotero is actually still running). I'm working on fixing that but it's incredibly slow going.

> By the way, the above test was carried out with "Automatically pin citation key" feature. It was set to 30 seconds. At that time, the slider was at the leftmost position even though the text box showed "30". I couldn't change "30".

When this happens, can you go into Zotero Preferences -> Advanced -> Config Editor -> I accept, and then search for `autoPinDelay`? What it says there is the true value of autoPinDelay, both the slider and the text field should automatically reflect that value. I wonder which of the two is off.

**Comment by ryofurue** [comment] 2023-02-06 13:32
VN8Q82EF-refs-apse
9WLRBS5W-refs-apse

This report is exactly the same as my previous one, except that the "Automatically pin citation key" feature is off this time (and therefore I didn't do the unpin step).  I think the debug log has been on all the time because I didn't see the "Enable debug log" message before submitting the logs.

**Comment by retorquere** [comment] 2023-02-06 14:38
debug logging is on in both. I'll need to add more trace logging to see what's happening.

**Comment by retorquere** [comment] 2023-02-07 08:25
Can you install 3771, restart with logging enabled, reproduce, and send a new log?

**Comment by ryofurue** [comment] 2023-02-07 10:05
94L9FGZX-refs-apse
TFFVBXM3-refs-apse

0. I installed 6.7.54.3771 and restarted Zotero
1. Tried to send a BBT debug log, but the debug-log pane demanded restart. I restarted Zotero again.
2. Sent a BBT log for `IlligS.etal:2018` and `IlligS.etal:2018a`.
3. Removed the first entry.
4. Tried to refresh the cite key of the second entry.

This time, **refresh worked!!!!**

Somehow the test build cured the problem?

**Comment by retorquere** [comment] 2023-02-07 11:42
A little disappointing, I just added logging. Can you try 3772? That just removes the logging again.

**Comment by ryofurue** [comment] 2023-02-08 14:23
PFHFH6U9-refs-apse
49HPTXNL-refs-apse

So, with 3772, the problem has returned.  Remove the first entry and try to refresh the cite key of the second, which doesn't work.

**Comment by retorquere** [comment] 2023-02-09 06:57
3775 adds the logging back. I need a debug log that has the extra logging for diagnosis. I cannot reproduce the problem on my end.

**Comment by ryofurue** [comment] 2023-02-09 13:52
BVG5HIN7-refs-apse
4AVTYEU9-refs-apse

Now, I reproduced the problem with 3775.
0. I installed 6.7.54.3775 and restarted Zotero.
1. Tried to send a BBT debug log, but the debug-log pane demanded restart. I restarted Zotero again.
2. Sent a BBT log for `IlligS.etal:2018` and `IlligS.etal:2018a`.
3. Removed the first entry.
4. Tried to refresh the cite key of the second entry. I tried again.  The **refresh didn't work.**
5. Sent another BBT log for  `IlligS.etal:2018a`.

**Comment by retorquere** [comment] 2023-02-09 15:18
If you enter `V5PPQXXH` in the search field, do you see any items?

**Comment by ryofurue** [comment] 2023-02-09 15:25
> If you enter `V5PPQXXH` in the search field, do you see any items?

No.  (But, what a mysterious question!)

**Comment by retorquere** [comment] 2023-02-09 15:59
It's the internal key of the item you deleted. Is the deleted item still in the trash? If you empty the trash, does the other item refresh? That would still be an error in BBT, but I now have a clearer picture of what I'm looking for.

**Comment by retorquere** [comment] 2023-02-09 16:05
A new build will drop here again soon. Can you go into the advanced prefs and turn on `extensions.zotero.translators.better-bibtex.log-events`, then replay the scenario and send a debug log? You can go into `Help` and turn on debug logging before replaying, then it doesn't need an extra restart.

**Comment by ryofurue** [comment] 2023-02-09 17:38
> It's the internal key of the item you deleted. 

I see! That makes sense.

> Is the deleted item still in the trash?

I didn't check but it should have been, because I had never emptied the trash.

> If you empty the trash, does the other item refresh?

I then emptied the trash and found that the other item refreshes now!

During this procedure, I never restarted Zotero.

**Comment by retorquere** [comment] 2023-02-09 18:09
I still need a log from 7386, because it looks like I'm missing deletion notifications. BBT thinks the item still exists, which is why the other didn't refresh.

**Comment by retorquere** [comment] 2023-02-10 00:21
A new build will drop here in 10 minutes or so, you know the drill by now.

**Comment by retorquere** [comment] 2023-02-10 00:23
Can you go into preferences -> `Advanced` -> `Config Editor` -> `I accept the risk` -> search for `scrubDatabase`, double-click it to set it to `true`, then restart Zotero.

**Comment by ryofurue** [comment] 2023-02-10 12:50
XTRZN4XY-refs-apse
G6XSEAJI-refs-apse
S8X2EHWM-refs-apse

Using test build 3793. `scrubDatabase` is true.

1. Got the two entries.
2. Removed the 1st entry.
3. Tried to refresh the 2nd entry.  It didn't work.
4. Emptied the trash bin.
5. Refreshed the 2nd entry. It worked.

I sent one log after step 1, another after step 3, and another after step 5.

**Comment by retorquere** [comment] 2023-02-10 22:08
Can you go into the config editor again, search for `translators.better-bibtex.log-events`, toggle it to `true`, then replay the scenario?

**Comment by ryofurue** [comment] 2023-02-12 06:55
GCXWFRAR-refs-apse
TFZJCILU-refs-apse

The above logs are before and after removing the 1st entry, after 6.7.54.3803 had been installed and Zotero restarted.

> search for `translators.better-bibtex.log-events`

I must be missing something but when I searched for `log-`, I found only ". . . log-animations".  When I searched for `better-bibtex.l` I found only `better-bibtex.language`

**Comment by retorquere** [comment] 2023-02-12 16:29
I forgot that this was a fully hidden preference. With 3812 you can turn on `logEvents`.

**Comment by ryofurue** [comment] 2023-02-13 12:12
9CV6GPXR-refs-apse
NXYM9HNL-refs-apse

The above logs are before and after removing the 1st entry, after 6.7.54.3812 had been installed, Zotero restarted, `logEvents` turned on, and Zotero restarted again.

**Comment by retorquere** [comment] 2023-02-13 13:54
Again please. Sorry for the drudge work, but I haven't been able to reproduce it locally.

**Comment by ryofurue** [comment] 2023-02-13 15:10
> Sorry for the drudge work

Don't apologize. I thank you for your hard work. I just do the test once a day or less.  It's very little work on my part.  I'll use the latest test build tomorrow.

**Comment by ryofurue** [comment] 2023-02-14 12:26
PZJIMPF4-refs-apse
ECVVY2QJ-refs-apse

Test build 6.7.54.3820 with `. . . .better-bibtex.logEvents` = true.  Zotero's Debug Output Logging has been enabled.

The first log was before the 1st duplicate bib entry was removed. The second log was after I removed the 1st entry and tried to refresh the cite key of the 2nd entry.

**Comment by retorquere** [comment] 2023-02-15 09:52
Can you get me a new log from 3836?

**Comment by ryofurue** [comment] 2023-02-15 11:51
ZF3LS3RX-refs-apse
BMXKBLS6-refs-apse

Using [test build 6.7.54.3837](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.54.3837.xpi).  Everything else was just as before (I think).

**Comment by retorquere** [comment] 2023-02-15 13:55
I don't have a fix yet, this is all still just diagnosis. A new build will drop soon for further diagnosis.

**Comment by ryofurue** [comment] 2023-02-16 14:40
3E7UHP8J-refs-apse
RBI2R9GA-refs-apse

Using [test build 6.7.54.3842](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.54.3842.xpi). Everything else is the same (I think).

**Comment by retorquere** [comment] 2023-02-16 17:08
New log again plz

**Comment by retorquere** [comment] 2023-02-17 19:14
Can you try 3856? I think I have finally found the cause.

**Comment by retorquere** [comment] 2023-02-18 16:34
Cool! Turns out the culprit was sync - zotero would send notifications to plugins that trashed items are modified during sync, and I had assumed only non-deleted items would ever get modification notices, so I would actually regenerate the key when the trashed item was synced. This also explains why my test suite couldn't reproduce the problem - it's not synced.

**Closed** 2023-02-19 10:56 UTC
Labels: bug, awaiting-user-feedback
