### ISSUE TITLE
Automatic exporting seems to have broken since last Zotero release

### ISSUE THREAD

**Issue by satikusala** [retorquere/zotero-better-bibtex#1920] opened 2021-09-08 17:05 UTC
**Zotero version:**
5.0.97-beta.43+c5d89f6d0
**BBT version:**
Aug. 31
**Support log ID:**

**Exporter used:**
Better BibTex
**Expected behavior:**
After checking exportOptions.keepUpdated any changes to my file will automatically be reexported. 

**Actual behavior:**
I am finding that I have to manually reexport every time. This used to work, before the Aug. 31 Zotero update.

**Comment by retorquere** [comment] 2021-09-08 17:12
If you don't submit a support log, I can't possibly help you. Please turn on debug logging, reproduce the problem by changing an item that you expected to trigger an auto-update, and submit a log, as per the instructions under point 2.

I'm trying to phrase the request in the template as politely as I can, and the reminder by the bot is as polite as I can make it, but the support log really isn't optional. Auto-export obviously isn't broken for everyone, as it works for me, and it's tested at least once a day by the automated tests. Without a support log, I would have to resort to guessing, and that's really not a great use of either of our time.

**Comment by retorquere** [comment] 2021-09-09 18:01
If you don't submit a support log, I have no choice but to close this issue. Without the support log I cannot do anything. It's just a few clicks.

**Comment by satikusala** [comment] 2021-09-09 18:40
We’ll, you’re assuming I know how to do that in the context of this ticket.

I think I figure it out: 5JVB6SBF-euc.

BTW, the problem seems to have resolved itself when I enabled debugging. Does bebugging have to be on for the out export to work. Once I turned it on the option string change to Keep updated. It wasn’t that before. What are the implications of have the debugging on?


Michael J. Becker
CEO
Identity Praxis, Inc.
***@***.***
M: +1-408-242-5733
https://www.linkedin.com/in/privacyshaman/

Check my availability & schedule meeting with me: 30 MIN or 60 MIN

**Comment by retorquere** [comment] 2021-09-09 19:14
I don't dismiss the possibility that the instructions are unclear or incomplete - suggestions on how to improve them very much welcome. Given how familiar I'm with BBT, it's hard for me to know what others don't understand about it. 

Debugging on or off should have zero influence on this problem - does the problem return of debugging is off? That would be annoying, but even with logging off, a support log might still have captured the error. With debugging off, zotero doesn't log nothing, just substantially less.

I'll look at the log when I'm back at my computer, maybe there's still something there, but of the problem doesn't occur before you submit a log, it's not very likely.

**Comment by satikusala** [comment] 2021-09-09 19:18
thanks. :) seems to be ok now. I’ll let you know if it returns. Can’t tell if debugging is off or on right now, as there is no clear “disable” state.

Thanks. You can close ticket for now.


Michael J. Becker
CEO
Identity Praxis, Inc.
***@***.***
M: +1-408-242-5733
https://www.linkedin.com/in/privacyshaman/

Check my availability & schedule meeting with me: 30 MIN or 60 MIN

**Closed** 2021-09-12 19:55 UTC
Labels: export

**Comment by retorquere** [comment] 2021-09-17 06:44
Zotero automatically turns off logging at start unless you have enabled "Start with debug logging", and with the next start after that, it's off again.
