### ISSUE TITLE
Protect math sections

### ISSUE THREAD

**Issue by choeffer** [retorquere/zotero-better-bibtex#1148] opened 2019-03-11 09:37 UTC
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

# Bug classification

## Exporting references
report ID: MCWAADUW-euc

I have a problem with exporting the following entry (csv exported):

```
﻿"Key","Item Type","Publication Year","Author","Title","Publication Title","ISBN","ISSN","DOI","Url","Abstract Note","Date","Date Added","Date Modified","Access Date","Pages","Num Pages","Issue","Volume","Number Of Volumes","Journal Abbreviation","Short Title","Series","Series Number","Series Text","Series Title","Publisher","Place","Language","Rights","Type","Archive","Archive Location","Library Catalog","Call Number","Extra","Notes","File Attachments","Link Attachments","Manual Tags","Automatic Tags","Editor","Series Editor","Translator","Contributor","Attorney Agent","Book Author","Cast Member","Commenter","Composer","Cosponsor","Counsel","Interviewer","Producer","Recipient","Reviewed Author","Scriptwriter","Words By","Guest","Number","Edition","Running Time","Scale","Medium","Artwork Size","Filing Date","Application Number","Assignee","Issuing Authority","Country","Meeting Name","Conference Name","Court","References","Reporter","Legal Status","Priority Numbers","Programming Language","Version","System","Code","Code Number","Section","Session","Committee","History","Legislative Body"
"RZMP88CJ","webpage","","","\input Wiki .:. goLaTeX - Mein LaTeX-Forum","","","","","https://golatex.de/wiki/%5Cinput","","","2019-03-11 07:01:19","2019-03-11 07:01:19","2019-03-11 07:01:19","","","","","","","","","","","","","","","","","","","","","","","/home/pink/Dokumente/AIT_Master/4th_semester/zotero/storage/TYX7X2MB/input.html","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""
```

I have chosen BetterBibLaTex as export format. It gets exported as following:

```
@online{InputWikiGoLaTeX,
  title = {$\backslash$input {{Wiki}} .:. {{goLaTeX}} - {{Mein LaTeX}}-{{Forum}}},
  url = {https://golatex.de/wiki/%5Cinput},
  urldate = {2019-03-11},
  file = {/home/pink/Dokumente/AIT_Master/4th_semester/zotero/storage/TYX7X2MB/input.html}
}
```

and this breaks biblatex when creating the bibliography. Following added braces fix it:

working (added braces around `$\backslash$input`):

```
@online{InputWikiGoLaTeX,
  title = {{$\backslash$input} {{Wiki}} .:. {{goLaTeX}} - {{Mein LaTeX}}-{{Forum}}},
  url = {https://golatex.de/wiki/%5Cinput},
  urldate = {2019-03-11},
  file = {/home/pink/Dokumente/AIT_Master/4th_semester/zotero/storage/TYX7X2MB/input.html}
}
```

If you need more information please let me know.

**Comment by retorquere** [comment] 2019-03-11 09:49
If I stick that in this MWE it compiles just fine for me (tested on Overleaf and using `latexmk -pdf`):

```
\documentclass{article}

\usepackage[american]{babel}
\usepackage[style=authoryear]{biblatex}

\usepackage{filecontents}
\begin{filecontents*}{test.bib}
@online{InputWikiGoLaTeX,
  title = {$\backslash$input {{Wiki}} .:. {{goLaTeX}} - {{Mein LaTeX}}-{{Forum}}},
  url = {https://golatex.de/wiki/%5Cinput},
  urldate = {2019-03-11},
  file = {/home/pink/Dokumente/AIT_Master/4th_semester/zotero/storage/TYX7X2MB/input.html}
}
\end{filecontents*}
\addbibresource{test.bib}
\begin{document}

From \parencite{InputWikiGoLaTeX} we see that \ldots

\printbibliography

\end{document}
```

**Comment by retorquere** [comment] 2019-03-11 09:51
(the CSV export isn't necessary BTW -- the debug report gets me an importable copy of the reference, and Zotero can't import the CSV data)

**Comment by choeffer** [comment] 2019-03-11 10:17
This is also working for me.

```
\documentclass{article}

\usepackage[american]{babel}
\usepackage{csquotes}
\usepackage[backend=bibtex,style=numeric]{biblatex}

\addbibresource{test.bib}
\begin{document}

From \cite{InputWikiGoLaTeX} we see that \ldots

\printbibliography

\end{document}
```

Seems that it is a problem with the ieee style. When using style=ieee the code is broken again, could you also please verify this?

**Comment by moewew** [comment] 2019-03-11 10:41
How else could it be, sentence casing is the culprit here. Math mode must be protected by a pair of braces from `\MakeSentenceCase*`. (The standard styles don't apply sentence casing, so the issue can't be reproduced there, `biblatex-ieee` on the other hand does and throws errors.)

```latex
\documentclass{article}

\usepackage[american]{babel}
\usepackage[style=authoryear]{biblatex}

\DeclareFieldFormat{titlecase}{\MakeSentenceCase*{#1}}

\usepackage{filecontents}
\begin{filecontents*}{\jobname.bib}
@book{elk,
  author = {Anne Elk},
  title  = {{$\backslash$input} Lorem Ipsum},
  year   = {2019},
}
@book{elkb,
  author = {Anne Elk},
  title  = {\textbackslash input Dolor Sit},
  year   = {2019},
}
\end{filecontents*}
\addbibresource{\jobname.bib}

\begin{document}
From \autocite{elk,elkb} we see that \ldots

\printbibliography
\end{document}
```

One might want to discuss whether `$\backslash$input` is the best translation of `\input`. I would probably prefer `\textbackslash` outside of math mode, but the whole issue of escaping is tricky.

**Comment by retorquere** [comment] 2019-03-11 11:01
I thought that `$\backslash$` was more widely supported than `\textbackslash`, but if that is not a problem, that's easy to change in BBT.

Zotero doesn't support math, so any math that ends up being exported by BBT is me abusing math-mode to reproduce certain characters, so case-meddling might actually be desirable. If you want *actual* math output, you should certainly protect it using `<pre>` or `nocase`.

So in the case above, how can I export something that doesn't break IEEE (which is a horrid style BTW, just sayin') but that still allows case-meddling?

**Comment by moewew** [comment] 2019-03-11 12:31
Mhhh, AFAICS `\textbackslash` is defined in the kernel, so I don't think it is less widely applicable than `$\backslash$`, but I'm no expert in this matter, so take my advice with a grain of salt.

Math in initial position must be protected or it blows up. Of course then its case is not changed. I don't know how exactly you (ab)use math mode and don't know what kind of case change you would like to have applied to maths, but I can't think of a way to get case change going inside protected math at the moment, sorry.

**Comment by retorquere** [comment] 2019-03-11 12:53
Anything that has `"math": true` [here](https://github.com/retorquere/unicode2latex/blob/master/dist/ascii.json) has that because I couldn't find a non-math equivalent for that character. I use non-math when I can.

**Comment by moewew** [comment] 2019-03-11 13:27
https://github.com/retorquere/unicode2latex/blob/bd5fece686b7d71f003b4ad6b64b10ca9efc942c/dist/ascii.json#L27

looks a bit odd, non-math `\-` seems more appropriate.

Anyhow, I didn't have an extensive look at all `math` occurrences what with Firefox reporting more than 1000 hits for `math` on that page, but it seems that most replacements are macros that won't be affected by case change anyway. So I don't think you stand to lose a lot if you protect math mode by default.

**Comment by retorquere** [comment] 2019-03-11 13:33
`\-` comes from https://www.w3.org/2003/entities/2007xml/unicode.xml . If it can be text, that has my preference.

I'll take a look at protecting math mode.

**Comment by retorquere** [comment] 2019-03-11 17:50
So all math mode, or just at the start of the text? I get enough complaints about braces as it stands.

**Comment by moewew** [comment] 2019-03-11 20:12
To be on the safe side you'd need the protection everywhere: `biblatex-ieee` does some additional pre-processing and applies `\MakeSentenceCase` separately for all substrings separated by a colon. So
```latex
\documentclass{article}

\usepackage[american]{babel}
\usepackage[style=ieee]{biblatex}

\usepackage{filecontents}
\begin{filecontents*}{\jobname.bib}
@article{elk,
  author = {Anne Elk},
  title  = {Lorem Ipsum $A^2+B^2=C^2$: $X^2+Y^2=Z^2$},
  year   = {2017},
}
@article{elkb,
  author = {Anne Elk},
  title  = {Lorem Ipsum {$A^2+B^2=C^2$}: {$X^2+Y^2=Z^2$}},
  year   = {2018},
}
\end{filecontents*}
\addbibresource{\jobname.bib}

\begin{document}
From \autocite{elk,elkb} we see that \ldots

\printbibliography
\end{document}
```
also breaks. It is not inconceivable that other styles would do similar things. (Plus, as I mentioned before math mode generally benefits from case protection).

Of course that would make

> `Lorem A$^2$+B$^2$=C$^2$`

even more terrible

> `Lorem A{$^2$}+B{$^2$}=C{$^2$}`

**Comment by retorquere** [comment] 2019-03-11 20:23
I already do re-protection at subsentence starts, but "on the safe side" has different meanings here. The math-mode code I generate is *never* for actual math, as Zotero has no entry method for it -- if there are text-ish characters that I output as math, it is entirely plausible that I'd want them to be subject to case-folding. *Actual* math would have to be entered with the BBT-specific `<pre>`, which can have any protection you want, but the sample you provide above is simply not something BBT generates.

**Comment by moewew** [comment] 2019-03-11 20:47
Well, if you are confident that you already add the necessary protection where a style might need it then that's fine. Of course it is hard to know what styles might do and you will have to find a balance if you don't want to apply blanket protection to all math modes.

I maintain that for the most part exempting even your text-replacement-math from case change does not offer a great advantage for the average user since many replacements are to commands that by their very nature will not be changed in case either way and on balance I would opt always to protect math mode. But if you think that you can benefit from not protecting math mode to make use of the case change, then it is not unreasonable at all not to protect math mode.

**Comment by retorquere** [comment] 2019-03-11 20:58
I'm not confident about this (and I'm still busy right now on extending it to math mode to resolve this issue), but a blanket coverage of math is not much different than handling caps protection by wrapping the whole field in an extra `{{...}}` and being done with it. That's not the right approach.

I'm not sure how to understand the second part -- if many replacements are not affected by case-meddling, it doesn't matter whether I protect them one way or the other, but if there *are* instances (and I don't know whether there are), people are going to complain, because they cannot (by design limitation in Zotero) have entered this as math. And as a matter of pragmatism, I've never seen protected-math bibtex files, and I'm going to assume people only do protect math when they hit these cases in styles like IEEE.

AAMOF from a technical POV, just protecting all math is the easiest option for me, but that doesn't automatically make it the right option.

BTW, if I have a title that starts with `<^2`, would IEEE be satisfied with `{$<$}$^2$`, or must all leading math be protected as one unit?

**Comment by moewew** [comment] 2019-03-11 21:28
Apparently I was overly cautious when I stated earlier that math mode in initial position must be protected. In fact math mode in other positions can also blow up if it is unprotected. *Very* simple stuff like `$A$` usually works fine, but still usual if not that simple stuff `$^{2}$` and `$\geq$` already blows up.

Another example comes directly from your list. Suppose I have U+1D419: *MATHEMATICAL BOLD CAPITAL Z* (UTF-16: 0xD835 0xDC19) in a title. If I read https://github.com/retorquere/unicode2latex/blob/4e892a5d84090bab06050a7b273c5316c7e8954e/dist/ascii.json#L2793 correctly that would give me `$\mathbf{Z}$` in the title.

```latex
\documentclass{article}
\usepackage[american]{babel}
\usepackage{csquotes}
\usepackage[style=authoryear]{biblatex}

\DeclareFieldFormat{titlecase}{\MakeSentenceCase*{#1}}

\usepackage{filecontents}
\begin{filecontents*}{\jobname.bib}
@article{elk,
  author = {Anne Elk},
  title  = {Lorem Ipsum $\mathbf{Z}$},
  year   = {2017},
}
\end{filecontents*}
\addbibresource{\jobname.bib}

\begin{document}
From \autocite{elk} we see that \ldots

\printbibliography
\end{document}
```
The issue can be solved by adding braces
```
  title  = {Lorem Ipsum {$\mathbf{Z}$}},
```

So I probably should have stated right from the start that math mode needs to be protected by braces. The LaTeX-side implementation of `\MakeSentenceCase` is massively complicated and I can't say I have understood it, so for cases like this I usually have to go by observed behaviour. I apologize for the confusion.

My second point wasn't very clear, sorry. My point is that the primary issue with math mode and `\MakeSentenceCase` is that `\MakeSentenceCase` is very fragile and blows up over un-braced uses of math mode (it may not blow up for some very simple cases, but that is accidental from what I can see). The question of whether or not those braces (which are necessary to prevent the math mode from blowing up) actually apply case protection or not is secondary for me. I personally believe that the additional case protection they offer are generally a good thing (you wouldn't want to have your math formulas case changed), but I appreciate that your use case for math mode is different. Even there I believe you don't gain a lot from not affording the protection, since many things you do have won't be case changed either way. Since you don't stand to gain a lot from not protecting math (the cases where you want and can actually get case changed math are not abundant), but stand to lose quit a lot (it blows up in your face), my advice is to blanket protect math.

Re your last questions: My experiments suggest that `{$<$}$^2$` is enough (if horrible), but I can't back this up with knowledge of the implementation, so your observations are as good as mine.

**Comment by retorquere** [comment] 2019-03-11 21:56
I appreciate your help, but please, on this one part:

> I believe you don't gain a lot from not affording the protection, since many things you do have won't be case changed either way

"many" doesn't help me here. I don't consider the "not-many" as acceptable fallout without knowing what that fallout might be. Case handling is easily one of the more intricate things BBT does, and I don't want to make sweeping changes without knowing what I'm getting into. It's not something that I feel needs to fixed with so much hurry that we can't stop to think about this -- BBT has existed for *years* before this came up, certainly we have time to think about this.

That said, I'm interested in generating output that doesn't blow anything up, but I'd appreciate it if you'd be less dismissive of the case handling in BBT. I understand you're not interested in the case handling and you'd rather just have everything brace-protected, and I'm looking for a middle way, but from BBTs point of view, "blanket protect math" is just "who cares about people who enter text", because from the POV of BBT, *people have never entered math*.

If we are *sure* there is no case-affected stuff that I output as math-mode, then sure, we can do blanket protection, but we don't know this. I'm totally fine with doing a blanket protection for anything that's labeled as explicitly mathematical in the unicode table. Maybe that covers everything -- we'd have to check.

@nickbart, any thoughts?

**Comment by moewew** [comment] 2019-03-11 23:06
I say "many" because I haven't read the whole list of replacements. For now the only examples where I can verify that you would see a difference between protected and unprotected math are the uppercase Greek letters for which LaTeX does not have a dedicated control sequence (on that note `ΑΘΗΝΑΙ` if converted to `$A$$\Theta$$E$$N$$A$$I$` would come out as `$a$$\Theta$$e$$n$$a$$i$` "*a*Θ*enai*" in lower case, because LaTeX does not attack control sequences, this is one of the reasons why I am sceptical that you can really benefit from case change here: the results can be extremely unexpected). Other examples explode without brace protection or would not be case-changed even if they did not explode simply because they consist of only a control sequence (`\Leftrightarrow`).

My main worry is that unprotected math mode only works accidentally in some simple cases and that it might break if something in the implementation of `\MakeSentenceCase` changes. So I can not in good faith recommend to use unprotected math mode. Of course my worries may be entirely unfounded, but I would have considered it negligent if I had not emphasised that issue (which I believe I have done *ad nauseam* now).

I am sorry if I offended you. I am well aware of (some of) the difficulties of the whole case changing business and I know full well that you have done a lot of difficult work in that area. I also appreciate that the whole business is quite a bit more involved on your side than for my simple uses (and than I would like it to be). I will admit that I'm not particularly fond of the whole sentence case thing in general as it stands now because it is extremely thorny business with lots of edge cases and weird fringe behaviour (my main conceptual problem is that curly braces mean too many things at once for BibTeX), but that is just how it is and has nothing to do with BBT.

On one point I must protest though: I do emphatically *not* want *everything* to be case protected (the WYSIWYG `title = {{This Title Is Fully Protected}},` is one of my pet hates), but I do believe (on balance) that it is better to protect all math mode in braces.

(PS: I think you pinged the wrong Nick Bart.)

**Comment by retorquere** [comment] 2019-03-11 23:30
I reacted too strongly. Sorry for that.

**Comment by blip-bloop** [comment] 2019-03-12 00:01
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.58.3580](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.58.3580.xpi) ("should be the last")

Install in Zotero by downloading [test build 5.1.58.3580](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.58.3580.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment] 2019-03-12 06:47
3580 has the changes you want. @choeffer, I'd appreciate it if you could test.

@moewew, I reacted too emotionally. Part of my irritation comes from way too many people asking "just use less braces" or "just use more braces" without knowing the process BBT goes through, but that does not apply to you.

**Comment by choeffer** [comment] 2019-03-12 06:59
style numeric and ieee are working fine now in biblatex.

newly created bibtex key is now:

@online{InputWikiGoLaTeX,
  title = {\textbackslash{}input {{Wiki}} .:. {{goLaTeX}} - {{Mein LaTeX}}-{{Forum}}},
  url = {https://golatex.de/wiki/%5Cinput},
  urldate = {2019-03-11},
  file = {/home/pink/Dokumente/AIT_Master/4th_semester/zotero/storage/TYX7X2MB/input.html}
}

Thanks for your fast response and solving the issue.

**Comment by retorquere** [comment] 2019-03-12 09:44
5.1.59 is running for release with this change

**Closed by retorquere** 2019-03-12 09:44 UTC
Labels: question
