### ISSUE TITLE
Citation Key Not Refreshing

### ISSUE THREAD

**Issue by maxoppelt** [retorquere/zotero-better-bibtex#3074] opened 2024-11-26 15:34 UTC
### Debug log ID

YIFQ7I9H-refs-euc/6.7.256-7

### What happened?

**Description**
When using Zotero (v7.0.10) with the Better BibTeX plugin (v6.7.256) on macOS 15.1.1 (Apple M processor), the citation key in the right-hand pane does not update correctly when switching between publications. The issue persists until the application is rebooted.

**Steps to Reproduce**
- Open the Zotero application.
- Select a publication from the list.
    - The citation key in the right pane is displayed correctly.
- Select a different publication from the list.
    - The other information in the right pane updates correctly.
    - However, the citation key does not refresh and still shows the previous publication's citation key.
- Restart the Zotero application.
- Select the publication again.
   - The correct citation key is now displayed.

**Expected Behavior**
When switching between publications, the citation key in the right-hand pane should refresh and display the correct citation key for the selected publication without requiring a restart.

**Actual Behavior**
The citation key does not update when switching between publications. The correct citation key is displayed only after restarting Zotero and selecting the publication.

**Environment**
Operating System: macOS 15.1.1 (Apple M processor)
Zotero Version: 7.0.10
Better BibTeX Plugin Version: 6.7.256

Additional Notes
Other metadata fields in the right pane, such as title, authors, and publication date, appear to update correctly.
The issue seems isolated to the citation key field, potentially related to a refresh/update problem.
Please let me know if further information or additional debugging steps are required.

<details><summary>Screenshot Startup:</summary>
![01](https://github.com/user-attachments/assets/6ee816f6-dcb3-43e1-8d2e-3fa5ce2f0be4)
</details>

<details><summary>Screenshot First Publication (Correct):</summary>
![02](https://github.com/user-attachments/assets/f545f51f-2cd7-48ea-a28e-1910c0898c47)
</details>

<details><summary>Second Publication (Incorrect):</summary>
![03](https://github.com/user-attachments/assets/ed59e7be-0839-4f65-b5dd-c958cf477e7d)
</details>

<details><summary>Third Selection (Incorrect):</summary>
![04](https://github.com/user-attachments/assets/1cfe421e-3545-4eda-a86a-245c72185fa1)
</details>

<details><summary>Selection after Restart (Correct):</summary>
![05](https://github.com/user-attachments/assets/eca430ef-9730-4601-bc2f-cba48699946c)
</details>

**Comment by OnlyAlexisRaine** [comment] 2024-11-27 00:54
To add some additional information to this. I did notice that if I close out of Zotero, re-open, select and item that item's key is displaying correctly. However, now every item shows that same key. I did validate the export file that I use with Obsidiian, and the output file key's are accurate, it is just an issue with the viewing pane. 

I do see that there was a recent commit [72a2a7d](https://github.com/retorquere/zotero-better-bibtex/commit/72a2a7d83370897a7d7673b5063d3d513b97493e) which may solve this issue, just wanting on confirmation.

**Comment by mgleze** [comment] 2024-11-27 22:05
Hello
The same problem also occurs with windows. The citation key is not changed when modifying the citation. The key has been generated properly, since the citation key search works. Only its display does not change when changing the citation.

**Comment by 192933488S** [comment] 2024-11-27 22:25
I can reproduce. The exported *.bib contains the correct keys, but they are not displayed correctly in 7.0.10

**Comment by AlanHuang99** [comment] 2024-11-27 23:51
same issue here

**Comment by JDCRecomendable** [comment] 2024-11-28 02:14
I found that you have to open the associated attachment of a publication to get the correct citation key.  The info pane for that view will have the correct citation key.  Meanwhile, the info pane in the library view will still show the wrong key.  This could be a worthwhile workaround that does not necessitate restarting Zotero.

**Comment by Nicoals-James** [comment] 2024-11-28 07:47
same issue on windows. the citation key displayed normally yesterday

**Comment by retorquere** [comment] 2024-11-28 07:52
OK, I get it, more "same issue" posts are unnecessary.

**Comment by MelchiorUU** [comment] 2024-11-28 10:40
Any ETA on when this will be fixed? It is a workflow breaking bug for me :(.

**Comment by retorquere** [comment] 2024-11-28 11:10
No ETAs

**Comment by retorquere** [comment] 2024-11-28 11:13
@maxoppelt can you first upgrade BBT, then reproduce and send a new log? You're on .256

All others, what I need right now is debug logs. Without them I don't know what the state of things is on your installation of Zotero.

**Comment by NegriAndrea** [comment] 2024-11-28 11:54
I've sent you a debug log, ID IVYXRT59-euc/6.7.258-7

**Comment by mdahirel** [comment] 2024-11-28 12:45
Hi! Another debug log from my install showing the same issue, ID: NYIANJP8-euc/6.7.258-7

**Comment by maxoppelt** [comment] 2024-11-28 13:49
@retorquere: I have uninstalled the previous version and installed the new release from https://github.com/retorquere/zotero-better-bibtex/releases/tag/v6.7.258. The issue remains.

The debug log ID is: AGM3DB4F-euc/6.7.258-7

**Comment by GJoe2** [comment] 2024-11-28 18:04
If it helps, the issue was not really instanly after I update to zotero 7, something in between a pop up appear in my screen complaining about  bibtex which I really didnt care at that time, only after that I realize the bug.

I have this error in zotero, which I suspect is related to the bug
```
1732816409241	addons.xpi-utils	WARN	disabling legacy extension zoterotag@euclpts.com

[JavaScript Error: "uncaught exception: undefined" {file: "chrome://zotero/content/xpcom/file.js" line: 339}]

[JavaScript Error: "TypeError: emptyListMessage is null" {file: "chrome://zotero/content/standalone/standalone.js" line: 687}]
ZoteroStandalone</this.updateAddonsPane/<@chrome://zotero/content/standalone/standalone.js:687:7


appName => Zotero, version => 7.0.10 (x64), os => Windows 11 22631, locale => en-US, extensions => Better BibTex for Zotero (6.7.258, extension), Zotero Tag (0.3.0, extension, disabled)
```
And from zotero console I have this, which kinda tell the same thing but extended:

```
unreachable code after return statement
[util.js:205:4](resource://zotero/bluebird/util.js)
Missing resource in locale en-AU: reader.ftl
Missing resource in locale en-CA: reader.ftl
Missing resource in locale en-NZ: reader.ftl
Missing resource in locale en-AU: browser/browserSets.ftl
Missing resource in locale en-CA: browser/browserSets.ftl
Missing resource in locale en-NZ: browser/browserSets.ftl
1732816409241	addons.xpi-utils	WARN	disabling legacy extension zoterotag@euclpts.com
Missing resource in locale en-NZ: browser/browserSets.ftl
Missing resource in locale en-CA: browser/browserSets.ftl
Missing resource in locale en-AU: browser/browserSets.ftl
Missing resource in locale en-NZ: reader.ftl
Missing resource in locale en-CA: reader.ftl
Missing resource in locale en-AU: reader.ftl
Uncaught (in promise) undefined [file.js:339:13](chrome://zotero/content/xpcom/file.js)
ItemTreeColumnManager: The 'defaultIn' property is deprecated. Use 'enabledTreeIDs' instead.
ItemTreeColumnManager: The 'disableIn' property is deprecated. Use 'enabledTreeIDs' instead.
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features! [zoteroPane.xhtml](chrome://zotero/content/zoteroPane.xhtml)
unreachable code after return statement
[aboutaddonsCommon.js:39:2](chrome://mozapps/content/extensions/aboutaddonsCommon.js)
unreachable code after return statement
[aboutaddons.js:286:4](chrome://mozapps/content/extensions/aboutaddons.js)
unreachable code after return statement
[aboutaddons.js:3404:4](chrome://mozapps/content/extensions/aboutaddons.js)
Uncaught TypeError: emptyListMessage is null
    updateAddonsPane chrome://zotero/content/standalone/standalone.js:687
[standalone.js:687:7](chrome://zotero/content/standalone/standalone.js)
    updateAddonsPane chrome://zotero/content/standalone/standalone.js:687
Key event not available on some keyboard layouts: key=“i” modifiers=“accel shift alt” id=“key_importFromClipboard” [zoteroPane.xhtml](chrome://zotero/content/zoteroPane.xhtml)
DOMException: Could not get children of file(C:\Users\user\AppData\Roaming\Zotero\Zotero\Crash Reports\events) because it does not exist [CrashManager.sys.mjs:663:17](resource://gre/modules/CrashManager.sys.mjs)
    _getUnprocessedEventsFiles resource://gre/modules/CrashManager.sys.mjs:663
Missing resource in locale en-NZ: toolkit/global/wizard.ftl
Missing resource in locale en-CA: toolkit/global/wizard.ftl
Missing resource in locale en-AU: toolkit/global/wizard.ftl
Missing resource in locale en-NZ: devtools/client/toolbox.ftl
Missing resource in locale en-CA: devtools/client/toolbox.ftl
Missing resource in locale en-AU: devtools/client/toolbox.ftl

```

Does "addons.xpi-utils	WARN	disabling legacy extension zoterotag@euclpts.com" have something to do with the bug?

**Comment by retorquere** [comment] 2024-11-28 22:10
**_please_** don't paste logs. It makes it harder to keep track of what's going on in the issue. The debug log sender is there for a reason. For the same reason, don't attach logs here if the BBT log submission works. It has more information than what you can copy-paste from the debug log window, such as your BBT settings, and I have specialized tools that create an efficient workflow for dealing with logs. Everything that is not a debug log ID creates more work for me.

> I have this error in zotero, which I suspect is related to the bug

unrelated

> And from zotero console I have this, which kinda tell the same thing but extended:

unrelated.

I know you all are trying to help, but you're flooding me with messages that don't help. The debug logs are what I need. As far as I can tell, the key not refreshing is a Zotero bug for which I've posted a request to the zotero developer group.

**Comment by maxoppelt** [comment] 2024-11-29 09:23
For those looking for a way to see the citation key (while the issue remains), you can also show them as column in the list.
 
<img width="2011" alt="6" src="https://github.com/user-attachments/assets/aae26a54-1980-4338-a937-2718e674ed75">

**Comment by retorquere** [comment] 2024-11-29 09:52
Zotero has confirmed the bug. I've rolled back to the section display until it's fixed.

**Comment by mgleze** [comment] 2024-12-01 00:14
It works correctly. 
Thank you very much for everything

**Closed** 2024-12-20 16:44 UTC
Labels: reopened
