### ISSUE TITLE
[Bug/Feature]: Better Biblatex would export .bib even if uncheck the "keep updated" and "background export"

### ISSUE THREAD

**Issue by earthmoon** [retorquere/zotero-better-bibtex#2459] opened 2023-03-26 08:41 UTC
### Debug log ID

983NYQ2T-refs-euc

### What happened?

Hello,

There is a bug as we do the steps below:

1. Start the Zotero,
2. Click the "File" of the top-left in the Zotero,
3. Select the "Better Biblatex" for "Format",
4. Select the "Keep updated" and "Background export",
5. Select the location where we store the **.bib** file,
6. When we modify any information of any references in Zotero, we would find the Zotero modify the **.bib** file in time,
7. Deselect the  "Keep updated" and "Background export",
8. When we modify any information of any references in Zotero, we would find the Zotero still modify the **.bib** file in time. That is weird.

The bug I reported just contains the step 8.

Thanks.

**Comment by earthmoon** [comment] 2023-03-26 08:50
Maybe I should not choose "On change" of "Automatic export" of Better Bibtex? This function is a little duplicate of  "Keep updated" and "Background export".

**Comment by retorquere** [comment] 2023-03-26 10:08
What you find weird is just a misunderstanding of what the checkbox "keep updated" means.

The checkboxes in the export screen apply to the export you are doing at that specific point. They bear no relationship to any other export, regardless of whether the file paths happen to be the same.

So in the first export, you check "keep updated", and to Zotero that means "For the collection/library I selected for export, keep exporting them to the file I will select next".

Then you do another export, you uncheck "keep updated", and to Zotero that means For the collection/library I selected for export, export them once to the file I will select next".

So you overwrite the export file once, and then if you next update the collection/library, the promise of the first auto-export kicks in.

If you want to delete auto-export, you have already found them in the preferences, you can delete them there. There is a "Remove" button in the preferences  under the auto-export you set up.

The "on change" option just pauses all auto-exports, it doesn't permanently delete them, so it isn't a little duplicate of the "Remove" button, which removes one auto-export (the one you have selected in the prefs screen).

**Comment by earthmoon** [comment] 2023-03-26 11:31
May you tell me what is the difference between "on change" of "auto export" and "keep updated" in exporting?

**Comment by retorquere** [comment] 2023-03-26 12:12
"Keep updated" just means "when something relevant changes, schedule an export to reflect this". The "on change" setting concerns when this scheduled export actually happens: on change = immediately, on idle = when you're not using zotero, disabled = only when you explicitly say so. But in each of these cases the export is in fact scheduled to be run after a change.

**Comment by earthmoon** [comment] 2023-03-26 12:20
Thanks a lot. I know now. Regards.

**Comment by retorquere** [comment] 2023-03-26 12:39
I've updated the docs in the hopes that this is explained better now.

"Background export" is orthogonal to that, it just means that the export (whether auto or not) runs without disturbing the Zotero user interface (which all Zotero exports do except BBT+background). Auto-exports are always done in the background. For manual exports it is user choice.

**Closed** 2023-03-26 13:43 UTC
Labels: question
