### ISSUE TITLE
Spurious generation of additional folder on export

### ISSUE THREAD

**Issue by gmacpherson** [retorquere/zotero-better-bibtex#1401] opened 2020-01-16 09:54 UTC
**Report ID:**
63CE3X2P-euc

**Exporter used:**
File -> Export Library... -> Better Bibtex
BBT v5.2.7, Zotero 5.0.81, Linux

**Expected behavior:**
A bib file exported to the chosen file in the chosen location.

**Actual behavior:**
The export of the file works, but an additional folder is created in the location that Zotero is launched from.

Say I launch Zotero from location A

    cd /home/<username>/<path_A>
    zotero &

then I export a bib file to location B, the export works fine to that location, but I get an additional spurious folder created in location A, that looks like the absolute path to location B, e.g. I get a folder:

    /home/<username>/<path_A>/home/<username>/<path_B>

where the bit from the second home onwards did not exist before the export.

It looks to me like something along the lines of a check to see if the absolute path to location B exists is missing the leading /, and creating that location relative to the directory that Zotero is started in.

**Comment by retorquere** [comment] 2020-01-16 21:25
Reproducible,  and cause found. On it.

**Comment by blip-bloop** [comment] 2020-01-17 00:04
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.7.5673](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.7.5673.xpi) ("OS.Path.split strips the root component... oy vey")

Install in Zotero by downloading [test build 5.2.7.5673](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.7.5673.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment] 2020-01-17 00:37
I consider this a pretty serious problem, thanks for reporting this. For me 5673 fixes it; it'd be good to have confirmation, but I'm rolling this into a new release tomorrow afternoon CET at the latest.

**Comment by gmacpherson** [comment] 2020-01-17 10:02
No problem - thanks for developing the tool and fixing the issue so quickly.

I have successfully tested 5673:  I get the same contents in my exported .bib as before, but the problem with the spurious additional folder seems fixed.

**Comment by retorquere** [comment] 2020-01-17 10:53
Is "same content" good or bad in your perception? If bad, there's something I must fix; if good, I am going to roll out a new release.

**Comment by gmacpherson** [comment] 2020-01-17 14:20
Sorry, to be clear, "same content" is good from my perspective, there was no change from 5.2.7 to 5.2.7.5673, and there was no need for one - as far as I can tell, the export is doing what it should - there is therefore nothing more to fix.

Saying that, I noticed that at or around the 14 Jan release (5.2.7 I think), the order of item export changed from the date order of addition of the record to my Zotero db, to alphabetical on cite key, so I cannot easily verify the before and after export behaviour from that release (I have >1000 entries, although I do have the difference under git control if I really need to). All that I can say is that my LaTeX docs seem to build and look fine with the citations that I'm using, so I don't have any reason to suspect a problem.

**Comment by retorquere** [comment] 2020-01-17 14:27
Yeah sorry about that... I had assumed that people who used version control would select the "sort items for version control" option, and that behavior is now the default. Export-wise, nothing has changed. It was previously off because I thought is would gain some speed, and then it struck me that I don't actually need to sort the output, I could sort the input. And I am trying to cut down on the number of knobs and dials BBT has.

**Comment by retorquere** [comment] 2020-01-17 14:28
I'm closing a few more issues and will then cut a new release. Again thank you for reporting this, and specifically for the clear diagnosis.

**Closed** 2020-01-17 14:28 UTC
Labels: awaiting-user-feedback, bug

**Comment by blip-bloop** [comment] 2020-01-20 08:47
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.9.5702](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.9.5702.xpi) ("actually merge #1401")

Install in Zotero by downloading [test build 5.2.9.5702](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.9.5702.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".
