### ISSUE TITLE
export missing the á accent 

### ISSUE THREAD

**Issue by qiuzhu** [retorquere/zotero-better-bibtex#691] opened 2017-08-01 06:32 UTC
I use zotero 4 and download the item bibtex from the Google Schoar  that include  a author with Spanish name :

```
> @article{sanjurjo2011energy,
  title={Energy Analysis of Bare Electrodynamic Tethers},
  author={Sanjurjo-Rivo, Manuel and Pel{\'a}ez, J},
  journal={Journal of Propulsion and Power},
  volume={27},
  number={1},
  pages={246},
  year={2011}
}
```

The J. Peláez  , namely  á , when I export to bib using the bbl  ,the item becomes the  J. Pelaez, how to fix this? it seems using only zotero  export with utf8 option works fine ,but the bbl has no such option

**Comment by retorquere** [comment] 2017-08-01 07:28
Can you right-click that reference, select "submit better bibtex error, and post the debug ID you get here?

**Comment by qiuzhu** [comment] 2017-08-01 07:38
Report ID :8PKZ8HAZ

**Comment by retorquere** [comment] 2017-08-01 08:38
Can you enable extended debugging in the BBT preferences, export that reference again, and submit a new debug log? I can't reproduce this using the reference you just submitted. I can see you have the "as ascii" both disabled, but even if I enable them I get ` {Sanjurjo-Rivo, Manuel and Pel{\'a}ez, J.},` (which is what I'd expect)

**Comment by retorquere** [comment] 2017-08-01 08:40
Wait, I just noticed you didn't escape the output in your original report (I've changed that); I see that in your export you get `author={Sanjurjo-Rivo, Manuel and Pel{\'a}ez, J},`, which would be OK if you had the ascii setting for your chosen export enabled. But I also see no spaces surrounding the `=` for the fields; BBT always has a space around the `=`. Are you sure you're exporting with BBT?

**Comment by qiuzhu** [comment] 2017-08-01 09:03
thank you very much , 
when I set the BBT panel without  ` Export BibTex as ASCII ` , the export output just like this :

> @article{sanjurjo-rivo_2011_EnergyAnalysisBare,
  title = {Energy {{Analysis}} of {{Bare Electrodynamic Tethers}}},
  volume = {27},
  timestamp = {2017-07-24T06:37:41Z},
  number = {1},
  journal = {Journal of Propulsion and Power},
  author = {Sanjurjo-Rivo, Manuel and Peláez, J.},
  year = {2011},
  note = {00005},
  pages = {246},
}

Peláez with no escape a and just as it is . the debug mode Report ID is :HM4NX4E5

 when i enable the ` Export BibTex as ASCII ` , the export output just like this :
> author = {Sanjurjo-Rivo, Manuel and Pel{\'a}ez, J.},

it seems ok what I expected , so it means always keep ` Export BibTex as ASCII ` enabled?

**Comment by retorquere** [comment] 2017-08-01 09:08
This is exactly the expected behavior. If `Export BibTex as ASCII` is enabled, BBT will change any unicode characters into their equivalent LaTeX constructs. If you have it enabled, it will export unicode characters as-is. The default for BibTeX is `on`, as BibTeX processors are generally not unicode-safe; the default for BibLaTeX (which is unicode safe) is `off`, but if you like ascii-only bibliographies (as I do), you can turn it on.

(If you surround text with triple backticks the github issue tracker won't hide the backslashes)

**Comment by retorquere** [comment] 2017-08-01 10:33
Is this resolved by this explanation?

**Comment by qiuzhu** [comment] 2017-08-01 10:38
yes ,thank you very much 
and hoping the BBT5 is coming , it seems the zotero 5 more prowerfull

**Comment by retorquere** [comment] 2017-08-01 10:50
It's being worked on. Z4 is deprecated so it doesn't really matter whether Z5 is more powerful, it's the only game in town in a few months.

**Closed by retorquere** 2017-08-01 10:50 UTC
Labels: question
