### ISSUE TITLE
Error in automatic export

### ISSUE THREAD

**Issue by vrs01** [retorquere/zotero-better-bibtex#585] opened 2016-10-21 12:21 UTC
Report ID: 6PTDKX42

I want to automatically export a collection. The status of the automatic export in the Zotero preferences changes to 'Error' when I add a reference to the exported collection. I use Better BibTex for exporting.

When I disable the automatic export and use the 'export' button in the preferences the export works.

**Comment by retorquere** [comment] 2016-10-21 12:30
You don't need to disable the automatic export for that, the export button will always just fire off an export, regardless of its status.

Can you enable advanced debugging in the BBT preferences, fire off a new export there, and submit a new error log?

**Comment by vrs01** [comment] 2016-10-21 12:38
Here is the log with advanced debugging: HWNTKQ2E

**Comment by vrs01** [comment] 2016-10-21 12:59
For me, the manual export also doesn't work. I was wrong in the first post. The status stays at "pending". Sometimes an error shows up (9UDA5P9Q) but not immediately when I click the button.

**Comment by vrs01** [comment] 2016-10-21 13:00
For me, the manual export also doesn't work. I was wrong in the first post. The status stays at "pending". Sometimes an error shows up (9UDA5P9Q) but not immediately when I click the button.

**Comment by retorquere** [comment] 2016-10-21 13:07
I was already a little surprised that would work. I have at least part of the problem diagnosed, but my testing service (circleCI) is down so I currently can't do much.

**Comment by retorquere** [comment] 2016-10-21 14:29
Can you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.78-circle-3136.xpi ?

**Comment by vrs01** [comment] 2016-10-21 15:02
Manual exporting from the auto-export tab works with zotero-better-bibtex-1.6.78-circle-3136.xpi! Cool!

For the automating exporting, it works when I don't make too many changes in a row. Here's a log after several changes to my collection: E7S55XU3. Error log says: "trying to update unsynced document."

The status stays at 'pending' even when the auto-export was executed.

**Comment by retorquere** [comment] 2016-10-22 09:35
Can you try this: https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.78-circle-3142.xpi

There shouldn't be any effect from rapid changes as exports are deferred for a few seconds to see if more changes occur; only if no changes have occurred in that deferral period does the auto-export kick in. But there's something in your log about stuffing invalid objects in the DB. I'd like to know first whether that's not residual damage from the bug I solved in 1.6.78-circle-3142

**Comment by vrs01** [comment] 2016-10-22 11:31
Report: RIA82BEF

Thanks for the new version! The first change after setting up the auto-export gets exported, but every following change does not.
The time stamp after 'pending' in the auto-export tab always shows the time of the last change, so the changes get recognized.

How long is that deferral period you were mentioning?

I'm on a different system now.

**Comment by whenriques** [comment] 2016-10-22 15:10
Good morning. I'm experiencing what I believe to be the same issue as @vrs01 . Yesterday my automatic export worked fine, however this morning after I added several sources to my library, the automatic export threw an error. I have been unable to manually export. 

I read through the thread, and submitted the first error report: 9ZQ7K872
Then I enabled advanced debugging and submitted the second error report: NVCPWJM9

According to Zotero, the Better Bib(La)Tex 1.6.78 was updated today...are those the releases mentioned in the thread above that have already been worked in to an update? 

Thanks for staying on top of this @retorquere. I definitely appreciated finding this active thread as I tried to figure out the error.

**Comment by retorquere** [comment] 2016-10-22 16:46
@whenriques you're still on .78 -- the errors you see are to be expected, some of those have been fixed in 1.6.78-circle-3142. This isn't released yet, I need to make sure I got everything and the log from @vrs01 still shows errors.

**Comment by retorquere** [comment] 2016-10-22 17:01
Ugh, that was a silly mistake. Try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.78-circle-3145.xpi .

**Comment by retorquere** [comment] 2016-10-22 18:37
(@whenriques: no, .78 doesn't include the fixes above)

**Comment by whenriques** [comment] 2016-10-22 19:21
@retorquere .78-circle-3145.xpi seems to work for me. I installed it in Zotero and my library exported automatically without any errors.

**Comment by retorquere** [comment] 2016-10-22 19:47
Super. @vrs01? OK for you too? Then I can merge and release.

**Comment by vrs01** [comment] 2016-10-22 20:29
Yeah automatic export works now! Thanks a lot! 

(don't want to spoil the euphoria, but the log still shows an error: 99MHNSIH. )

**Comment by retorquere** [comment] 2016-10-22 21:54
Bummer. Can you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.78-circle-3147.xpi (and new debug log yada yada)? It looks like everything is operational but for some reason the cache doesn't do what it's supposed to.

**Comment by vrs01** [comment] 2016-10-23 06:14
circle-3147 test: IPJ2XVT9

There is still an error.

**Comment by retorquere** [comment] 2016-10-23 11:06
I should have made that explicit, sorry: I don't yet know what causes this problem or even where it occurs, this version adds logging which I hope will pinpoint the place where it happens and a potential cause.

**Comment by retorquere** [comment] 2016-10-23 21:47
Still not enough info. Can you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.78-circle-3149.xpi ? Again, won't fix the problem, still trying to diagnose the issue.

**Comment by vrs01** [comment] 2016-10-24 06:26
I tried 3149 on my linux system and no error showed up: 3KK3V5KV.
I will try it later on my windows machine. That's the one I was using for the last build.

**Comment by vrs01** [comment] 2016-10-24 06:35
Here is the log for build 3149 from the windows machine: ZJJIHFII

**Comment by retorquere** [comment] 2016-10-24 09:16
I'll look at it when I have access to my computer, but it'd be super nice if this wasn't in some way a platform dependency.  I don't have a windows system at hand, and debugging on windows is a major PITA in any case. But the debug log may have enough information. There really ought to be no difference from an extension point to of view between platforms.

**Comment by vrs01** [comment] 2016-10-24 10:24
Was playing around a bit more and got this (on linux): KGJTCFND

**Comment by retorquere** [comment] 2016-10-24 19:13
I don't see any errors in `KGJTCFND`?

`ZJJIHFII` is a timing error, fixed in https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.78-circle-3157.xpi 

`IPJ2XVT9` has this strange error for which I as of yet do not have an explanation (or a way to reproduce). If you can reproduce with circle-3157 and get me a log that'd be great.

**Comment by vrs01** [comment] 2016-10-25 09:43
With circle-3157 I only get this error:
`[JavaScript Error: "1477388465299	Toolkit.Telemetry	ERROR	TelemetryStorage::loadAbortedSessionPing - error removing ping: PingReadError JS Stack trace: PingReadError@TelemetryStorage.jsm:80:15 < TelemetryStorageImpl.loadPingFile<@TelemetryStorage.jsm:1440:13" {file: "resource://gre/modules/Log.jsm" line: 749}]`

Report ID: PGJ32PGB

**Comment by vrs01** [comment] 2016-10-25 09:46
Here is another error: INC7AHUU
`[JavaScript Error: "no element found" {file: "https://better-bibtex-error-reports-62200312.s3.eu-central-1.amazonaws.com/" line: 1}]`

**Comment by retorquere** [comment] 2016-10-25 09:49
The first (from `PGJ32PGB`) is an error from the Firefox telemetry. This is harmless and isn't caused by BBT nor does it affect BBT.

The second (from `INC7AHUU `) seems to be an old [firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=884693) that crops up every now and then. Also harmless and isn't caused by BBT nor does it affect BBT.

So it looks like we're there yeah?

**Comment by vrs01** [comment] 2016-10-25 09:54
Yes! 

Can you tell me how the error in `IPJ2XVT9 ` looked like so that I can look out for it in the future? I didn't save the logs locally.

**Comment by retorquere** [comment] 2016-10-25 09:56
You will see `undefined is not an integer-string` in the errors, and I'm keeping the logging so should it ever arise again, I should be able to pinpoint the origin. I found the origin for your case, but I'm still not entirely certain why it did that. I think I have it though.

**Comment by retorquere** [comment] 2016-10-25 10:08
Merged to master.

**Closed by retorquere** 2016-10-25 10:08 UTC
Labels: bug

**Comment by retorquere** [comment] 2016-10-25 18:25
.79 is out

**Comment by vrs01** [comment] 2016-10-26 08:36
Nice!
