### ISSUE TITLE
Import linked pdfs from bib file under Windows 10

### ISSUE THREAD

**Issue by f-brinkmann** [retorquere/zotero-better-bibtex#1522] opened 2020-05-13 17:06 UTC
I'm not sure if this is a BBT problem but I already posted on Zotero without getting an answer:
https://forums.zotero.org/discussion/83091/import-pdfs-linked-in-bibdesk-file-into-zotero-under-windows-10

I try to import bib files with linked pdfs. It worked under Mac OS but does not under Windows. Any help would be greatly appreciated!

The Report ID is: TJRD7UBY-euc
Here is the content of the file I imported. I tripple checked the file path, tried single/double quotes around the path, and tried a file name without spaces:

```
@inproceedings{Algazi2001b,
Abstract = {43 human and 2 KEMAR (small and large ears) subjects. 1250 directions measured, r =1m},
Address = {New Paltz, New York},
Author = {Algazi, V. Ralph and Duda, Richard O. and Thompson, Dennis M. and Avendano, Carlos},
Booktitle = {IEEE Workshop on Applications of Signal Processing to Audio and Acoustics},
Doi = {10.1109/ASPAA.2001.969552},
Keywords = {Spatial Audio (Bin. Tech.), HRTF; HRTF (Individualization), _done}
Month = oct,
Pages = {99-102},
Title = {The {CIPIC HRTF} database},
Year = {2001},
File = {C:\Users\panik\Documents\Uni\Literature\Papers\Algazi Duda Thompson Avendano 2001_The CIPIC HRTF database.pdf}}
```

Thanks, Fabian

**Comment by retorquere** [comment] 2020-05-13 19:23
If you import the RDF file from https://gist.github.com/64d7cbc16348fec40b0be48f61e1c08a (make sure to get the raw version), does it import the PDF?

**Comment by f-brinkmann** [comment] 2020-05-13 19:29
yes that imports the file!

**Comment by retorquere** [comment] 2020-05-13 20:03
That's bad news for me, because that means the problem is in BBT. I'll get you a debug build, because I don't have access to a windows machine.

**Comment by blip-bloop** [comment] 2020-05-13 20:27
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.22.6533](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.22.6533.xpi) ("absolute paths on Windows")

Install in Zotero by downloading [test build 5.2.22.6533](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.22.6533.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by f-brinkmann** [comment] 2020-05-13 20:57
Yesss! That did the trick - a million thanks...

**Comment by retorquere** [comment] 2020-05-13 21:16
thanks for the confirmation, will be in the next release. You can just keep using this version, it's just the current release with this patch, you'll be upgraded automatically.

**Closed by retorquere** 2020-05-13 21:16 UTC
Labels: awaiting-user-feedback, bug
