### ISSUE TITLE
Failed Better CSL JSON export

### ISSUE THREAD

**Issue by mijalche** [retorquere/zotero-better-bibtex#812] opened 2017-11-21 20:09 UTC
When I try to export My library in Better CSL JSON format, with checked Keep updated option, the export fails. 
Report ID: 6L9D6KRU
The failure happens also when I try to export without checked Keep updated option. 
Report ID: RV8UP2GZ
Keep the good work!

**Comment by retorquere** [comment] 2017-11-21 20:26
From the logs it looks to be a duplicate of #811; can you join there? There's a proposed fix on that issue.

**Closed** 2017-11-21 20:38 UTC
Labels: bug, duplicate
