### ISSUE TITLE
Error Exporting BibTex library

### ISSUE THREAD

**Issue by morgen1990** [retorquere/zotero-better-bibtex#2920] opened 2024-07-24 00:30 UTC
### Debug log ID

3EBEKLG3-euc/6.7.211-7

### What happened?

When I try to export my library as a BibTex file, I get a generic error message saying "Error: An error occurred while trying to export the selected file." I was using the latest version of BibTex then downloaded the older version to see if it solved the problem (it didn't). The screenshot below is from the Error Console if it's relevant. Thank you in advance. I'm in my last two weeks of writing my dissertation and panicking about Zotero breaking all of a sudden :*(
![Screenshot 2024-07-24 at 3 29 08 AM](https://github.com/user-attachments/assets/d57d1c48-a44e-4249-8f17-18edb8d3ce28)

**Comment by retorquere** [comment] 2024-07-24 03:17
Try build 6576. If it works, please still generate a new log. Something is wrong with an attachment in your library.

**Comment by retorquere** [comment] 2024-07-24 23:14
Did this work for you?

**Comment by morgen1990** [comment] 2024-07-25 12:16
> Did this work for you?

Yes!! It worked! Thank you soooooooo much! 

The new debug log is: JEJCU7RG-refs-euc/6.7.212.2920.6576-7

**Comment by retorquere** [comment] 2024-07-26 12:07
The attachment that caused the problem is not in `JEJCU7RG-refs-euc/6.7.212.2920.6576-7`. Can you try exporting your entire library and sending a new log?

**Comment by retorquere** [comment] 2024-07-27 17:48
The build I gave you is just a workaround, I don't know what the actual problem is yet, so I'd really appreciate a new log for diagnosis.

**Comment by morgen1990** [comment] 2024-07-27 18:34
For sure, thank you so much for your help. Here is the new debug log: 9IPWQEBB-refs-euc/6.7.212.2920.6576-7

**Comment by retorquere** [comment] 2024-07-27 22:43
Can you see if the problem remains fixed on 6603?

**Comment by morgen1990** [comment] 2024-07-28 02:34
It seems like it's working now! Thanks so much. I made another debug log in case it's helpful but I think it's working!
debug log:

FWEP2KHP-refs-euc/6.7.214.2920.6605-7

**Comment by retorquere** [comment] 2024-07-28 02:46
If it's working, I've found the error. Thanks so much for testing this. You can keep using this build, it's release-ready. I'm putting a few more finishing touches in and then I'll release a new version tomorrow or day after. You will be upgraded automatically.

**Comment by retorquere** [comment] 2024-07-28 02:53
A new build will drop here, but you can ignore that, it's a performance tweak.

**Closed** 2024-07-28 17:03 UTC
Labels: awaiting-user-feedback
