### ISSUE TITLE
Zotero 7 macOS stuck at "Preparing Sync" due to "Too Much Recursion" in BetterBibteX

### ISSUE THREAD

**Issue by kshitijgoel007** [retorquere/zotero-better-bibtex#2937] opened 2024-08-12 06:11 UTC
### Debug log ID

"Continue" button is greyed out, please see below.

### What happened?

We are seeing this error

```
[JavaScript Error: "InternalError: too much recursion" {file: "jar:file:///Users/kshitijgoel/Library/Application%20Support/Zotero/Profiles/w8hw0kdw.default/extensions/better-bibtex@iris-advies.com.xpi!/content/better-bibtex.js" line: 58124}]
```
<img width="520" alt="Screenshot 2024-08-12 at 11 40 09" src="https://github.com/user-attachments/assets/cc55d15d-d144-4688-963a-da35d252f9be">

The continue button to send the debug log is greyed out for me.

More discussion here: https://forums.zotero.org/discussion/116743/zotero-7-macos-stuck-at-preparing-sync-debug-id-d1935769910#latest

**Comment by kshitijgoel007** [comment] 2024-08-12 06:16
<img width="362" alt="Screenshot 2024-08-12 at 11 45 54" src="https://github.com/user-attachments/assets/3f69c580-58f9-431d-8cb8-c7c07f584d4d">

There is no option “Help” > “Send debug log to file.io”.

**Comment by retorquere** [comment] 2024-08-12 06:45
I'll need the rest of the log that shows the "too much recursion" error.

**Comment by retorquere** [comment] 2024-08-12 06:48
Can you install https://github.com/retorquere/zotero-debug-log ? That will keep the "Send to File.io" entry in the menu.

Do you have automatic export set up?

**Comment by kshitijgoel007** [comment] 2024-08-12 07:46
Yes I have automatic exports set up.

Debug log ID: Q5KBET5M-apse/6.7.219-7

**Comment by retorquere** [comment] 2024-08-12 07:49
If you pause them, does the problem go away?

**Comment by kshitijgoel007** [comment] 2024-08-12 08:17
Yes it does

**Comment by kshitijgoel007** [comment] 2024-08-12 09:04
No it happens generally. Also not able to add papers via the Zotero connector when better BibTeX is enabled (not sure if that is a separate issue).

**Comment by retorquere** [comment] 2024-08-12 10:26
But it goes away if you pause the auto-exports, regardless of this?

**Comment by retorquere** [comment] 2024-08-12 21:31
> But it goes away if you pause the auto-exports, regardless of this?

I will have very limited time to work on BBT for a few days starting fay after tomorrow, so I'd preferably have this analysed and fixed by then. I need this information.

Also, can you check if the problem still occurs on build 6736?

**Comment by kshitijgoel007** [comment] 2024-08-13 08:30
<img width="516" alt="Screenshot 2024-08-13 at 14 00 12" src="https://github.com/user-attachments/assets/536468d3-a071-4f02-b061-86df5ba57a28">

It seems that build 6736 is incompatible with Zotero 7 stable version.

**Comment by kshitijgoel007** [comment] 2024-08-13 08:36
> But it goes away if you pause the auto-exports, regardless of this?

Yes. When the auto-exports are paused, there are no issues. However when I set it to "On Changed" I cannot add new papers via Zotero connector and the Zotero client tries to sync forever.

**Comment by kshitijgoel007** [comment] 2024-08-13 08:37
<img width="611" alt="Screenshot 2024-08-13 at 14 06 59" src="https://github.com/user-attachments/assets/c8c51e78-ff3b-43ce-a711-08e50da66057">

When I use "On Changed" in auto-export, the zotero chrome connector does not detect that zotero is running. Maybe this helps.

**Comment by retorquere** [comment] 2024-08-13 08:41
> It seems that build 6736 is incompatible with Zotero 7 stable version.

It shouldn't be because no build drops here unless the whole test suite passes on Zotero 7 release, Zotero 7 beta, and Zotero 6. The test suite installs the plugin dropped here in an actual Zotero (albeit on Linux) and runs the tests that way.

But I see the installation problem on MacOS too. Madness. looking into it.

**Comment by retorquere** [comment] 2024-08-13 09:12
Errr... Zotero says it's incompatible but it shows no error in the logs and BBT seems to actually just work.

**Comment by retorquere** [comment] 2024-08-13 18:53
Does this work for you? If not, would you mind sharing your zotero directory and profile with me? I can't replicate the problem myself.

**Comment by kshitijgoel007** [comment] 2024-08-15 09:17
Same problem as this: https://github.com/retorquere/zotero-better-bibtex/issues/2937#issuecomment-2285670233. It says the build is not compatible.

How to share zotero directory and profile? I have not done it before.

**Comment by retorquere** [comment] 2024-08-15 09:24
The message that it is incompatible may be a zotero bug; I see that message too but it runs just fine for me. I have reported this to zotero. I need to know whether you're still seeing the recursion error.

**Comment by kshitijgoel007** [comment] 2024-08-15 09:33
I was able to fix the incompatibility issue by upgrading Zotero to 7.0.1.

I am still seeing the recursion error.

Debug log ID: KS9DUZE7-apse/6.7.221-7

**Comment by kshitijgoel007** [comment] 2024-08-15 10:15
Just realized I used the release version of BBT to test the above.

For the [test build 6.7.221.6748](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.221.6748.xpi), I am getting the incompatibility with MacOS error again.

**Comment by retorquere** [comment] 2024-08-15 10:55
Yeah I don't know why zotero shows the incompat message when literally the only difference is the version number. The recursion problem is the real issue.

**Comment by retorquere** [comment] 2024-08-15 11:15
I'm looking into it but my response times are slower than usual, the zotero 7 release is bringing in a spike of requests, and I'm currently away to a competition with limited to to get behind a computer. I'm doing my best to address the issues and will be back to normal response times on Tuesday. I don't know why zotero 7 release responds differently than the beta I was testing on.

**Comment by kshitijgoel007** [comment] 2024-08-15 14:41
No worries. Thank you for your effort and contributions.

**Comment by retorquere** [comment] 2024-08-16 21:09
Does the build work for you?

**Comment by kshitijgoel007** [comment] 2024-08-17 05:11
The incompatibility error is gone but the syncing issue is still there.

I am not able to generate a debug log when I have auto export set to "On change". The "continue" button is greyed out. The file io thing also does not result in anything (i.e, I click on it but it does not seem to do anything).

Here is another debug log when I set auto export to "Paused": W6KYSK67-apse/6.7.221.2937.6769-7

**Comment by retorquere** [comment] 2024-08-17 09:47
No errors there. A new build will drop here in a few minutes; please reproduce the error and find the line number in the log as you did in the original message. That's currently the only thing I have to go on, but line numbers have shifted because of fixes I've put in in the interim.

**Comment by kshitijgoel007** [comment] 2024-08-17 11:21
Error reported for the build above

```
1723893594458	addons.xpi	WARN	Checking /Applications/Zotero.app/Contents/Resources/distribution/extensions for addons
1723893595315	addons.webextension.better-bibtex@iris-advies.com	WARN	Loading extension 'better-bibtex@iris-advies.com': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots
1723893595863	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled
[JavaScript Error: "uncaught exception: undefined" {file: "chrome://zotero/content/xpcom/file.js" line: 335}]
[JavaScript Error: "uncaught exception: undefined" {file: "chrome://zotero/content/xpcom/file.js" line: 335}]
[JavaScript Error: "InternalError: too much recursion" {file: "resource://zotero/bluebird/debuggability.js" line: 645}]
[JavaScript Error: "InternalError: too much recursion" {file: "jar:file:///Users/kshitijgoel/Library/Application%20Support/Zotero/Profiles/w8hw0kdw.default/extensions/better-bibtex@iris-advies.com.xpi!/content/better-bibtex.js" line: 58138}]
```

**Comment by kshitijgoel007** [comment] 2024-08-25 11:42
Should I test this build?

**Comment by retorquere** [comment] 2024-08-25 12:19
That was the idea, but a new build with fixes from another issue rolled in will drop here in 10 minutes or so; please try that build.

**Comment by kshitijgoel007** [comment] 2024-08-25 13:53
It is fixed now, thanks

**Comment by retorquere** [comment] 2024-08-25 13:56
You have no idea what a relief that is. I'm putting out a new release now.

**Closed by retorquere** 2024-08-25 13:56 UTC
Labels: reopened
