### ISSUE TITLE
Better bibtex does not seem to start after update to 5.4.16

### ISSUE THREAD

**Issue by clagms** [retorquere/zotero-better-bibtex#1821] opened 2021-05-25 11:45 UTC
**edit by @retorquere if you have urgent work, grab 5.4.14. I'm debugging the problem, I expect a fix today**

---

I open zotero almost everyday, and every day it works perfectly.
Except today :)

The problem is simple to reproduce:
1. Open zotero
2. Fail to see the familiar better bidlatex initialization popup
3. Fail to see the citekey column in the references list.
4. Fail to see the citekey field in the reference view.

I'm sure this was introduced in the latest version (5.4.16), since I've in the meantime reverted back to 5.4.15 and everything is working fine.

The error log consists of many messages, similar to this one:
```
[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 280}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:280:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:246:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3500:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1086:15
```

My app specs:
```
version => 5.0.96.2, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => en-US, appName => Zotero, appVersion => 5.0.96.2, extensions => Zotero LibreOffice Integration (5.0.25.SA.5.0.96.2, extension), Zotero Word for Windows Integration (5.0.19.SA.5.0.96.2, extension), Better BibTex for Zotero (5.4.16, extension)
```

Support log ID:

**Comment by clagms** [comment] 2021-05-25 11:51
I followed the instructions to send the better bibtex log report, and got nothing.

**Comment by yhu266** [comment] 2021-05-25 11:52
I have encountered the same issue.

**Comment by retorquere** [comment] 2021-05-25 11:58
Are you both on Windows? I have it reproducible on Windows.

**Comment by yhu266** [comment] 2021-05-25 12:06
> Are you both on Windows? I have it reproducible on Windows.

I'm using the latest macOS.

**Comment by retorquere** [comment] 2021-05-25 12:47
Bummer. Maybe the windows problem gives a lead on the more general problem, but I'm on macos and I have no issue.

**Comment by retorquere** [comment] 2021-05-25 12:51
If you both just want to get on with your life, grab 5.4.14, but I'd hugely appreciate it if you both would be around to test, given that I can't reproduce on mac.

**Comment by yhu266** [comment] 2021-05-25 12:56
Thank you! I used the 5.4.15 version and it's working now.

I'd love to test it and offer more debugging info. Let me backup my files and test it with 5.4.16.

**Comment by retorquere** [comment] 2021-05-25 12:59
Build 954 solves the startup problem on Windows for me.

**Comment by shackenberg** [comment] 2021-05-25 13:03
I had the same issue and it seems to be working now with [test build 5.4.16.954](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.4.16.954.xpi). Thank you for the quick fix.

**Comment by yhu266** [comment] 2021-05-25 13:03
Build 5.4.16.954 solves the issue on macOS for me.

**Comment by retorquere** [comment] 2021-05-25 13:08
Test suite is running, release will be out in approx 10 minutes.

**Comment by retorquere** [comment] 2021-05-25 13:29
@clagms if you can confirm, we can close this issue.

**Comment by retorquere** [comment] 2021-05-25 14:06
Damn. Can you get me a full log? The actual problem happens before this.

**Comment by gkwiatk** [comment] 2021-05-25 14:13
Sure:
`[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 280}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:280:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:246:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3500:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1086:15


[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 280}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:280:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:246:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3500:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1086:15


[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 280}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:280:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:246:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3500:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1086:15


[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 280}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:280:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:246:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3500:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1086:15


[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 280}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:280:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:246:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3500:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1086:15


[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 280}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:280:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:246:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3500:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1086:15


[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 280}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:280:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:246:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3500:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1086:15


[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 280}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:280:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:246:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3500:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1086:15


[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 280}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:280:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:246:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3500:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1086:15


[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 280}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:280:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:246:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3500:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1086:15


[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 280}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:280:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:246:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3500:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1086:15


[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 280}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:280:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:246:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3500:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1086:15


[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 280}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:280:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:246:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3500:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1086:15


[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 280}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:280:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:246:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3500:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1086:15


[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 280}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:280:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:246:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3500:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1086:15


[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 280}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:280:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:246:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3500:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1086:15


[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 280}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:280:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:246:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3500:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1086:15


[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 280}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:280:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:246:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3500:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1086:15


[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 280}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:280:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:246:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3500:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1086:15


[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 280}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:280:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:246:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3500:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1086:15


[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 280}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:280:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:246:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3500:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1086:15


[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 280}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:280:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:246:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3500:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1086:15


[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 280}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:280:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:246:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3500:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1086:15


[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 280}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:280:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:246:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3500:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1086:15


[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 280}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:280:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:246:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3500:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1086:15


version => 5.0.96.2, platform => MacIntel, oscpu => Intel Mac OS X 10.16, locale => pl-PL, appName => Zotero, appVersion => 5.0.96.2, extensions => ZotFile (5.0.16, extension), Zotero Word for Mac Integration (5.0.36.SA.5.0.96.2, extension), Better BibTex for Zotero (5.4.17, extension), Zotero LibreOffice Integration (5.0.25.SA.5.0.96.2, extension, disabled)`

**Comment by retorquere** [comment] 2021-05-25 15:41
Yes! I think this has the info I need - on it!

**Comment by brienna** [comment] 2021-05-25 18:25
I downloaded the test build, but I'm still having the same problem as @gkwiatk. 

[errors.txt](https://github.com/retorquere/zotero-better-bibtex/files/6541515/errors.txt)

I was using Zotero beta when I first noticed this problem, then I downgraded to Zotero 5.0.96, but the problem is still present. 

I'm also unable to use Zotero at all, and I get this message in the library view, instead of the files: 
<img width="535" alt="Screen Shot 2021-05-25 at 2 24 32 PM" src="https://user-images.githubusercontent.com/9706870/119549260-09e0b500-bd65-11eb-9a29-bc2fcd68abff.png">

Zotero does work again if I remove the extension.

**Comment by jonnythemonster** [comment] 2021-05-25 18:28
Actually mine looks exactly like @brienna

**Comment by retorquere** [comment] 2021-05-25 19:02
Can you go into the [hidden prefs](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/), look up extensions.zotero.translators.better-bibtex.citekeySearch, disable it, and restart Zotero?

**Comment by gkwiatk** [comment] 2021-05-25 19:14
> Can you go into the [hidden prefs](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/), look up extensions.zotero.translators.better-bibtex.citekeySearch, disable it, and restart Zotero?

@retorquere It seems that nothing has changed.

[Log.txt](https://github.com/retorquere/zotero-better-bibtex/files/6541772/Log.txt)

**Comment by gkwiatk** [comment] 2021-05-25 19:33
Thanks for the instructions! 

[typescript.zip](https://github.com/retorquere/zotero-better-bibtex/files/6541900/typescript.zip)

**Comment by retorquere** [comment] 2021-05-25 19:48
I need a new log from 960. This will not fix it, I need more logging to see where the problem occurs.

**Comment by xf15** [comment] 2021-05-25 19:49
5.4.16.960 still doesn't work for me

**Comment by GitHubDoug** [comment] 2021-05-25 19:53
Hi; I ran the log instructions to generate a file 'typescript'.  Thanks for your work. Doug
[typescript.txt](https://github.com/retorquere/zotero-better-bibtex/files/6541991/typescript.txt)

**Comment by xf15** [comment] 2021-05-25 19:54
[typescript.zip](https://github.com/retorquere/zotero-better-bibtex/files/6542004/typescript.zip)

**Comment by retorquere** [comment] 2021-05-25 20:01
The builds that will drop here will only be debug builds for now -- I still don't know what causes this.

This is driving me up the wall -- *neither* of those logs show *any* activity from BBT before the error hits.

**Comment by retorquere** [comment] 2021-05-25 20:02
I appreciate you guys being patient in helping suss out this problem. I wish I could replicate the problem on one of my systems, but I haven't been able to so far.

**Comment by retorquere** [comment] 2021-05-25 20:07
slight change: it's easier for me if the file is uploaded as 

To generate a full log, on macos or linux, you will need to do the following:

Type `script <your username>.txt` on the command line. You will see 

```
Script started, output file is <your username>.txt
```

and will be back at the prompt. There, type

```
/Applications/Zotero.app/Contents/MacOS/zotero -ZoteroDebugText
```

reproduce the error, and quit zotero. You should once again see the command prompt. Type `exit`, you will see

```
Script done, output file is <your username>.txt
```

and attach the file `<your username>.txt` it generated here

**Comment by xf15** [comment] 2021-05-25 20:11
[xf15.txt](https://github.com/retorquere/zotero-better-bibtex/files/6542100/xf15.txt)

**Comment by retorquere** [comment] 2021-05-25 20:12
We have activity! I'm trying to bisect where the problem could have occurred, but this helps massively.

**Comment by retorquere** [comment] 2021-05-25 20:35
Icanhazlog?

**Comment by xf15** [comment] 2021-05-25 20:44
[xf15.txt](https://github.com/retorquere/zotero-better-bibtex/files/6542268/xf15.txt)

**Comment by retorquere** [comment] 2021-05-25 20:47
Ugh why is this so &^%@#&^%@# random! No BBT activity before the error hits.

**Comment by retorquere** [comment] 2021-05-25 20:54
Anyone around here on discord? We can do much quicker turnaround that way. https://discord.gg/D6QsyJ74

**Comment by retorquere** [comment] 2021-05-25 22:35
I've narrowed down the problem to two candidate areas, if you have time, please drop by in the morning (EU time) on discord. I need to catch some ZZs right now.

**Comment by TheVoroscope** [comment] 2021-05-26 03:22
> > Are you both on Windows? I have it reproducible on Windows.
> 
> I'm using the latest macOS.

Just as an FYI: I was having the same problem on **Linux,** so this is not just a Windows/MacOS issue. Downgrade to 5.4.14 has restored functioning again.

**Comment by yhu266** [comment] 2021-05-26 03:24
> > > Are you both on Windows? I have it reproducible on Windows.
> > 
> > 
> > I'm using the latest macOS.
> 
> Just as an FYI: I was having the same problem on **Linux,** so this is not just a Windows/MacOS issue. Downgrade to 5.4.14 has restored functioning again.

Did you try the latest patch 5.4.18? It fixes the issue for me on macOS.

**Comment by TheVoroscope** [comment] 2021-05-26 03:25
OK, will give it a go... 🤞

**Comment by TheVoroscope** [comment] 2021-05-26 03:26
Liftoff! 🚀

👍

**Comment by retorquere** [comment] 2021-05-26 04:26
That's because it's 5.8.14 (check the addons pane) in disguise so as to not get every single BBT user on here.

I'm on discord. There's only two candidates for the problem now, but since I cannot reproduce the problem on any of my systems, I'll need help for the diagnosis. I'm on discord right now.

**Comment by jonnythemonster** [comment] 2021-05-26 06:17
I try to join you later on in Discord. Unfortunately, the problem still exists for me. I cannot set a citation key and exporting is not possible.
[jonnythemonster.txt](https://github.com/retorquere/zotero-better-bibtex/files/6544201/jonnythemonster.txt)

**Comment by jonnythemonster** [comment] 2021-05-26 06:22
Ah wait, I missed the new release. This one ist Working 🚀🚀🚀 Thanks man!
[jonnythemonster.txt](https://github.com/retorquere/zotero-better-bibtex/files/6544234/jonnythemonster.txt)

**Comment by retorquere** [comment] 2021-05-26 06:24
That's because it's actually 5.4.14 in disguise. But we're really close on discord.

**Comment by GitHubDoug** [comment] 2021-05-26 13:33
Thank you.  Working on PayPal contributions, your package is a major element of workflow in my group.

**Closed** 2021-05-26 15:27 UTC
Labels: bug

**Comment by retorquere** [comment] 2021-05-26 15:29
super thanks for helping diagnose this one people! Tests for release are running.

**Comment by qqobb** [comment] 2021-05-26 15:49
@retorquere: I was just looking at

https://github.com/retorquere/zotero-better-bibtex/compare/v5.4.15...v5.4.16
https://github.com/retorquere/zotero-better-bibtex/compare/v5.4.15...master

clicking on "Files changed". There's this line which is probably unrelated to this issue, but it seems wrong, so you might want to change it:

https://github.com/retorquere/zotero-better-bibtex/blob/10f74dea521005bee3aaf05477d2f6a26e356380/util/issue-state#L42

 `brances.remote` -> `branches.remote`.

 (I was still on 5.4.15 when I read about the issue, so I didn't experience it.)

**Comment by retorquere** [comment] 2021-05-26 15:52
Fixed, but indeed unrelated, it's a script I use the find stale branches.

**Comment by retorquere** [comment] 2021-05-26 15:53
10... 9... 8...

**Comment by retorquere** [comment] 2021-05-26 15:55
(no need to manually install, it will update automatically, or you can request Zotero to update now)

**Comment by clagms** [comment] 2021-05-26 16:12
Thank you so much for all the work maintaining this plugin!

**Comment by retorquere** [comment] 2021-05-26 16:19
It is very much recommended to request to update now - while not catastrophic problems, fixing this issue also flushed out another bug, plus 5.4.19 has a rare addition of eye candy - so if you can find it ;)

**Comment by retorquere** [comment] 2021-05-26 16:39
Mind I have modest standards for what counts as eye candy - latex user after all.

**Comment by TheVoroscope** [comment] 2021-05-27 01:57
Do you mean the "exporting" scroll bar near the top of the screen (for when it does auto-export)?

**Comment by retorquere** [comment] 2021-05-27 05:17
That and the auto-exports show their progress, but for small exports they disappear pretty much before you'd notice them. It's mostly useful for people with fairly large exports.
