### ISSUE TITLE
CSL JSON/YAML export of dates with season fails

### ISSUE THREAD

**Issue by scarwire** [retorquere/zotero-better-bibtex#811] opened 2017-11-21 17:31 UTC
Hi there,

I just submitted an export bug report with the debug ID V6JCM688.

I think the problem here comes down to exporting nonstandard dates. The citations that are giving me trouble are for issues from "Spring 1985" or "Autumn 1993" (translated into French: I entered them as "printemps 1985" and "automne 1993"). Zotero itself doesn't recognize seasons as dates (it displays only "Y" for year next the date I've entered), but on Zotero 4, BBT just exported the text as entered .

These references fail when I try to export to Better CSL YAML or Better CSL JSON. They export OK (but without the season) to Better BibTeX and Better BibLaTeX. They also cause a failure when I try to export my entire library to YAML or JSON.

Hope this report helps, and many thanks for keeping this lovely extension up to date for Zotero 5.

**Comment by retorquere** [comment] 2017-11-21 19:05
Please try 4918.

**Comment by mijalche** [comment] 2017-11-21 20:36
it solves the problem for me. 
Thank you!

**Comment by retorquere** [comment] 2017-11-21 20:38
Is it also correct CSL-JSON being exported? I've cribbed the season format from samples I could find but I couldn't find authoritative sources.

**Comment by mijalche** [comment] 2017-11-21 20:42
I tested it. Also, it successfully exports CSL-JSON

**Comment by blip-bloop** [comment] 2017-11-21 20:46
:robot: this is your friendly neighborhood build bot announcing [test build 4919](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.46.4919.issue-811.xpi) ("fixes #811").

**Comment by retorquere** [comment] 2017-11-21 20:49
4919 just adds the V6JCM688 test case. I's still prefer to know if 4918/4919 solves not only the error but also outputs the correct csl-json.

**Comment by mijalche** [comment] 2017-11-21 20:52
for me 4918 exports the correct csl-json

**Comment by retorquere** [comment] 2017-11-22 07:57
Thanks for the confirmation, merged to master, new release soon.

**Comment by blip-bloop** [comment] 2017-11-22 08:02
:robot: this is your friendly neighborhood build bot announcing [test build 4921](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.46.4921.master.xpi) ("fixes #811").

**Comment by scarwire** [comment] 2017-11-22 09:22
This kinda sorta fixes the bug. BBT now outputs something like this to YAML:

```
  issued:
    date-parts:
      - - 1985
    season: spring
```

This looks fine, but pandoc-citeproc (the next step in my workflow) doesn't seem to pick up ```season: spring```, and just outputs "1985" in the citation. BBT4 used to output something like this, which worked perfectly with pandoc-citeproc:

```
  issued:
    literal: printemps 1985
```

So what do you think? Is this something that should be changed in BBT or should file a report with the people who maintain pandoc-citeproc?

Thanks again

**Comment by retorquere** [comment] 2017-11-22 11:23
The problem here is that BBT4 would output 

```
  issued:
    literal: printemps 1985
```

not because it decided that would be the best representation, but because it could not recognize this as a date, in which case both BBT4 and BBT5 throw up their hands saying "I don't know -- here's what I you gave me" and stick that in a literal field. BBT5 *does* recognize seasons, so it doesn't throw up its hands.

Whether that's desirable or not is something we could talk about, but that would be a broader discussion on heuristic (that is, non-EDTF) date recognition (which means all dates likely to show up in Zotero, in practice). We could talk about disabling that heuristic scanning whole as an option, but I'm ready to predict you by and large wouldn't like the results. The BBT date recognition is pretty good, and there are things that would be recognized as valid ETDF where the intent is clearly different (like `12/2017`, which to me is obviously December 2017, not the date range 0012-2017). The heuristic scanner picks those and others out. One of those others is `printemps 1985`.

My stance on this is

* principally, if `{ issued: { date-parts: [ 1985	], season: "spring" } }` is valid CSL data (and I don't know, because I just copied this format from samples I found, but it validates against the [CSL data schema](https://github.com/citation-style-language/schema/blob/v1.0.1/csl-data.json#L222)), BBT should be allowed to output it, as programs claiming to support CSL JSON/YAML should process it correctly
* pragmatically, if these programs are unlikely to budge, I can be reasoned with.

So yeah I'd prefer this to be reported to the citeproc-pandoc people first.

**Comment by njbart** [comment] 2017-11-22 12:08
> So yeah I'd prefer this to be reported to the citeproc-pandoc people first.

Not sure. At least the following works as expected with pandoc-citeproc:

~~~
pandoc -s -F pandoc-citeproc -t plain << EOT

Foo [@item1].

---
references:
- id: item1
  type: article-journal
  author:
  - family: Theauthor
    given: A. B.
  issued:
    year: 1985
    season: 3
  title: The title
  container-title: The Journal
  page: 123-145
  volume: 77
  language: en-US
...
EOT
~~~

Output:

Theauthor, A. B. 1985. “The Title.” _The Journal_ 77 (Autumn):123–45.

**Comment by retorquere** [comment] 2017-11-22 12:10
I can do numeric seasons if that's desired. Hold on.

**Comment by retorquere** [comment] 2017-11-22 12:18
Still, that sample doesn't seem to validate against the [CSL schema](https://github.com/citation-style-language/schema/blob/v1.0.1/csl-data.json#L204), and `season` can legitimately be a string.

**Comment by blip-bloop** [comment] 2017-11-22 12:24
:robot: this is your friendly neighborhood build bot announcing [test build 4922](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.46.4922.issue-811.xpi) ("numeric seasons").

**Comment by retorquere** [comment] 2017-11-22 12:31
4922 outputs numbers for seasons rather than strings, but will still issue 

```
  issued:
    date-parts:
      - - 1985
    season: 3
```

not

```
  issued:
    year: 1985
    season: 3
```

**Comment by njbart** [comment] 2017-11-22 20:18
Hmm, I’m beginning to think we’re also dealing with a pandoc-citeproc issue here after all.

This is an example from the 2011 citeproc-js specs ([archive link](http://archive.is/dNclX)):

~~~
{  "issued" : {
      "date-parts" : [
         [ 1950 ]
      ],
      "season" : "1"
   }
}
~~~

Its (generic) CSL-YAML equivalent should be this (note that it’s slightly different from what you listed above):

~~~
issued:
  date-parts:
  - - 1950
  season: '1'
~~~

There’s also a pandoc flavour of CSL-YAML, using a different date format, for better readability:

~~~
  issued:
    - year: 1950
      season: 1
~~~

pandoc-citeproc is supposed to be able to deal with both flavours – but it seems it does not render a season element when using generic CSL-YAML, though it does so when using pandoc CSL-YAML.

This bug will of course have to be fixed in pandoc-citeproc, so I feel BBT should continue to export to generic CSL-YAML.

**Comment by retorquere** [comment] 2017-11-22 21:00
Reading that spec, I was wrong to output "spring", but `1` and `"1"` are equivalent according to that spec. Where my sample differs is indentation (but this indentation is equivalent in YAML) and that I output a number (which is equivalent according to the CSL spec): this

```
issued1:
  date-parts:
  - - 1950
  season: '1'
issued2:
    date-parts:
      - - 1985
    season: '3'
```

parses to

```
{
  "issued1": {
    "date-parts": [
      [
        1950
      ]
    ],
    "season": "1"
  },
  "issued2": {
    "date-parts": [
      [
        1985
      ]
    ],
    "season": "3"
  }
}
```

I agree that Pandoc-YAML is more readable; I'm absolutely not fond of the date-parts format, but outputting CSL-YAML is essentially free for me; the only difference between my CSL-JSON and CSL-YAML exporters is that they use a different serializer.

I find it odd though that CSL would treat the number and the number-content string as equivalent, it would have been cleaner to say "numbers are season enumerators, strings are literals", because as I read it, it would treat `"5"` very different from `"4"`. In any case, numbers are explicitly supported.

**Comment by retorquere** [comment] 2017-11-22 22:24
I've merged the numeric season into .48

**Comment by retorquere** [comment] 2017-11-23 12:21
Can we close this issue?

**Comment by scarwire** [comment] 2017-11-23 17:34
I think so. If this is valid CSL, I can take up the issue with the pandoc-citeproc people.

**Comment by retorquere** [comment] 2017-11-23 17:46
I think it is. If they show it isn't, I'll revise.

**Comment by njbart** [comment] 2017-11-23 18:17
@scarwire – Have a look at https://github.com/jgm/pandoc-citeproc/issues/309, whether that covers your concerns, too.

@retorquere – I spotted one thing though: I would have expected EDTF dates with a season element like “2017-23” to be exported as:

```
issued1:
  date-parts:
  - - 2017
  season: '3'
```

What I actually see, however, is:

```
  issued:
    date-parts:
      - - 2017
        - 23
```

**Comment by retorquere** [comment] 2017-11-23 19:56
@njbart that would be an error on my part. Can you right-click that reference and get me a debug report?

**Comment by njbart** [comment] 2017-11-23 22:09
Z9MMIDD6

**Comment by blip-bloop** [comment] 2017-11-23 22:15
:robot: this is your friendly neighborhood build bot announcing [test build 4932](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.47.4932.issue-811.xpi) ("seasonize all the things").

**Comment by retorquere** [comment] 2017-11-23 22:24
Got it.

**Comment by blip-bloop** [comment] 2017-11-23 22:29
:robot: this is your friendly neighborhood build bot announcing [test build 4933](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.47.4933.issue-811.xpi) ("more test cases for #811").

**Comment by njbart** [comment] 2017-11-24 08:57
This one’s fixed, it seems.

But (once you start looking …), there’s more:

For some “circa” dates, the `circa` makes it into the output:

`2012-11-12~`

```
  issued:
    date-parts:
      - - 2012
        - 11
        - 12
    circa: true
```

`2012~`

```
  issued:
    date-parts:
      - - 2012
    circa: true
```

For others, it doesn’t:

`2012-12~`

```
  issued:
    date-parts:
      - - 2012
      - - 12
```

`2011-11-11~/2012-12-12~`, `2011-11-11/2012-12-12~`, `2011-11-11~/2012-12-12`

```
  issued:
    date-parts:
      - - 2011
        - 11
        - 11
      - - 2012
        - 12
        - 12
```


BTW, the CSL-JSON schema itself seems flawed: it seems highly unfortunate to have a JSON/YAML object that may contain a date range, but exactly one “circa” and one “season” element only. I wonder whether we should bring this up on https://github.com/citation-style-language/schema/issues. Thoughts?

**Comment by retorquere** [comment] 2017-11-24 09:41
Can you get me samples (by way of a debug ID) of those circa-problems? They're most likely (as with the previous issue) picked up by the heuristic scanner preventing them being passed to the EDTF parser.

Agreed on it being odd that ranges can't have mixed-season/circa.

**Comment by njbart** [comment] 2017-11-24 10:41
Ok, report ID: UM4JXPAW

**Comment by blip-bloop** [comment] 2017-11-24 19:26
:robot: this is your friendly neighborhood build bot announcing [test build 4944](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.47.4944.issue-811.xpi) ("give EDTF precedence").

**Comment by njbart** [comment] 2017-11-25 08:22
Looks mostly good for CSL-YAML and CSL-JSON dates with “circa” and/or “season” elements – for the moment, I’m only aware of one remaining issue:

`2017-24~`

which is exported to

```
  issued:
    date-parts:
      - - 2017
      - - 24
    circa: true
```

But in biblatex dates exported by BBT the “circa” or “season” markers seem to be missing so far.

**Comment by retorquere** [comment] 2017-11-25 12:57
`2017-24~` should now be fixed in the CSL exporters in 4952.

How are seasons denoted in biblatex? Would it be possible for you to:

* download the [test cases](https://raw.githubusercontent.com/retorquere/zotero-better-bibtex/811/test/fixtures/export/Date%20export%20to%20Better%20CSL-JSON%20%23360%20%23811.json)
* import them
* export them using biblatex
* fix the output as desired

and get me that corrected file?

**Comment by blip-bloop** [comment] 2017-11-25 12:59
:robot: this is your friendly neighborhood build bot announcing [test build 4952](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.49.4952.issue-811.xpi) ("fixes CSL part of #811").

**Comment by blip-bloop** [comment] 2017-11-25 13:08
:robot: this is your friendly neighborhood build bot announcing [test build 4953](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.49.4953.issue-811.xpi) ("test cases").

**Comment by njbart** [comment] 2017-11-25 16:43
Corrected biblatex file: https://gist.github.com/njbart/dc4825416796e9b675c00539b719182a

Notes:

biblatex uses EDTF dates throughout, including but not limited to ranges, seasons, and circa tags (see biblatex manual).

I have assumed that you do want to parse “printemps 1985”, and map it to EDTF “1985-21”.

CSL date fields “container” and “submitted” have no biblatex counterpart, so I have ignored these.

Also, none of the biblatex date fields (in the default data model: `date`, `origdate`, `eventdate`, and `urldate`) accepts literal strings. BBT, quite sensibly maps stuff in Z’s “Date” field that can be parsed as an EDTF date to biblatex `date`, and anything else as a literal string to biblatex `year` (since `year`, unlike `date` can deal with literal strings). There is no obvious way to achieve something similar for biblatex `origdate`, `eventdate`, and `urldate`. Hence, for lack of a more sensible option, I have mapped literal strings such as “13 cent”, quite simplistically, to the matching biblatex `…date` field, though it’s clear biblatex will ignore anything in these fields that isn’t in EDTF format.

**Comment by retorquere** [comment] 2017-11-25 18:52
So you're saying that the [biblatexExtendedDateFormat](https://github.com/retorquere/zotero-better-bibtex/wiki/Configuration#use-biblatex-extended-name-format-requires-biblatex-35) should be removed?

**Comment by retorquere** [comment] 2017-11-25 19:03
So you're saying that the [biblatexExtendedDateFormat](https://github.com/retorquere/zotero-better-bibtex/wiki/Configuration#biblatexextendeddateformat) preference should be removed?

**Comment by blip-bloop** [comment] 2017-11-25 23:20
:robot: this is your friendly neighborhood build bot announcing [test build 4960](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.49.4960.issue-811.xpi) ("date fields unification").

**Comment by retorquere** [comment] 2017-11-25 23:21
4960 passes the test cases you provided but still relies on biblatexExtendedDateFormat being on.

**Comment by njbart** [comment] 2017-11-26 09:27
> biblatexExtendedDateFormat

biblatex dates have been fully EDTF Levels 0 and 1 compliant since biblatex v. 3.5, released 2016-09-10 – so I don’t see a reason *not* to export EDTF dates as a default.

Whether to keep or remove a biblatexExtendedDateFormat option (I wasn’t even aware existed) depends on whether users have been reporting difficulties with EDTF somewhere in their toolchains that can be solved by falling back to the earlier ISO8601 format.

**Comment by retorquere** [comment] 2017-11-26 09:42
In my rather limited experience, a year is a short time in latex-world. Things seem to move at glacial pace, and I'm myself inclined to leave well enough alone once I have something working for a paper.

But I wouldn't mind at least making the default "on". How about the extended name format? Also default on?

**Comment by njbart** [comment] 2017-11-26 11:10
The transition from bibtex to biblatex has been slow indeed, but for whoever is using biblatex there’s hardly an excuse for not updating to the newest version - so I’d vote in favour of a default “on” for both options.

pandoc-citeproc cannot handle either of the biblatex extensions (yet), but with BBT’s very decent support for CSL JSON and CSL YAML, there’s no need to make a detour via the biblatex format anyway.

**Comment by njbart** [comment] 2017-11-26 11:15
Correction: pandoc-citeproc does support EDTF (https://github.com/jgm/pandoc-citeproc/issues/240 [closed]), but does not handle extended names yet (https://github.com/jgm/pandoc-citeproc/issues/266 [open]).

**Comment by retorquere** [comment] 2017-11-26 11:19
Alright, so with the EDTF preference available and on by default, this is good to merge?

(note to self: remove enc_date and its dependents)

**Comment by njbart** [comment] 2017-11-26 12:02
Hmm, export to biblatex in 4960 fails silently when biblatexExtendedDateFormat is on, and an entry contains both a date in the “Date” field and also something like `issued: 2015` in the “Extra” field.

**Comment by retorquere** [comment] 2017-11-26 13:24
I'm not at home right now so I'll check that case tonight. Can you get me that sample in the interim? I'd like to add all these test cases to prevent regressions.

Wrt the extended name format: ik could enable it by default but add a warning in the docs about pandoc.

**Comment by njbart** [comment] 2017-11-26 15:13
Report ID: BSN8XRTG

**Comment by retorquere** [comment] 2017-11-26 23:08
4966 handles BSN8XRTG.

How does biblatex handle date sets (e.g. `[2007]`)? This is technically valid EDTF, but do date sets make sense for references?

**Comment by njbart** [comment] 2017-11-26 23:41
Maybe I’m just being thick here – but what’s a “date set”? I can’t find that term in either https://www.loc.gov/standards/datetime/pre-submission.html or the 2016 ISO 8601 working draft …

**Comment by njbart** [comment] 2017-11-26 23:48
4966 indeed behaves as expected wrt BSN8XRTG.

**Comment by njbart** [comment] 2017-11-26 23:53
… but it also fails when the ISBN field contains two ISBNs, e.g., “0-943396-04-2 0-85131-041-9” (something Zotero’s library catalogue translators put there quite frequently).

**Comment by retorquere** [comment] 2017-11-27 04:42
Wrt "set", see 5.3.3 in the pre-submission. I currently treat sets as not valid EDTF (directed by a preference) because I have historically supported a syntax to enter origdate using brackets.

How should duplicate isbns be output?

**Comment by njbart** [comment] 2017-11-27 07:57
“Date sets”: Ok, got it. Being an EDTF level 2 feature, this is not supported by biblatex.

ISBNs: Output the whole field unaltered, I’d suggest.

**Comment by retorquere** [comment] 2017-11-27 08:34
Ah, great, I think EDTF.js detects levels, so I can just move on to heuristic parsing when I detect level 2.

Can you get me a sample for the two-isbn reference? I'm not wholly sure yet what you mean by "the whole field"; BBT errors out on purpose when I'm generating a duplicate field that is not explicitly marked as OK for duplicates (a day that's the error in the log), so I'm generating two isbn fields apparently.

**Comment by retorquere** [comment] 2017-11-27 08:44
Oh wait, there's just two space-separated isbns in the isbn field, nothing additional in the `extra` field?

Shit you might have submitted that sample, I can't look in S3 right now, but will as soon as I'm back at a computer.

**Comment by njbart** [comment] 2017-11-27 09:16
> Oh wait, there's just two space-separated isbns in the isbn field, nothing additional in the extra field?

Right. “0-943396-04-2 0-85131-041-9” in Zotero’s “ISBN” field should be exported to `isbn = {0-943396-04-2 0-85131-041-9},`

> when I'm generating a duplicate field that is not explicitly marked as OK for duplicates

If you’re talking about CSL JSON, CSL YAML, bibtex, biblatex output: Is it *ever* OK to generate duplicate fields? (I can’t think of any situations where it would …)

Also, I trust you are aware of the citeproc-js rules on “cheater syntax” (https://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html#cheater-syntax-for-odd-fields); most importantly: when entered in “cheater syntax”, only “type” and the various dates will override an existing value in the corresponding regular Zotero field.

**Comment by retorquere** [comment] 2017-11-27 10:07
If I put `0-943396-04-2 0-85131-041-9` in the ISBN field, that's just what I get on output; no error. Can you get me the reference sample that errors out in a debug report?

I don't think my CSL exporters have the ability to generate duplicate fields as they're implemented using dicts; the bib(la)tex exporters currently use arrays for fields, so they could in principle generate duplicate fields; currently, I export every attached note as a separate note / annotation field. If duplicate fields are never OK, I could use dicts too for the bib(la)tex exporters, which would probably simplify a few corners.

I was not aware of that particular behavior; I assumed that if you put something manually in the `extra` field, you wanted that to override anything else; you're saying that dates and `type` are overrides, and all others are just fallbacks if missing?

**Comment by njbart** [comment] 2017-11-27 12:18
> If I put `0-943396-04-2 0-85131-041-9` in the ISBN field, that's just what I get on output; no error. 

Report ID: CX4D3F7H – but right now I cannot reproduce this either. 

Still, a different issue: the CSL YAML output contains the first ISBN only:

```
---
references:
- id: AuthormultipleISBNs2017
  type: book
  title: multiple ISBNs
  ISBN: 0-943396-04-2
  author:
    - literal: Author
  issued:
    date-parts:
      - - 2017
...
```

biblatex, for comparison:

```
@book{AuthormultipleISBNs2017,
  title = {Multiple {{ISBNs}}},
  isbn = {0-943396-04-2 0-85131-041-9},
  author = {{Author}},
  date = {2017}
}
```

>  If duplicate fields are never OK

I tend to think they aren’t indeed – bib(la)tex doesn’t combine them, so the later ones always overwrite the earlier ones. So it would seem best to assemble attached notes into one single note / annotation field.

> you're saying that dates and type are overrides, and all others are just fallbacks if missing?

Yes, that’s what I (or rather, the citeproc-js docs) are saying.

Also note that names of creators that do not have a regular field in a given type (e.g., editor in the Report type) may be entered using the cheater syntax, and these are cumulative, e.g.,

```
editor: Thompson || Hunter S.
editor: King || Martin Luther
```

**Comment by blip-bloop** [comment] 2017-11-27 12:21
:robot: this is your friendly neighborhood build bot announcing [test build 4969](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.49.4969.issue-811.xpi) ("biblatex supports EDTF up to level 1").

**Comment by blip-bloop** [comment] 2017-11-27 12:33
:robot: this is your friendly neighborhood build bot announcing [test build 4971](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.49.4971.issue-811.xpi) ("Merge branch 'master' into 811").

**Comment by blip-bloop** [comment] 2017-11-27 13:06
:robot: this is your friendly neighborhood build bot announcing [test build 4974](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.49.4974.issue-811.xpi) ("override ISBN handling").

**Comment by retorquere** [comment] 2017-11-27 13:06
Creator types in the `extra` field are already cumulated, so that should be taken care of. ISBN has been added in 4974; in general, the CSL exporters use Zotero's CSL creator but then fixes the results where necessary.

I'll take a look at changing the field handling to use a dict. What's the difference between `annotation` and `note` in biblatex?

In bibtex, I have an option to export the URL as a `note` field, but also the `extra` field would go in a `note`. I'd have to skip the export of the `extra` if the user selected "URL in `note`".

**Comment by blip-bloop** [comment] 2017-11-27 15:09
:robot: this is your friendly neighborhood build bot announcing [test build 4978](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.49.4978.issue-811.xpi) ("more prep work").

**Comment by njbart** [comment] 2017-11-27 16:50
> What's the difference between annotation and note in biblatex?

From the biblatex manual:

> __note__ – Miscellaneous bibliographic data which does not fit into any other field. The note field may be used to record bibliographic data in a free format. Publication facts such as “Reprint of the edition London 1831” are typical candidates for the note field.

> __annotation__ – This field may be useful when implementing a style for annotated bibliographies. It is not used by all standard bibliography styles.

So, for biblatex, Extra → note, and Note attachment(s) → annotation seems sensible.

**Comment by retorquere** [comment] 2017-11-27 17:46
But still a single one of each, yes?

**Comment by njbart** [comment] 2017-11-28 04:17
> But still a single one of each, yes?

One note, one annotation field per entry, yes.

**Comment by blip-bloop** [comment] 2017-11-28 19:42
:robot: this is your friendly neighborhood build bot announcing [test build 4992](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.49.4992.issue-811.xpi) ("Merge branch 'master' into 811").

**Comment by retorquere** [comment] 2017-11-28 19:42
4992 removes the possibility of duplicate fields.

Is that it, then?

**Comment by njbart** [comment] 2017-11-28 20:13
I’d say so, yes.

**Closed** 2017-11-28 20:37 UTC
Labels: bug, in progress
