### ISSUE TITLE
(Large) bibtex file import hangs (OSX beachball, no interaction possible)

### ISSUE THREAD

**Issue by richarddmorey** [retorquere/zotero-better-bibtex#1692] opened 2020-11-10 13:52 UTC
Report ID: I2NRN9LD-euc (However, please note that because Zotero hangs, I cannot give a report just after the bug, of course. I figured it might still be useful for you to have the info from the report before the error.)

[bibfile.bib.zip](https://github.com/retorquere/zotero-better-bibtex/files/5517655/bibfile.bib.zip)

I select "File -> Import..." and choose this file in the wizard. I expect it to import the bibtex database file into my library.

Zotero is pegged at 100% CPU utilization for hours and I get a "beachball" in OSX. I cannot interact with the log window after the hang, but here's a screenshot:

<img width="1278" alt="Screenshot 2020-11-10 at 13 40 31" src="https://user-images.githubusercontent.com/1284826/98682072-62b5a680-235b-11eb-9d6b-015672dcdefb.png">

(Sorry, I know it is horrible to post a screenshot of a text log, but I can't interact with the window).

**Comment by retorquere** [comment] 2020-11-10 14:45
I have this reproducible, and the approximate cause. On it.

**Comment by richarddmorey** [comment] 2020-11-10 16:08
thanks (I see "awaiting user feedback" but I'm not sure to what that refers - let me know if I can provide any more info)

**Comment by retorquere** [comment] 2020-11-10 20:05
That's just @label-gun -- more often than not, if I comment, it's because I need more info, and that happened often enough that I automated it, but that's not the case here, so I should have manually unlabeled it. I think I have a fix, but my testing service has been acting up today, and I've been waiting for [over 3 hours](https://travis-ci.org/github/retorquere/bibtex-parser/builds/742734401) for the build to clear. I've set up my release chain so that I can't release untested builds, so I'm afraid I'll have to wait for the last test to pass.

**Comment by blip-bloop** [comment] 2020-11-11 10:59
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.85.7372](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.85.7372.xpi) ("Merge branch 'master' into gh-1692")

Install in Zotero by downloading [test build 5.2.85.7372](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.85.7372.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by richarddmorey** [comment] 2020-11-11 14:47
Successfully imported; thanks.

**Comment by retorquere** [comment] 2020-11-11 15:38
Cool, fix is in the new release. You'll be upgraded automatically, but it's just what you have now with a formal build number slapped on.

**Closed** 2020-11-11 15:39 UTC
Labels: awaiting-user-feedback, bug
