### ISSUE TITLE
Automatic export seems slow for small library

### ISSUE THREAD

**Issue by mathiasj33** [retorquere/zotero-better-bibtex#2231] opened 2022-08-02 17:57 UTC
Support log ID: TGW838U7-euc
BBT version: 6.7.18 (latest)
Zotero: 6.0.10.
OS: Ubuntu 20.04.4 LTS

Hi!

I've noticed that the automatic export seems to be quite slow even for a very small library of about 10 items. When I make a change, BBT shows this loading message in the top right corner for about 10-15 seconds (quite a big variance here, sometimes it only takes a few seconds but sometimes also 30+):
![Screenshot from 2022-08-02 18-30-01](https://user-images.githubusercontent.com/4721214/182438745-411dfa6c-2348-43d5-85bd-2c3e67a9c5ef.png)

Once that initial stage has passed, the actual export itself is instant. If I manually go to Preferences -> Automatic Export -> Export now, my library is also updating instantly.

As far as I remember I never had this problem of having to wait for the automatic export for small libraries like the one I'm currently working with. If it helps, the library is cached as well.

**Comment by retorquere** [comment] 2022-08-05 08:41
Can you get me a new log from build 3061, after triggering an auto-export by changing an item?

**Comment by mathiasj33** [comment] 2022-08-05 10:29
Log submitted, with ID PDCP7LSA-euc.

It seems like it has already improved a lot!

**Comment by retorquere** [comment] 2022-08-05 10:42
I had hoped it would, but the logs confirm it.

**Comment by mathiasj33** [comment] 2022-08-05 16:25
Hmm, while doing further testing I unfortunately ran into the issue again earlier, where I waited for more than 30 seconds before finally manually triggering the export. Unfortunately I didn't have logging enabled at that time. I did just submit a new log where the auto-export took about 10 seconds or so again to trigger: SM6PYBZK-euc

**Comment by retorquere** [comment] 2022-08-06 18:32
[test build 6.7.19.3064](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.19.3064.xpi) will log export prep regardless of whether you have logging enabled.

**Comment by retorquere** [comment] 2022-08-07 07:14
Is it the "preparing" phase day takes long for you, or is that long time before preparing starts?

**Comment by mathiasj33** [comment] 2022-08-07 07:25
No, the "preparing" phase is very fast once it gets to it. It just takes quite long to get there, during which I can only see the loading bar I included in the image in my first post.

I just submitted another support log (I had logging disabled, but was running build 3064) where the issue happened again - it took about 90 seconds or more until it got to the preparing phase: EZJJPQDE-euc

**Comment by retorquere** [comment] 2022-08-07 14:53
I don't understand, the state in the screenshot you posted is after the "preparing" phase. So what you're saying is it that after prep is done, it takes long for the progress meter to get going? But I don't currently understand how that could be faster when you manually click export.

The auto-export sequence is:

1. an item or collection changes
2. BBT waits some time to make sure no other changes would cause overlapping exports of the same auto-export, this is set to 5 seconds by default
3. BBT shows "Preparing `<translator>`" with a progress circle
4. BBT starts exporting items and shows "`<translator>`" with a progress circle (this is what is in your screenshot)
5. BBT hides the "`<translator>`" with a progress circle when the export is done

The manual auto-export sequence is

1. You click "Export" on an auto-export
3. BBT shows "Preparing `<translator>`" with a progress circle
4. BBT starts exporting items and shows "`<translator>`" with a progress circle (this is what is in your screenshot)
5. BBT hides the "`<translator>`" with a progress circle when the export is done

So when you said "in the first sequence of events, there is an unexpected delay, and in the second sequence of events, there is not", I had assumed that the problem was in the "Preparing" showing up late, and I did find and remedy a problem there. But now I think you must mean something else.

Where in the first sequence would you say does the stall happen?

**Comment by mathiasj33** [comment] 2022-08-08 00:47
I think the step where I am experiencing issues is number 2. Usually it goes something like this:

1. I change an item in the collection
2. BBT immediately shows this message:
![image](https://user-images.githubusercontent.com/4721214/183317965-8f203137-d272-43d9-b295-36a9855a4c1c.png)
3. Nothing seems to be happening for a while
4. BBT shows this message for a few seconds and then finishes the export:
![Screenshot from 2022-08-08 01-34-36](https://user-images.githubusercontent.com/4721214/183318013-e1e2d104-c5fc-4fea-bdac-4bf6361115de.png)

It also seems like it generally gets worse the longer I keep using Zotero and is better when I've just restarted.

If I manually click on export on the other hand, I immediately see the message in the second picture and the export finishes almost instantly.

**Comment by mathiasj33** [comment] 2022-08-08 00:55
Here is a gif showing the process:
![Peek2](https://user-images.githubusercontent.com/4721214/183318876-c889d5dc-0bf6-4c87-9712-d1a1cc2c2628.gif)

In this case it took about 15 seconds to sync, but as I said I also experienced it for much longer.

Thanks again for looking into this btw!

**Comment by retorquere** [comment] 2022-08-10 13:45
I've adjusted the message displayed before prep, can you send a new log from 3079?

**Comment by mathiasj33** [comment] 2022-08-11 02:33
Here is the log: RGHN8C7M-euc

For that one, it took a very long time (>= 2 min) to sync. I also submitted a support log while it was still syncing: QIM7D74D-euc

The phase that's taking long now is "Scheduled Better BibLaTeX".

**Comment by retorquere** [comment] 2022-08-11 16:50
3087 won't fix anything but adds logging that may give me a clue to what's happening.

**Comment by mathiasj33** [comment] 2022-08-12 10:28
FGDK5783-euc

The first few changes to the bibliography were quite fast, but the last few again took about 15-20 seconds.

**Comment by retorquere** [comment] 2022-08-12 19:38
I think I have it.

**Comment by mathiasj33** [comment] 2022-08-12 23:03
Seems to work from my initial experiments! I'll let you know if I run into the issue again in the next few days during my normal workflow, but seems like it's been resolved. Thanks a lot!

**Comment by retorquere** [comment] 2022-08-13 13:36
BBT was effectively switching to on-idle mode after zotero went idle the first time. After that, all auto exports would be stuck in the scheduling phase until zotero went idle again. That also explains why I wasn't able to reproduce the problem - when I'm actively debugging, zotero doesn't go idle, and it has to go idle once to trigger the problem.

**Comment by mathiasj33** [comment] 2022-08-14 11:59
I see, that makes sense. I haven't run into the issue again all day yesterday, so I can confirm it's been fixed now. Feel free to close this issue!

**Closed** 2022-08-14 12:39 UTC
