### ISSUE TITLE
BBT (6.7.258) shows only single citation key

### ISSUE THREAD

**Issue by NailGit** [retorquere/zotero-better-bibtex#3087] opened 2024-11-28 19:14 UTC
### Debug log ID

4F4975DQ-euc/6.7.258-7

### What happened?

Hi, BBT just updated to 6.7.258 and some surprising thing appear. After launching Zotero and clicking to one paper, the all others paper have the same citation key as a first one! But really in bib file the citations keys are different.  I make sure more and more, that it is necessary to return on the version Zotero 6 or JabRef.

**Comment by maxoppelt** [comment] 2024-11-29 08:50
Related to: https://github.com/retorquere/zotero-better-bibtex/issues/3074

**Comment by retorquere** [comment] 2024-11-29 09:10
Duplicate of #3074. Follow that issue please. I may bring back the section to display the citation key, because the API to display them in the info pane isn't working. I've asked the Zotero devs about this, still waiting for a response.

**Closed by retorquere** 2024-11-29 09:10 UTC
