### ISSUE TITLE
Authors export looks like this: prefix=von useprefix=true...

### ISSUE THREAD

**Issue by HachimanSec** [retorquere/zotero-better-bibtex#2138] opened 2022-05-01 18:13 UTC
Hello, 

some exports currently appear to contain some metadata, like family=, given=, prefix=, etc. 

Anyone any idea what this could be?

I am currently finishing my thesis and this is quite worrying for me. 

Thanks alot!

Zotero version: 6.0.6
Better BibTeX version: 6.5.2

Support log ID: PEZM2LJQ-refs-euc

Example:
```
@article{vonsolmsInformationSecurityCyber2013,
  title = {From Information Security to Cyber Security},
  author = {family=Solms, given=Rossouw, prefix=von, useprefix=true and family=Niekerk, given=Johan, prefix=van, useprefix=true},
  date = {2013-10},
  journaltitle = {Computers \& Security},
  shortjournal = {Computers \& Security},
  volume = {38},
  pages = {97--102},
  issn = {01674048},
  doi = {10.1016/j.cose.2013.04.004},
  langid = {english},
  keywords = {Cyber-Security,Essential,Reviewed}
}
```

becomes:
```
prefix=von useprefix=true family=Solms, given=Rossouw and pre-
fix=van useprefix=true family=Niekerk, given=Johan. From information security to cyber security. 38:97–102. ISSN 01674048. doi: 10.1016/j.cose.2013.04.004.
```

**Comment by retorquere** [comment] 2022-05-01 20:22
You have turned in biblatex extended name format

**Comment by retorquere** [comment] 2022-05-02 14:24
Can you install build 2525, turn on debug logging, re-create that export, and send a new log? I see that you have extended name format off but BBT is acting like it is on on your system. I cannot reroduce the problem using`PEZM2LJQ-refs-euc`, so 2525 adds logging around name production.

**Comment by retorquere** [comment] 2022-05-04 10:58
I cannot reproduce this on my end, so if you want a fix for this, I'll need your help.

**Closed** 2022-05-05 12:23 UTC
Labels: bug, awaiting-user-feedback
