### ISSUE TITLE
Non-breaking spaces in Zotero notes are exported as tilde  

### ISSUE THREAD

**Issue by zhaohualu** [retorquere/zotero-better-bibtex#813] opened 2017-11-21 21:00 UTC
Report ID: TDQIFMGF
I am using Better Bib(La)Tex 5.0.46 and Zotero 5.0.27. 

I am exporting BibLatex with format Better BibLatex. And I selected Export Notes in the translator options.

Why enter is exported as tilde or I missed some settings? 

Thanks for your help in advance!

The note is 
"
Notes

 

Just testing the autoexporting

 

"

But the annotation field in the exported bib file is

annotation = {Notes
~
Just testing the autoexporting
~
~
~}

**Comment by retorquere** [comment] 2017-11-22 08:04
You have [no-break space](http://www.fileformat.info/info/unicode/char/00a0/index.htm) characters in your note. Visually these look like spaces [space](http://www.fileformat.info/info/unicode/char/0020/index.htm)s only slightly wider, but in text they behave differently in that words can't break there (hence the name); the LaTeX equivalent of that is the `~`.

**Comment by retorquere** [comment] 2017-11-22 08:09
Under the hood, your note in Zotero looks like this:

```
<p>Notes</p>
<p>&nbsp;</p>
<p>Just testing the autoexporting</p>
<p>&nbsp;</p>
<p>EN: Deep Learning</p>
<p>CNN: To read</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
```

It's the `&nbsp;`s that you see represented as `~`.

**Comment by zhaohualu** [comment] 2017-11-22 21:51
Thanks for the response! 

Then how can I use enter in the note editor?

Thanks again!

**Comment by retorquere** [comment] 2017-11-22 21:57
You do have enters in the note -- everywhere where I started a new line in my sample above, there's an enter. The problem is not lack of enter's (or newlines, as they're technically called), but the spurious non-breaking spaces that the editor inserted for you.

You can remove these by going into the source view of your editor and you will see the tags (but not the `&nbsp;` marks -- they'll be there, but as `00a0` character codes, which look like spaces). If you remove those "spaces", the problem will go away. But the *real* problem here is the note editor adding these non-breaking spaces in the first place.

**Comment by zhaohualu** [comment] 2017-11-22 22:54
Thanks for your detailed response!

**Comment by retorquere** [comment] 2017-11-23 09:50
My pleasure. 

Can we close this issue?

**Closed** 2017-11-23 21:24 UTC
Labels: awaiting feedback from user, question
