### ISSUE TITLE
Library appears empty after closing and opening Zotero window on Mac

### ISSUE THREAD

**Issue by timtroendle** [retorquere/zotero-better-bibtex#792] opened 2017-11-17 10:35 UTC
Better BibTeX (5.0.38) seems to bring my Zotero (5.0.25) library into an usable state: the library appears empty, with no entries inside. Quitting Zotero completely resolves the issue. I can easily reproduce this issue on my Mac by closing the Zotero window and reopening it. 

This does not happen with Better BibTeX disabled. During a few moments before I see the empty library there are two notifications:

* `Better BibTex: Starting the key manager... ` in the center of the window
* `Better BibTex: Assigning citation keys | "Found x references without a citation key` in a box bottom right

Any ideas what the issue here could be? I tried to send a debug log, but did not find the mentioned button in the Better BibTex pref pane.

**Comment by ltalirz** [comment] 2017-11-17 10:57
I can confirm this issue.
Perhaps another hint: When this problem occurs, there is a note from better bibtex similar to "found xx entries without citation keys" and it goes through the list of items (while, as stated above, the folders of the library inside zotero appear completely empty).

Then I close zotero and reopen it again and the problem is gone (also no re-indexing by better bibtex)

**Comment by retorquere** [comment] 2017-11-17 12:37
@timtroendle what platform are you on, and can you submit an error report?

@ltalirz I can see you're on MacOS but there's nothing in the logs that indicates an error. Can you confirm disabling BBT makes the library show again?

**Comment by timtroendle** [comment] 2017-11-17 12:41
Sure: `U2A8XYKR`. I am on macOS 10.12.6.

**Comment by ltalirz** [comment] 2017-11-17 12:48
@blip-bloop Yes, I also noticed that no errors are shown. I was hoping that the debug log would show something helpful... 
Anyhow, yes, I can confirm that the problem is gone, when disabling better bibtex.

Just to be clear about the steps to reproduce the problem:
1. open zotero
2. click on the red "x" to close the window
3. click on the zotero icon in the sidebar

When, instead, one just minimizes zotero (green _ button) or one completely quits zotero (cmd+q), the problem does not occur.

**Comment by retorquere** [comment] 2017-11-17 12:53
And disabling BBT brings it back?

Oh great, it's one of those MacOS weirdnesses where closing an app just sort of closes it. Fuck. I see it now too.

This is not going to be a quicky fix I'm afraid. I see it tries to re-start the init workflow, and init is not supposed to run twice.

**Comment by timtroendle** [comment] 2017-11-17 12:59
I tend to say this is a new issue as I'm using better bibtex for several weeks now and I am seeing this issue only since recently. But maybe I simply hadn't closed the window before...

**Comment by retorquere** [comment] 2017-11-17 13:07
That's honestly the most likely scenario because init running twice would have been a problem in BBT4 but moreso in BBT5, because the timing is so sensitive in Z5.

So maybe I shouldn't get rid of this Macbook just yet... couldn't have diagnosed this without it. It's getting a bit old though so I've bene eyeing a Linux machine... not getting another mac :roll_eyes: I can sort of understand why people are singing its praise, but if you're used to linux (sloppy focus FTW!)

**Comment by blip-bloop** [comment] 2017-11-17 13:19
:robot: this is your friendly neighborhood build bot announcing [test build 4809](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.39.4809.issue-792.xpi) ("fixes #792 ?").

**Comment by retorquere** [comment] 2017-11-17 13:21
Give 4809 a go.

**Comment by timtroendle** [comment] 2017-11-17 13:21
It looks good to me.

**Comment by retorquere** [comment] 2017-11-17 13:23
Holy crap what kind of machine are you on? I couldn't have installed & restarted that fast, and I have the XPI at hand :laughing:

**Comment by timtroendle** [comment] 2017-11-17 13:25
Haha, saw blip-bloop's announcement right away by chance. Anyhow, closing the window and reopening doesn't do any harm anymore.

**Comment by ltalirz** [comment] 2017-11-17 13:26
Same here, thanks a lot!

**Closed** 2017-11-17 14:17 UTC
Labels: bug

**Comment by retorquere** [comment] 2017-11-17 14:19
5.0.41 will drop momentarily (no blip-bloop though)

**Comment by timtroendle** [comment] 2017-11-17 16:47
Thanks a lot for the quick fix!
