### ISSUE TITLE
Export (manual) stuck at 40 percent

### ISSUE THREAD

**Issue by jrennstich** [retorquere/zotero-better-bibtex#1811] opened 2021-05-20 13:02 UTC
For the last few (beta) versions, my manual export gets stuck at 40 percent. 

Support log ID: IFZNF83B-euc

MacOS 11.3.1 (20E241)
Zotero 5.0.97-beta.27+861d5787d

**Comment by jrennstich** [comment] 2021-05-20 14:04
Sure thing:

Support Log ID: GL5ZTW4F-euc

Same problem on my end here, though. :-(

**Comment by retorquere** [comment] 2021-05-20 15:03
I see just one export, but that's an auto-export that completes. Can I get a copy of your database to see if I can replicate this?

**Comment by jrennstich** [comment] 2021-05-20 16:36
It’s huge…

**Comment by retorquere** [comment] 2021-05-20 16:37
How big? I can set up a file drop off if it's less than 100G

**Comment by jrennstich** [comment] 2021-05-20 17:20
Loading now.

**Comment by retorquere** [comment] 2021-05-21 07:02
How do you know it's stuck at 40%? I don't get progress feedback.

**Comment by jrennstich** [comment] 2021-05-21 07:06
I am probably to trusting in dialog boxes :-)

![screenshot_274](https://user-images.githubusercontent.com/22581234/119096358-c8be6d00-ba13-11eb-86de-578c3be34f4e.png)

**Comment by retorquere** [comment] 2021-05-21 07:33
Oh I thought it was a manual export?

**Comment by jrennstich** [comment] 2021-05-21 07:37
My bad/misunderstanding. I thought, when I choose "Automatic export - disabled" and thus have to trigger the exports manually that also means "manual export". I forgot that you can export manually directly as well.

**Comment by retorquere** [comment] 2021-05-21 08:28
That's alright, I realize that's ambiguous now. But then I did see that one manually-triggered auto-export in `IFZNF83B-euc`, and that finished correctly.

It is in principle possible that the cache isn't fully filled, but the export completed correctly. I'll have to think about providing some kind of feedback for large exports.

**Comment by jrennstich** [comment] 2021-05-22 11:47
Thanks for updating BBT. Alas, no change, I do see a new "Progress: " Info line, which is something you included here, I am sure. 

![screenshot_275](https://user-images.githubusercontent.com/22581234/119225447-1f0ad900-bb04-11eb-920a-118bc15304b4.png)

Here's the 

Support log ID: ZQGLNISY-euc

Thanks for all your awesome support!

**Comment by retorquere** [comment] 2021-05-22 12:02
You should be able to see the progress climb; in the main interface there's also a progress bar left of the quick search that shows while an export is running.

**Comment by jrennstich** [comment] 2021-05-22 12:08
There was no change for me, unfortunately.

**Comment by jrennstich** [comment] 2021-05-24 08:54
Oooooh, I LOVE ❤️  that new "Status" line in the dialog. Gives more information, uses less space, well-done you! Here's the result from the log:

BDIU22HX-euc

Works as advertised.

**Comment by retorquere** [comment] 2021-05-24 11:09
So you do see the progress climb now?

**Comment by retorquere** [comment] 2021-05-24 11:57
I've re-added the cache rate -- I have a method now which is faster *and* more precise.

**Comment by jrennstich** [comment] 2021-05-24 15:24
> So you do see the progress climb now?

Indeed!

**Comment by jrennstich** [comment] 2021-05-25 08:33
With the 5.4.15.934 testbuild, I don't get the loading BBT info window on the bottom right anymore. Also I get a dialog box that looks like this:

![screenshot_277](https://user-images.githubusercontent.com/22581234/119466174-a8105300-bd44-11eb-85db-ae8f7f7a0305.png)


How do I trigger an export now?

**Comment by jrennstich** [comment] 2021-05-25 08:35
Also, I cannot start the sending the BBT support log process anymore. Rebooted Zotero (beta: 5.0.97-beta.27+861d5787d) to no avail.

**Comment by retorquere** [comment] 2021-05-25 08:37
That means BBT didn't finish loading. The preferences are hidden until the load is done. Can you get me a debug log?

**Comment by retorquere** [comment] 2021-05-25 08:40
Does 901 work for you?

**Comment by jrennstich** [comment] 2021-05-25 08:46
> Does 901 work for you?

Yes and no. Everything works as advertised the FIRST time I install BBT 910. But when I reboot Zotero to enable the support log, no window, no reaction after selecting the menu (Send BBT support log)

**Comment by jrennstich** [comment] 2021-05-25 08:49
934 also seems to show status in 5 percent increments. This works only after a fresh install and the first reboot.

**Comment by retorquere** [comment] 2021-05-25 09:17
When it starts failing (preferably on 934), can you quit Zotero and then start it using

```
/Applications/Zotero.app/Contents/MacOS/zotero -purgecaches -jsconsole -ZoteroDebugText > ~/BBT.log &
```

and get me BBT.log

**Comment by retorquere** [comment] 2021-05-25 09:21
(it is correct progress reported in 5% increments)

**Comment by retorquere** [comment] 2021-05-25 09:29
I cannot reproduce the problem locally with your database yet. I can restart Zotero beta at will with your database.

**Comment by jrennstich** [comment] 2021-05-25 09:48
Do I copy each line individually from the error console? I don't seem to be able to select more than one.

**Comment by retorquere** [comment] 2021-05-25 09:48
You can skip the error console

**Comment by jrennstich** [comment] 2021-05-25 09:49
Support log: CV6CXQ99-euc

**Comment by retorquere** [comment] 2021-05-25 09:49
I thought you had a problem where you couldn't send a debug log?

**Comment by jrennstich** [comment] 2021-05-25 09:50
With that command you send me it works

**Comment by jrennstich** [comment] 2021-05-25 09:50
I ran that in the Terminal

**Comment by retorquere** [comment] 2021-05-25 09:52
Ehm... that's not supposed to make any difference. There's also way too little in the logs. What about if you run

```
/Applications/Zotero.app/Contents/MacOS/zotero -ZoteroDebugText > ~/BBT.log &
```

**Comment by jrennstich** [comment] 2021-05-25 09:53
> Ehm... that's not supposed to make any difference. There's also way too little in the logs. What about if you run
> 
> ```
> /Applications/Zotero.app/Contents/MacOS/zotero -ZoteroDebugText > ~/BBT.log &
> ```

Well, it did 😳  - booted up normally and back to square one.

**Comment by jrennstich** [comment] 2021-05-25 09:58
Sorry, I am confused. Is this a Terminal command or a link to a folder?

**Comment by jrennstich** [comment] 2021-05-25 09:58
both work. which is super odd to me.

**Comment by retorquere** [comment] 2021-05-25 09:59
Terminal command, sorry.

**Comment by jrennstich** [comment] 2021-05-25 10:01
When I ran it in Terminal, I wasn't able to get the error log again this time. How do I access the info you need?

**Comment by retorquere** [comment] 2021-05-25 10:03
The output will be in a file called `BBT.log` in your home dir.

**Comment by jrennstich** [comment] 2021-05-25 10:05
Thanks! 😳
[BBT.log](https://github.com/retorquere/zotero-better-bibtex/files/6538391/BBT.log)

**Comment by retorquere** [comment] 2021-05-25 10:09
And this was with the error reproduced? There's zero BBT activity in that log.

**Comment by jrennstich** [comment] 2021-05-25 10:12
I booted up Zotero from the Finder this time, not from the Terminal. This is the error log.

[BBT.log](https://github.com/retorquere/zotero-better-bibtex/files/6538437/BBT.log)

**Comment by retorquere** [comment] 2021-05-25 10:25
Again zero BBT activity. I'm also missing info at the start of the log, for me it starts with

```
1621938051820 addons.manager  DEBUG Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider", "XPIInternal"]
1621938051823 addons.manager  DEBUG Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1621938051844 addons.manager  DEBUG Loaded provider scope for resource://gre/modules/addons/GMPProvider.jsm
1621938051846 addons.manager  DEBUG Loaded provider scope for resource://gre/modules/addons/PluginProvider.jsm
1621938051847 addons.manager  DEBUG Starting provider: XPIProvider
1621938051847 addons.xpi  DEBUG startup
1621938051847 addons.xpi  INFO  SystemAddonInstallLocation directory is missing
1621938051848 addons.xpi  INFO  Removing all system add-on upgrades.
1621938051848 addons.xpi  DEBUG Skipping unavailable install location app-system-share
1621938051849 addons.xpi  DEBUG checkForChanges
1621938051850 addons.xpi  DEBUG Loaded add-on state: {"app-profile":{"addons":{"debug-bridge@iris-advies.com":{"enabled":true,"lastModifiedTime":1621931997719,"path":"debug-bridge@iris-advies.com","signedState":0,"version":"0.1.5","enableShims":true},"better-bibtex@iris-advies.com":{"enabled":true,"lastModifiedTime":1621931997752,"path":"better-bibtex@iris-advies.com","signedState":0,"version":"5.4.16.emile.limonia","enableShims":true},"lyz@zotero.org":{"enabled":true,"lastModifiedTime":1621931998443,"path":"lyz@zotero.org","signedState":0,"version":"4.1.2a1"}},"path":"/Users/emile/.BBTZ5TEST/extensions"},"app-global":{"addons":{"zoteroOpenOfficeIntegration@zotero.org":{"enabled":true,"lastModifiedTime":1619778875178,"path":"zoteroOpenOfficeIntegration@zotero.org","signedState":0,"version":"5.0.25.SA.5.0.96.2","enableShims":true,"currentModifiedTime":1619778875178},"zoteroMacWordIntegration@zotero.org":{"enabled":true,"lastModifiedTime":1619778875206,"path":"zoteroMacWordIntegration@zotero.org","signedState":0,"version":"5.0.36.SA.5.0.96.2","enableShims":true,"currentModifiedTime":1619778875206}},"path":"/Applications/Zotero.app/Contents/Resources/extensions","checkStartupModifications":true}}
1621938051851 addons.xpi  INFO  Mapping better-bibtex@iris-advies.com to /Users/emile/.BBTZ5TEST/extensions/better-bibtex@iris-advies.com
```

and that's missing in `BBT.log`. I also see this in the console when I start Zotero this way:

```
$ 2021-05-25 12:20:52.144 zotero[6062:101216] *** WARNING: Textured window <ToolbarWindow: 0x10ec34850> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
JavaScript warning: resource://zotero/loader.jsm -> resource://zotero/bluebird/util.js, line 205: unreachable code after return statement
JavaScript warning: resource://zotero/loader.jsm -> resource://zotero/bluebird/util.js, line 205: unreachable code after return statement
JavaScript warning: chrome://zotero/content/zoteroPane.js, line 5347: unreachable code after return statement
objc[6062]: Class ZoteroSBApplicationDelegate is implemented in both /Applications/Zotero-beta.app/Contents/Resources/extensions/zoteroMacWordIntegration@zotero.org/resource/libZoteroWordIntegration.dylib (0x11eaafb30) and /Applications/Zotero-beta.app/Contents/Resources/extensions/zoteroMacWordIntegration@zotero.org/resource/libZoteroWordIntegrationClient.dylib (0x11eacba88). One of the two will be used. Which one is undefined.
2021-05-25 12:20:56.118 zotero[6062:101216] Warning: Expected min height of view: (<NSButton: 0x156916c00>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
```

can you make sure Zotero is not running, remove `BBT.log`, then start using

```
/Applications/Zotero.app/Contents/MacOS/zotero -ZoteroDebugText > ~/BBT.log &
```

again, reproduce the error, quit zotero, and then attach the log here.

**Comment by jrennstich** [comment] 2021-05-25 11:29
Submitted through Zotero
D288127080
Debug Output
[BBT.log](https://github.com/retorquere/zotero-better-bibtex/files/6538877/BBT.log)

**Comment by retorquere** [comment] 2021-05-25 12:52
If you just want to get on with your life, grab 5.4.14, but I'd hugely appreciate it if you would be around to test.

**Comment by jrennstich** [comment] 2021-05-25 13:56
Here's the support log: H2NXZ644-euc

**Comment by jrennstich** [comment] 2021-05-25 14:02
After reboot, same problem, so here's the file:
[BBT.log](https://github.com/retorquere/zotero-better-bibtex/files/6539863/BBT.log)

**Comment by retorquere** [comment] 2021-05-25 14:09
Can you make a new log with

```
/Applications/Zotero-beta.app/Contents/MacOS/zotero -ZoteroDebugText 2>&1 > ~/BBT.log &
```

**Comment by jrennstich** [comment] 2021-05-25 14:12
that doesn't work :-(

**Comment by retorquere** [comment] 2021-05-25 14:44
Ah shit that should have been

```
/Applications/Zotero.app/Contents/MacOS/zotero -ZoteroDebugText 2>&1 > ~/BBT.log &
```

**Comment by jrennstich** [comment] 2021-05-25 14:50
[BBT.log](https://github.com/retorquere/zotero-better-bibtex/files/6540176/BBT.log)

**Comment by jrennstich** [comment] 2021-05-25 15:16
Didn't seem to work. Here's the zip'd file
[typescript.zip](https://github.com/retorquere/zotero-better-bibtex/files/6540397/typescript.zip)

**Comment by retorquere** [comment] 2021-05-25 15:41
It did work, and I think this finally gives me the info I need.

**Comment by retorquere** [comment] 2021-05-25 19:02
Can you go into the [hidden prefs](https://retorque.re/zotero-better-bibtex/installation/preferences/hidden-preferences/), look up extensions.zotero.translators.better-bibtex.citekeySearch, disable it, and restart Zotero?

**Comment by jrennstich** [comment] 2021-05-25 19:38
I have now updated MacOS to 11.4 (20F71)

**Comment by jrennstich** [comment] 2021-05-25 19:45
No change :-( Should I switch over to the other thread? Or try 960?

**Comment by retorquere** [comment] 2021-05-25 19:51
960 just adds more logging. It'll help a lot if we could switch to a single thread -- I'm flooded with reports right now and I need to focus.

**Comment by retorquere** [comment] 2021-05-26 16:08
5.4.19 should fix the problem you have and should also start faster after the first time than it used to.

**Comment by jrennstich** [comment] 2021-05-26 17:34
Not sure where to post it now, but given the other issue is closed, I'll try here. It's running quicker, yes! I also was able to submit a support log:
6UKNQA6A-euc 

Alas:
![screenshot_278](https://user-images.githubusercontent.com/22581234/119705414-00d11000-be59-11eb-9001-325b7843520f.png)

The exported BibTeX file seems complete tho, so that's the important thing to me.

Thanks for all your incredible support!

**Comment by jrennstich** [comment] 2021-05-26 17:39
Ran it again, no change in the cache. Very quick this time (given it's a hot export). 

Support log ID: 4VESU7MZ-euc

**Comment by jrennstich** [comment] 2021-05-27 05:29
After clicking "Export now" it ran twice (on its own). Now it's showing 35 percent.

Support Log ID: XJDLE29Q-euc (w/o cache)
Support Log ID: TRGAPSBJ-euc (w cache)

![screenshot_279](https://user-images.githubusercontent.com/22581234/119770683-d1ec8580-bebc-11eb-8bdf-d3e628f2917d.png)

**Comment by jrennstich** [comment] 2021-05-28 14:00
With latest beta () and reactived scite plug-in as it seems to make no difference. Back to 40 percent.

Support Log-ID: 67ZU7JC4-euc

**Comment by retorquere** [comment] 2021-05-28 17:14
I'm not seeing some things in your log that really should be there. Can you get me a new one? Sorry about all this man, I know Zotero restarts are not fun with a database as large as yours.

**Comment by jrennstich** [comment] 2021-05-28 17:27
I admire your endurance with these issues, so what's a little rebooting in comparison? Here's the 

Support Log ID: 4ECS8DCE-euc

BTW, do you need the cache when submitting? It posts faster w/o and if you do not need it, why bother?

**Comment by retorquere** [comment] 2021-05-28 20:44
In a later release I'll start zipping the logs -- they should compress very heavily. But right now, I don't need the cache, and I only need one run from a non-full cache, as I should see cache-filling happening.

Something is making changes to your library:

```
(3)(+0000003): Notifier.trigger('add', 'item', [48440], {"skipSelect":true}) added to queue M4uWJhQL 
(3)(+0000001): Notifier.trigger('add', 'item-tag', [48440-331], {"48440-331":{"libraryID":1,"tag":"digital","type":0}}) added to queue M4uWJhQL 
(3)(+0000000): Notifier.trigger('add', 'item-tag', [48440-1626], {"48440-1626":{"libraryID":1,"tag":"emotion","type":0}}) added to queue M4uWJhQL 
(3)(+0000001): Notifier.trigger('add', 'item-tag', [48440-383], {"48440-383":{"libraryID":1,"tag":"ethics","type":0}}) added to queue M4uWJhQL 
(3)(+0000000): Notifier.trigger('add', 'item-tag', [48440-823], {"48440-823":{"libraryID":1,"tag":"robotics","type":0}}) added to queue M4uWJhQL 
(3)(+0000001): Notifier.trigger('add', 'item-tag', [48440-923], {"48440-923":{"libraryID":1,"tag":"technology","type":0}}) added to queue M4uWJhQL 
(3)(+0000001): Notifier.trigger('add', 'item', [48440], {"48440":{"skipSelect":true},"skipAutoSync":true}) called [observers: 22]
    Zotero.Notifier</this.trigger<@chrome://zotero/content/xpcom/notifier.js:140:38
(3)(+0000005): Notifier.trigger('add', 'item-tag', [48440-331,48440-1626,48440-383,48440-823,48440-923], {"skipAutoSync":true,"48440-331":{"libraryID":1,"tag":"digital","type":0},"48440-1626":{"libraryID":1,"tag":"emotion","type":0},"48440-383":{"libraryID":1,"tag":"ethics","type":0},"48440-823":{"libraryID":1,"tag":"robotics","type":0},"48440-923":{"libraryID":1,"tag":"technology","type":0}}) called [observers: 4]
(3)(+0000001): Notifier.trigger('add', 'item', [48441], {"skipSelect":true}) added to queue AHD5f2GW 
(3)(+0000001): Notifier.trigger('add', 'item-tag', [48441-12264], {"48441-12264":{"libraryID":1,"tag":"categorizing","type":0}}) added to queue AHD5f2GW 
(3)(+0000000): Notifier.trigger('add', 'item-tag', [48441-275], {"48441-275":{"libraryID":1,"tag":"comparative","type":0}}) added to queue AHD5f2GW 
(3)(+0000000): Notifier.trigger('add', 'item-tag', [48441-8075], {"48441-8075":{"libraryID":1,"tag":"comparison","type":0}}) added to queue AHD5f2GW 
(3)(+0000002): Notifier.trigger('add', 'item-tag', [48441-635], {"48441-635":{"libraryID":1,"tag":"methodology","type":0}}) added to queue AHD5f2GW 
(3)(+0000000): Notifier.trigger('add', 'item-tag', [48441-7778], {"48441-7778":{"libraryID":1,"tag":"observation","type":0}}) added to queue AHD5f2GW 
(3)(+0000001): Notifier.trigger('add', 'item-tag', [48441-701], {"48441-701":{"libraryID":1,"tag":"observational","type":0}}) added to queue AHD5f2GW 
(3)(+0000000): Notifier.trigger('add', 'item-tag', [48441-794], {"48441-794":{"libraryID":1,"tag":"qualitative","type":0}}) added to queue AHD5f2GW 
(3)(+0000000): Notifier.trigger('add', 'item-tag', [48441-795], {"48441-795":{"libraryID":1,"tag":"quantitative","type":0}}) added to queue AHD5f2GW 
(3)(+0000000): Notifier.trigger('add', 'item', [48441], {"48441":{"skipSelect":true},"skipAutoSync":true}) called [observers: 22]
    Zotero.Notifier</this.trigger<@chrome://zotero/content/xpcom/notifier.js:140:38
(3)(+0000006): Notifier.trigger('add', 'item-tag', [48441-12264,48441-275,48441-8075,48441-635,48441-7778,48441-701,48441-794,48441-795], {"skipAutoSync":true,"48441-12264":{"libraryID":1,"tag":"categorizing","type":0},"48441-275":{"libraryID":1,"tag":"comparative","type":0},"48441-8075":{"libraryID":1,"tag":"comparison","type":0},"48441-635":{"libraryID":1,"tag":"methodology","type":0},"48441-7778":{"libraryID":1,"tag":"observation","type":0},"48441-701":{"libraryID":1,"tag":"observational","type":0},"48441-794":{"libraryID":1,"tag":"qualitative","type":0},"48441-795":{"libraryID":1,"tag":"quantitative","type":0}}) called [observers: 4]
(3)(+0000001): Notifier.trigger('add', 'item', [48442], {"skipSelect":true}) added to queue AKOYFWPr 
(3)(+0000003): Notifier.trigger('modify', 'item', [48440], {}) added to queue AKOYFWPr 
(3)(+0000001): Notifier.trigger('add', 'item', [48442], {"48442":{"skipSelect":true},"skipAutoSync":true}) called [observers: 22]
    Zotero.Notifier</this.trigger<@chrome://zotero/content/xpcom/notifier.js:140:38
(3)(+0000001): Notifier.trigger('modify', 'item', [48440], {"48440":{},"skipAutoSync":true}) called [observers: 22]
(3)(+0000001): Notifier.trigger('add', 'item', [48443], {"skipSelect":true}) added to queue aIVZBJRN 
(3)(+0000001): Notifier.trigger('modify', 'item', [48441], {}) added to queue aIVZBJRN 
(3)(+0000001): Notifier.trigger('add', 'item', [48443], {"48443":{"skipSelect":true},"skipAutoSync":true}) called [observers: 22]
    Zotero.Notifier</this.trigger<@chrome://zotero/content/xpcom/notifier.js:140:38
(3)(+0000001): Notifier.trigger('modify', 'item', [48441], {"48441":{},"skipAutoSync":true}) called [observers: 22]
```

and that's triggering repeated auto-exports of your main library. I don't yet know how that would affect cache filling though, but it is something that stands out.

**Comment by retorquere** [comment] 2021-05-28 20:49
Never mind, that's not export being kicked off. You have auto-export off, and what I thought were auto-exports was just the resetting of the progress to 0%.

**Comment by retorquere** [comment] 2021-05-28 20:53
So, actually the opposite is true. I so no export being started in `4ECS8DCE-euc`, so I wouldn't expect to see cache activity.

**Comment by jrennstich** [comment] 2021-05-31 08:08
Is this new UI item related to the cache?
![screenshot_280](https://user-images.githubusercontent.com/22581234/120161886-1b5c0e00-c1f8-11eb-9530-c8524654b6bd.png)

**Comment by retorquere** [comment] 2021-05-31 08:13
Loosely -- it shows the progress of the running export, but it should disappear when the export is done. Apparently it doesn't for everyone, I'm addressing that in #1831, but it looks like this also affects you.

**Comment by jrennstich** [comment] 2021-05-31 08:13
No change, except for the blue progress bar, that indicates "done" now, even with a cache of 40%.
Support log ID: YAKPUV8Q-euc
![screenshot_281](https://user-images.githubusercontent.com/22581234/120162514-c1a81380-c1f8-11eb-956e-dfe1e2e6fc5d.png)

**Comment by jrennstich** [comment] 2021-05-31 08:44
No change, it seems, but the progress bar works as it should.

Support log ID: EA32LJMC-euc

**Comment by jrennstich** [comment] 2021-05-31 10:19
Shows 100 percent chache. In super duper mega speed time. Not sure what happened there.

Support Log ID: JSWIMRLM-euc

![screenshot_282](https://user-images.githubusercontent.com/22581234/120179120-7b5bb000-c20a-11eb-8816-edf1b3fd9f5b.png)

**Comment by jrennstich** [comment] 2021-05-31 10:30
Ran it again, same thing happened. It shows "105%" in the Status line for a short time, then it reverts back to 100%.

**Comment by retorquere** [comment] 2021-05-31 10:59
Can you install 1004, drop the cache, and try again?

**Comment by jrennstich** [comment] 2021-05-31 11:29
how do I drop the cache?

**Comment by retorquere** [comment] 2021-05-31 11:32
BBT prefs, advanced.

**Comment by jrennstich** [comment] 2021-05-31 11:47
Some weird behavior. First it wouldn't go beyond preparing 100% (also in the progress bar). Then I clicked Export now again. Same. Then again. This brought up Status 100%, Cache 100%. Clicked again, that showed the 105%. Now it's showing "done". Here's the log

SE3W8ZMN-euc

**Comment by retorquere** [comment] 2021-05-31 12:14
To debug the cache fill I need debug logging to be on from the start, so when installing a new version, you should *not* click "restart now" in the addons window, but "restart with logging enabled" from the help menu.

**Comment by retorquere** [comment] 2021-05-31 12:14
the 105% is really strange. I cap output to 100.

**Comment by jrennstich** [comment] 2021-05-31 12:14
ah, will try again, after this lecture

**Comment by jrennstich** [comment] 2021-05-31 12:15
i meant the lecture I am giving right now :-)

**Comment by retorquere** [comment] 2021-05-31 12:19
Understood -- I had no plans to lecture you about your test participation :D.

**Comment by jrennstich** [comment] 2021-05-31 13:23
> To debug the cache fill I need debug logging to be on from the start, so when installing a new version, you should _not_ click "restart now" in the addons window, but "restart with logging enabled" from the help menu. You couldn't have know that, sorry.

That's what I tried with the first debug log. The problem is, it doesn't seem to have an effect when I click on 
BBT > Advanced > Export > Reset cache
in the sense that it still shows 100 percent. When I do run the export again, its shows status "preparation 100%" for a rather long time (I assume that means it's creating the cache?), then goes on to export. That's at least what it seems to be doing:

Log ID (w cache): WW2S2KVQ-euc

**Comment by retorquere** [comment] 2021-05-31 13:57
> That's what I tried with the first debug log. The problem is, it doesn't seem to have an effect when I click on
> BBT > Advanced > Export > Reset cache

That does actually drop the cache but didn't update the UI. A fix for that is rolling in.

> When I do run the export again, its shows status "preparation 100%" for a rather long time (I assume that means it's creating the cache?),

Sort of, but even with 1004, the cache rate in the UI should have dropped to zero and climbed from there.

What's happening in the prep phase is that I'm asking Zotero for ready-to-be-exported items (aka serialized items) which I can then pass on to the background exporter. The results of this phase are cached too, so subsequent preps should be faster.

> That's what I tried with the first debug log. 

Are you sure you restarted through help => debug output => restart with logging enabled? I have a user on #1831 where the logs similarly indicate Zotero wasn't restarted this way before generating the log, but if this is what both of you have in the logs, maybe my logs are just wrong.

**Comment by jrennstich** [comment] 2021-06-01 06:53
>  Are you sure you restarted through help => debug output => restart with logging enabled? 
Ah...no. I restarted through Help > Send Better BibTeX support log. Sorry!
BBT support log ID: ADGJT2IP-euc
Debug ID: D1649312891 

Hope I did it right this time. Sorry!

**Comment by retorquere** [comment] 2021-06-01 07:20
Yep, that's the information I need. I have no access to the `D<number>` reports though.

Although restarting through Help > Send Better BibTeX support log should have yielded the same scenario. I'll look into that separately later.

**Comment by retorquere** [comment] 2021-06-01 18:46
With a library your size, it looks like I can choose between the cache fill rate being inaccurate, or intolerably slow (and very noticeable too). I'm thinking of making this something that could be shown on demand, or in debug mode, but not attempt to keep it updated live.

**Comment by jrennstich** [comment] 2021-06-01 18:53
> With a library your size, it looks like I can choose between the cache fill rate being inaccurate, or intolerably slow (and very noticeable too). I'm thinking of making this something that could be shown on demand, or in debug mode, but not attempt to keep it updated live.

Makes sense to me. Seems like a good compromise.

**Comment by jrennstich** [comment] 2021-06-02 12:17
Support Log ID: SR5X9N95-euc

**Comment by retorquere** [comment] 2021-06-02 12:21
How is 1018 behaving for you?

**Comment by retorquere** [comment] 2021-06-02 12:22
Barring bugs, I planned to make this the release.

**Comment by jrennstich** [comment] 2021-06-02 13:46
It's relatively fast, it exports the file properly as far as I can tell. When I click on "Cached:" it always shows me either 69% or 70%

**Comment by retorquere** [comment] 2021-06-02 13:50
Can you drop the cache, do a new export, click on "Cached:" and then send a log? I consistently get to 100%, but if you (or a plugin) is touching items, that will decache them.

**Comment by retorquere** [comment] 2021-06-02 13:54
Hold a bit, a new build is incoming with more logging

**Comment by retorquere** [comment] 2021-06-02 14:21
Can you install 1021, drop the cache, do a new export, click on "Cached:" and then send a log? I consistently get to 100%, but if you (or a plugin) is touching items, that will decache them.

**Comment by jrennstich** [comment] 2021-06-02 14:47
Preparation was much slower as compared to the other version (I assume, that has to do with the cache). The actual export (the second time the progress bar runs) was very fast. Still shows 70%
Support log ID: T5GIL9XP-euc
![screenshot_283](https://user-images.githubusercontent.com/22581234/120501827-367a7980-c3c2-11eb-9df9-a671ead8b731.png)

**Comment by retorquere** [comment] 2021-06-02 15:11
On the next build (should be here in 10 min or so), could you click `Cached:` before the export starts *and* after it is `done`.

**Comment by jrennstich** [comment] 2021-06-02 15:28
I did NOT delete the cache this time, correct? (Hope so, otherwise just let me know please).
First click, after install, 50%. Second click, after Export: 70%
Log ID: MA2ZGZZG-euc

**Comment by retorquere** [comment] 2021-06-02 15:28
Prep speed does have to do with caching.

Background:

Zotero exporters do not deal with the items in your database directly, but with a "serialized" (simple JSON) object. That is true for all translators, whether BBT or Zotero's own. So export really consists of two steps;

1. Zotero serializes the items to export, and 
2. hands them to the export translator, which then does its work.

BBT's step 2. is relatively slow, so whenever bib(la)tex output for an item is generated, I cache that output for that item for its settings. So when BBT sees "item 2653 must be exported" and it's in the cache, it just spits out that text, and moves on to the next. This is also why a change to any of BBTs preferences drops all export caches, because the settings might influence how the item should be written now.

Background exports happen in a different thread, and the data needs to go from the main thread to the exporter thread. That data can only be simple JSON objects, and I can't access the database from the thread, so what the prep does is slurp everything in a (vast, in your case) JSON object, sends that to the thread, and lets the thread do all the work from there. During export, the Zotero UI freezes, and there's currently nothing I can do about that. This is true for all translators, but because BBTs use cases include larger exports, this is incredibly annoying. Hence the background exports. Once the data is handed over, the UI is free again. Prep is everything that needs to happen on the main thread, before handoff.

The thing is that the serialization of objects is *really* slow. So in addition to the export caches, I also have a serialization cache, so items to be exported that haven't changed since the last time are fetched from the cache. This is what causes the differences in the prep speed. This cache is only dropped on an upgrade of Zotero itself (but as you're on a beta, that means every time you get a new beta version).

Individual items get removed from the export and serialization cache when the corresponding Zotero item changes.

There's quite a few moving parts to all of this. A lot will simplify if Zotero moves to an architecture where exports don't freeze the UI (meaning, when they go async), but that's unlikely to happen until the electron port I would venture to guess.

**Comment by jrennstich** [comment] 2021-06-02 15:30
Thanks for the eplxanation!

**Comment by jrennstich** [comment] 2021-06-02 15:30
I hit the wrong button, sorry.

**Comment by retorquere** [comment] 2021-06-02 15:33
label-gun is on guard :)

BBT is deeming some of your items non-cacheable. I have to find out why.

**Comment by retorquere** [comment] 2021-06-02 16:57
Same procedure as last svp

**Comment by jrennstich** [comment] 2021-06-02 17:31
Here we go:
First click: Cached: 0%, Export, second click: Cached: (drumroll....) 70%
Log ID: 4DUC7IMN-euc

**Comment by retorquere** [comment] 2021-06-02 21:49
no need to clear the cache now BTW, as long as its < 100% the test should be conclusive. But the higher version number will drop the cache.

**Comment by retorquere** [comment] 2021-06-02 21:49
Never would have found this one if you hadn't stuck this one out.

**Comment by jrennstich** [comment] 2021-06-03 10:10
I admire your sleuthiness. Yes, that'a word now. 

Installed 1025. Restarted. Cliched on Cached, which showed 50%. So, I deleted it (and checked, now it says 0%). Then exported. Then clicked Chached again: NOW IT SHOWS 100%
Log ID: MCMCLHQ4-euc

**Comment by retorquere** [comment] 2021-06-03 10:20
Awesome. That confirms what I thought.

**Closed by retorquere** 2021-06-03 10:20 UTC
Labels: bug

**Comment by jrennstich** [comment] 2021-06-03 10:23
I love me some successful hypothesis testing as an empirical academic :-)

**Comment by retorquere** [comment] 2021-06-03 10:55
amen to that.
