### ISSUE TITLE
Better BibTeX: Initializing never finishes;

### ISSUE THREAD

**Issue by bdegit** [retorquere/zotero-better-bibtex#1623] opened 2020-08-18 21:18 UTC
*Please verify **all** of the below before submitting*:

1. you have picked the right category for the issue in the previous screen.
2. You are on the latest release of Zotero
3. in the Zotero addons screen you can see that you have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest)
4. you are posting a single bug or feature request.
5. the issue has a subject that succinctly describes the problem or question.
6. you are available for follow-up questions and testing.
7. you have included an error-report ID here generated by restarting Zotero with debugging enabled (Help -> Debug Output Logging -> Restart with logging enabled), reproducing your problem, and selecting "Report Better BibTeX error" from the help menu.

**I AM NOT KIDDING ABOUT THIS. *PLEASE* INCLUDE A DEBUG LOG. I WILL END UP ASKING FOR IT ANYWAY**

Picking the right issue category is really important. Each category (`Export`, `General error`, `Import`, `Key generation`, `Question`) has different instructions for gathering the data necessary required to resolve the issue you are experiencing

The error-report is important; it gives me your current BBT settings and a log of what Zotero was doing at the time of error. Without it, I'm effectively blind.

**Report ID:** FGHMVUPD-euc

**Expected behavior:** Zotero should open up and Better BibText initializes in the bottom right and then disappears.

**Actual behavior:** Better BibTeX: Initializing keeps running and says "Waiting for Zotero database" indefinitely.

**Comment by retorquere** [comment] 2020-08-18 22:00
This is a duplicate of #1622 -- please join that discussion. For the interim, please go into Zotero's [hidden preferences](https://www.zotero.org/support/preferences/hidden_preferences), turn off `automaticScraperUpdates`, and let me know whether BBT starts up as usual.

**Comment by retorquere** [comment] 2020-08-18 22:03
Unrelated, there's a note with an embedded image that seems to disrupt your sync because the note is too large.

**Comment by bdegit** [comment] 2020-08-18 22:08
Thanks - I've just gone ahead and disabled the BibTex function b/c I don't
think I use it anyhow. So that worked fine and now Zotero launches okay and
everything seems to be working
---------------------------------------------------------------------------------------------------

Brian D. Earp, Departments of Philosophy and Psychology, Yale University

Associate Director
<http://www.thehastingscenter.org/who-we-are/service-to-bioethics/collaborations/>,
Yale-Hastings Program in Ethics & Health Policy

Research Fellow
<http://www.practicalethics.ox.ac.uk/staff/staff/research_fellows/brian_earp>,
Uehiro Centre for Practical Ethics, University of Oxford

Academia.edu page <https://oxford.academia.edu/BrianDEarp>; ResearchGate
page <https://www.researchgate.net/profile/Brian_Earp>; Twitter page
<https://twitter.com/briandavidearp>


Now available: *Love Drugs: The Chemical Future of Relationships*

US version: available from Stanford University Press
<https://www.sup.org/books/title/?id=27130> (2020)

UK version: available from Manchester University Press
<https://manchesteruniversitypress.co.uk/9781526145413/> (2020)

**Comment by retorquere** [comment] 2020-08-18 22:10
It would still have helped me to know whether turning off automaticScraperUpdates helped

**Comment by bdegit** [comment] 2020-08-18 23:50
Ah sorry about that - I didn't think I could still turn off
automaticScraperUpdates after disabling Better BibTeX - my apologies
---------------------------------------------------------------------------------------------------

Brian D. Earp, Departments of Philosophy and Psychology, Yale University

Associate Director
<http://www.thehastingscenter.org/who-we-are/service-to-bioethics/collaborations/>,
Yale-Hastings Program in Ethics & Health Policy

Research Fellow
<http://www.practicalethics.ox.ac.uk/staff/staff/research_fellows/brian_earp>,
Uehiro Centre for Practical Ethics, University of Oxford

Academia.edu page <https://oxford.academia.edu/BrianDEarp>; ResearchGate
page <https://www.researchgate.net/profile/Brian_Earp>; Twitter page
<https://twitter.com/briandavidearp>


Now available: *Love Drugs: The Chemical Future of Relationships*

US version: available from Stanford University Press
<https://www.sup.org/books/title/?id=27130> (2020)

UK version: available from Manchester University Press
<https://manchesteruniversitypress.co.uk/9781526145413/> (2020)

**Comment by retorquere** [comment] 2020-08-19 00:24
That's OK -- someone else has confirmed this is the issue. I'm delving further into the actual reason this happens, but it's pretty deep into Zotero. You can turn `automaticScraperUpdates` back on.

**Closed** 2020-08-19 18:41 UTC
Labels: awaiting-user-feedback, duplicate, question

**Comment by 7Moses** [comment] 2020-08-20 19:28
@retorquere, thanks for all your guidance. "please go into Zotero's hidden preferences, turn off automaticScraperUpdates[]" ... worked for me: restored my ability to copy a biblatex citation,  ... Are you providing updates on your delving into the issue, Thanks,

**Comment by retorquere** [comment] 2020-08-20 19:53
Updates happen on #1622, you can either subscribe there or wait for a new release.
