### ISSUE TITLE
[BUG] "Better BibTeX startup failed" when zotero 7 restart

### ISSUE THREAD

**Issue by opacscdbph44** [retorquere/zotero-better-bibtex#2944] opened 2024-08-14 07:28 UTC
### Debug log ID

KDZV86UU-fio-epSj4pov4mGM

### What happened?

When I install the plugin, everything is fine. But as soon as I restart zotero, two windows pop up and then the bibtex plugin disappears!

<img width="406" alt="3f1830166c91396aced60199e20da82" src="https://github.com/user-attachments/assets/7a789ba5-4f52-42fb-9395-790c3f5b8906">

**Comment by opacscdbph44** [comment] 2024-08-14 08:05
> KDZV86UU-fio-epSj4pov4mGM

is this ok?

**Comment by opacscdbph44** [comment] 2024-08-14 09:37
Thanks!

**Comment by carllx** [comment] 2024-08-14 16:39
> Yeah that's OK. I will look at it when I have access to my computer.

Thanks

**Comment by retorquere** [comment] 2024-08-14 21:47
Can you disable the zotero reference plugin, restart, and see if that makes a difference? If not, please disable all non-zotero plugins except better bibtex, reproduce the problem (after "restart with debug logging enabled"), and send a new log.

**Comment by llity** [comment] 2024-08-15 00:23
Having the same problem
![image](https://github.com/user-attachments/assets/1be0ca83-c854-4ff5-93f6-8b39c4fb89d7)
By the way, just a quick question, the installation package for BBZ is almost 40Mb, while most plugins are only a few megabytes. Is it possible to reduce the size of the installation package? Thanks

**Comment by opacscdbph44** [comment] 2024-08-15 00:36
> Can you disable the zotero reference plugin, restart, and see if that makes a difference? If not, please disable all non-zotero plugins except better bibtex, reproduce the problem (after "restart with debug logging enabled"), and send a new log.

This is the ID of debug information when I disable all non-zotero plugins except better bibtex:
L649UIXN-apse/6.7.221-7

However, the bug did not occur when I disable all non-zotero plugins except better bibtex.


It seems like there might be a conflict with this plugin.
This is the ID of debug information when I only use (1) better bibtex and (2) Ethereal Style (https://github.com/MuiseDestiny/zotero-style):
LUTFH7SH-fio-l6NP5DT6Icgp

**Comment by opacscdbph44** [comment] 2024-08-15 06:58
This bug can be fixed with update Plugin Ethereal Style to 4.7.1.
It is also recommended to update zotero to the latest version as well!
My problem is fixed already, all friends can try this solution.

**Comment by Quantum-fog** [comment] 2024-08-15 06:59
The problem was caused by a conflict with Ethereal Style, which has been resolved in Ethereal Style version 4.7.4

**Comment by young-liuos** [comment] 2024-08-15 08:12
> The problem was caused by a conflict with Ethereal Style, which has been resolved in Ethereal Style version 4.7.4

Currently, there is only 4.7.3, no 4.7.4

**Comment by opacscdbph44** [comment] 2024-08-15 08:45
> > The problem was caused by a conflict with Ethereal Style, which has been resolved in Ethereal Style version 4.7.4
> 
> Currently, there is only 4.7.3, no 4.7.4

try this: https://gitee.com/MuiseDestiny/plugins

or maybe use "check for update" will also work
![image](https://github.com/user-attachments/assets/d81080b9-77f5-46fd-95c8-b5e7f3ec799c)

**Comment by retorquere** [comment] 2024-08-15 08:52
> By the way, just a quick question, the installation package for BBZ is almost 40Mb, while most plugins are only a few megabytes. Is it possible to reduce the size of the installation package? Thanks

The bulk of this 40 MB is the optional chinese/japanese transliteration support; it is not in memory unless you enable that.

I will think about a way to bring this in as a separate download, but it's not high priority to me.

**Comment by opacscdbph44** [comment] 2024-08-15 08:56
> > By the way, just a quick question, the installation package for BBZ is almost 40Mb, while most plugins are only a few megabytes. Is it possible to reduce the size of the installation package? Thanks
> 
> The bulk of this 40 MB is the optional chinese/japanese transliteration support; it is not in memory unless you enable that.
> 
> I will think about a way to bring this in as a separate download, but it's not high priority to me.

By the way, are these error caused by better bibtex?
![image](https://github.com/user-attachments/assets/65fe84ae-ac60-4aa7-b31d-e913211bb959)

**Comment by llity** [comment] 2024-08-15 10:28
> The bulk of this 40 MB is the optional chinese/japanese transliteration support; it is not in memory unless you enable that.
> I will think about a way to bring this in as a separate download, but it's not high priority to me.

Don't worry, this doesn't impact the software's performance. Can we optimize the styling and text levels of the software's settings page UI? Thanks

**Comment by retorquere** [comment] 2024-08-15 10:53
I'd love for that to look better. It's this way partly because it is an automated translation of the prefs UI I have in Zotero 6, and that has compromises in a lot of places, but also very much because I hate UI work so I don't spend a lot of time on it.

**Closed** 2024-08-17 09:39 UTC
Labels: awaiting-user-feedback, reopened
