### ISSUE TITLE
Find items by generated citation key

### ISSUE THREAD

**Issue by adam-ah** [retorquere/zotero-better-bibtex#1307] opened 2019-10-23 21:58 UTC
**Expected behavior:**

Search for "Everything" should find the article by its BBT generated citation key.
Extra feature: find it even if it is in \parencite{XXX} or \textcite{XXX} format.

**Actual behavior:**

In rare cases, it seems to work, but mostly (95%+) if I paste in the citation key to the search box the item is not found (even if I switch to search in "Everything").

To find my item I have to keep hacking the search term (citation key), so eventually, it finds it.
So from "reidTextTalkSocial2007" I have to add spaces manually to turn it into "reid Text Talk Social 2007" to find the item.

Is it data storage/indexing problem or is it a search problem?
Is it a BBT or a Zotero issue? 

EDIT: Debug ID LCQPQMQZ-apse

**Comment by adam-ah** [comment] 2019-10-23 22:02
Updated with debug ID LCQPQMQZ-apse

**Comment by retorquere** [comment] 2019-10-23 22:04
Duplicate of #1231 . This can not currently be implemented; because the way search is implemented in Zotero, I cannot (safely) wedge my way into the search function. When the formal field for citekeys finally comes, it will automatically be possible to search for it (from what I can tell). If you're finding articles now, it's because Zotero is finding those words in other parts of the item data, it's not looking at the citekey. Unless it's pinned, I think Zotero searches the `extra` field too.

**Comment by adam-ah** [comment] 2019-10-23 22:07
Thanks for the quick response @retorquere. Out of curiosity, how do you store the citation key currently and why doesn't Zotero search for all fields?

**Comment by retorquere** [comment] 2019-10-23 22:07
What do you mean by `find it in \parencite{XXX} or \textcite{XXX} format`? I don't usually see that in Zotero item data.

**Comment by adam-ah** [comment] 2019-10-23 22:09
> What do you mean by find it in \parencite{XXX} or \textcite{XXX} format? I don't usually see that in Zotero item data.

To clarify, I use Zotero to quick-copy it in LaTeX citation key format and paste that directly into my LaTeX documents. Sometimes it would be handy if I could reuse the same format that Zotero exported (copied to clipboard) without having to extract the key from the format.
So when I press CMD+SHIFT+C, \parencite{reidTextTalkSocial2007} will be put to copied clipboard. It would be nice if I could reuse that as a search-string.

**Comment by retorquere** [comment] 2019-10-23 22:19
> Thanks for the quick response @retorquere. Out of curiosity, how do you store the citation key currently and why doesn't Zotero search for all fields?

It lives in it's own database; while Zotero is running it lives in an in-memory DB called LokiJS, and it's persisted to disk in an SQLite database (the same kind Zotero uses). It is not safe to add custom fields to Zotero's own database; the devs actively warn against this, and when I tried nonetheless years ago, I really wedged my account to the point I had to manually delete everything through the website and re-sync (the primary reason why I have a 2nd account on the Zotero forums). The Zotero search facility creates an SQL query under the hood; the query-construction is hard to get into for extensions, but even then, my data doesn't live in SQL for technical reasons. From the Zotero POV, the citekey isn't a field at all and I do a fair bit of black magic fuckery to make it appear like it is; BBT is quite easily the most invasive of Zotero extensions, and I monkey-patch Zotero left and right to make it do what I need it to.

More fields are coming Zotero, and specifically a dedicated citekey field is coming, although I don't know exactly when, or how BBT is going to play nice with it; BBT lives under the assumption I'm free to scribble over it because it's my own data, that will change when other extensions might also rightfully claim management of the field. We'll have to see when it lands.

WRT searching `parencite` etc, that's *probably* possible because I could monkey-patch the function that feeds the search string to the query builder and strip out the `\parencite{` bits. But that's all for nought until it's actually possible to search for citekeys.

**Closed** 2019-10-27 21:02 UTC
Labels: awaiting-user-feedback, duplicate, question
