### ISSUE TITLE
CSL JSON and CSL YAML exporters: ignore `Fields to omit from export` setting

### ISSUE THREAD

**Issue by jpcirrus** [retorquere/zotero-better-bibtex#1179] opened 2019-05-05 23:27 UTC
- [x] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing
- [x] I have included the error-report ID here after selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

**Report ID:**
NNWWEVRY-apse

**Exporters used:**
`Better CSL JSON` and `Better CSL YAML`

**Configuration option:**
Export option `Fields to omit from export (comma-seperated)` has an export field added e.g., `abstract`.

**Expected behaviour:**
In this example, the `abstract` field is not included in the exported file,  as occurs for `Better BibLaTeX` and `Better BibTeX`

**Actual behaviour:**
In this example, the `abstract` field *is* included in the exported file.

**Comment by retorquere** [comment] 2019-05-06 05:43
Please also include a debug log (see the last checkbox).

**Comment by blip-bloop** [comment] 2019-05-06 09:34
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.76.3930](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.76.3930.xpi) ("awaiting test case from debug ID")

Install in Zotero by downloading [test build 5.1.76.3930](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.76.3930.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by jpcirrus** [comment] 2019-05-06 23:31
Sorry about that, wasn't sure it was a bug or a feature request. Report ID addd to first post. Will now test your test build and get back.

**Comment by jpcirrus** [comment] 2019-05-06 23:45
Thank you. I confirm that `test build 5.1.76.3930` resolves the issue.

**Comment by retorquere** [comment] 2019-05-07 05:57
Both the bug report and the feature request templates ask for a debug report - in fact I still prefer to have one because it gives me a test case to add to my test suite.

**Comment by retorquere** [comment] 2019-05-07 08:08
I've added a test case to prevent regressions; I'm closing this because it's folded into master, when #1178 passes I'll cut a new release.

**Closed by retorquere** 2019-05-07 08:08 UTC
Labels: awaiting-user-feedback, bug
