### ISSUE TITLE
Better BibTeX avoids citekeys in the Trash

### ISSUE THREAD

**Issue by jun0** [retorquere/zotero-better-bibtex#2676] opened 2023-10-13 02:36 UTC
### Debug log ID

5E9WTB2D-refs-apse/6.7.124-6

### What happened?

When I trash an item and then add the same item again (through the Firefox Zotero extension if that matters), the new item will be assigned a citekey with an "a" appended.  Better BibTeX is apparently trying to avoid citekey conflicts with items in the Trash (looks like a regression of #117).  Is it possible to have Better BibTeX assign a citekey without that disambiguating character when the only conflicts are in the Trash?

**Comment by retorquere** [comment] 2023-10-13 07:09
I cannot reproduce this; can you replicate the problem and then send a new debug log, and when you do, check the checkbox "include cache"?

**Comment by jun0** [comment] 2023-10-16 01:07
Does this work?  VFANS7M3-refs-apse/6.7.124-6

**Comment by retorquere** [comment] 2023-10-16 06:42
Yes, that has the key cache. What item in the trash is claiming the key?

**Comment by jun0** [comment] 2023-10-16 07:26
The pre-existing item claiming the key is `{ "itemID": 965, "itemKey": "TUHKR3CM", "citekey": "Griffin1989FormulaeastypeNotionControl" }`.  The newly added item that got the disambiguating "a" is `{  "itemID": 967,  "itemKey": "SKEQRFSC", "citekey": "Griffin1989FormulaeastypeNotionControla" }`.

The exact sequence of things I did:
1. Restart Zotero with debug logging enabled.
2. Right-click itemID 965 and "Move Item to Trash..."
3. Go to https://dl.acm.org/doi/10.1145/96709.96714 where the paper is hosted, and import it through Firefox Zotero extension.
4. Right-click itemID 967 and "Send Better BibTeX debug log"

NB: when I say "right-click itemID 965", I mean the item that must have been itemID 965 judging from the title and citekey that was displayed in Zotero.  I don't know how to check item IDs from the Zotero UI.

The problem reproduces reliably for me regardless of the actual content of the item.

**Comment by retorquere** [comment] 2023-10-16 10:08
Can you install 5226, start with debugging enabled in the Help menu, then send a new log?

**Comment by retorquere** [comment] 2023-10-17 06:09
With the upcoming build, during startup, BBT should either flash the message "installing debug log listener" if the memory log listener is installed, or "NOT installing debug log listener" if it is not. I need to know which of the two it is.

**Comment by jun0** [comment] 2023-10-18 02:36
Where is this message supposed to appear?  I took a screen recording (available [here](https://drive.google.com/file/d/1MWNk2S7FTFXmO4pq72AkZ3yNrFPk71sG/view?usp=share_link) if you want to see it) and examined the startup closely, but no message of that sort shows up anywhere.  The recording I posted is the startup after doing "Restart with Logging Enabled", but it's the same deal if I just start Zotero normally.

I think I have test build 6.7.128.2676.5232 installed properly; going to Tools / Add-ons and clicking on "More..." under BBT shows it's at version 6.7.128.2676.5232.

Any ideas?  I don't know enough about the security model of Zotero extensions, but if it's possible to dump the message to a file in a fixed location, I can try to post that file here.

**Comment by retorquere** [comment] 2023-10-18 07:13
The message is a popup that disappears after 8 seconds. If you restart with debugging enabled and send a new debug log afterwards it will be in the log, so that should do.

**Comment by jun0** [comment] 2023-10-19 00:27
Sorry, I forgot to mention but 6.7.128.2676.5232 is also unable to create a debug log.  Same symptoms ("Zotero out of memory") as 5226.

**Comment by retorquere** [comment] 2023-10-19 04:40
Can you install https://github.com/retorquere/zotero-debug-log/releases/tag/v2.0.16, run the same procedure, then send a debug log using "Help" => "Send debug log to file.io"?

**Comment by jun0** [comment] 2023-10-19 05:12
Sure thing.  Debug log ID: YP3Z59DT-3pEXGwRg5hFc
This was prepared by the following steps:

1. Reinstall 6.7.128.2676.5232 (since I'd been experimenting with other versions)
2. Install debug-log-2.0.16.xpi
3. Restart from Help > Debug Output Logging > Restart with Logging Enabled...
4. Immediately click Help > Send debug log to file.io

I couldn't prepare a debug log where I reproduced the original citekey conflict problem.  As soon as I create a new bibliographic entry (whether through Firefox extension or manually from the + button in Zotero), the Help > Send debug log to file.io menu disappears.  But at least I got a debug log where the "Zotero is out of memory" problem reproduced.

**Comment by retorquere** [comment] 2024-01-14 17:24
Can you reproduce this on 5612?

**Comment by retorquere** [comment] 2024-01-21 14:55
closing for inactivity

**Comment by jun0** [comment] 2024-01-24 01:44
Sorry, I was busy for the past week.  FWIW, it does still reproduce in 5612 and 5628.  The log in 5628 is: RFM6M7XP-refs-apse/6.7.143.2676.5628-6

**Comment by retorquere** [comment] 2024-01-24 10:21
Look like you were busy since October. Can you attach a copy of the 5628 xpi here (rename it to zip)? I have deleted the diagnostic code and the debug build because it looked like you had abandoned the issue.

**Comment by jun0** [comment] 2024-01-25 00:34
Oh, you were waiting for my feedback on that last October build!  I saw the November builds but thought they were the github bot picking up on unrelated activity (since they mentioned other issues).  You must have felt ignored; I'm terribly sorry.

The 5628 xpi I used could not be attached directly (too large; 37 MB for 25 MB limit).  I put it up on Google Drive if that works for you: https://drive.google.com/file/d/11tUldxVW5yHBpy-6uUL00ko2DaURL2K6/view?usp=drive_link

**Comment by retorquere** [comment] 2024-01-25 10:48
Yeah, and I don't know where we were with our debugging months ago. BBT has also changed substantially since, and I pruned the diagnosis code I had for this since I have seen no response in such a long time. I will effectively have to start from scratch. The builds you saw in the interim have folded in fixes from other branches, because I don't want to deal with wildly varying versions between debugs.

I'll see what I can set back up later tonight.

**Comment by jun0** [comment] 2024-01-25 12:47
Well, if you've lost so much context, how about we close this?  I did reopen it, but I feel bad making you pay for my dropping the ball, especially considering this isn't affecting you (or too many other people, it seems).  Judging from your efforts back in October (which I very much appreciate), it looks like this will be very tricky to debug on your end due to lack of reproduction, so maybe it's not worth the trouble.

**Comment by retorquere** [comment] 2024-01-25 15:55
Let's just start over. The item in the trash is still "itemID": 965, "itemKey": "TUHKR3CM"?

**Comment by jun0** [comment] 2024-01-26 00:34
I believe the itemID has changed, but I don't have a local copy of debug log RFM6M7XP.  Is there a way to know the itemID and itemKey without looking into a saved log?

Anyway, here's a new debug log, where the ID and key are clear:  Z6E72W97-refs-apse/6.7.144-6
In this log, the item in the trash is "itemID":1108, "itemKey":"D334VPMH" and the item that got renamed is "itemID":1109, "itemKey":"EB9XYIRF".

Steps taken:
1. Restart Zotero with debug log enabled.
2. Make a conference paper item with author named "test" and all other fields left untouched.
3. Trash that item (itemID 1108).
4. Make another conference paper item with author named "test" and all other fields left untouched.
5. Send debug log.

**Comment by jun0** [comment] 2024-01-26 00:48
I believe the item ID has changed, and I'm not sure how to get that info for an already sent debug log.

Here's a new debug log where (I think) I know the ID and key: S52RWIXK-refs-apse/6.7.146.2676.5714-6
The trashed item should be "itemID":1108, "itemKey":"L4CGNAFQ" and the renamed item should be "itemID":1109, "itemKey":"3HBIVFSS".

I got the ID and key by inspecting database.json in a local copy of the debug log, and looking for items with the citation keys that I see in the Zotero GUI.  Tell me if I should do something else to ensure that the ID & key indeed identify the items of interest (and not e.g. leftovers from previous trials).

Steps taken:
1. Install 5714; restart.
2. Make sure items made in previous trials are deleted and the trash emptied.
3. Restart again with debug logging enabled.
4. Create a conference paper item with author name "test", all other fields left untouched.
5. Trash that item.
6. Create another conference paper item with the same fields.
7. Create debug log, saving a local copy.
8. Inspect database.json in that local copy.

**Comment by jun0** [comment] 2024-01-27 05:58
Sure thing; the new log is D8SPI32I-refs-apse/6.7.147.2676.5726-6
The item in the trash changed item ID and key again: "itemID":1064,"libraryID":1,"itemKey":"G8XFG6FX"
This is on a different machine than before; still macOS.

**Comment by jun0** [comment] 2024-01-27 23:02
With 5731 the bug no longer reproduces!  Tried both creating a dummy item (a conference paper item with only author name filled in) and importing real citations.  Both seems to not avoid cite keys of items in the trash.  In fact, items in the trash no longer have cite keys AFAICT, whereas before they seemed to acquire cite keys after syncing with Zotero.org.

**Closed** 2024-01-28 09:35 UTC
Labels: bug

**Comment by retorquere** [comment] 2024-01-28 09:38
>  In fact, items in the trash no longer have cite keys AFAICT

This should never have happened, and I thought I had addressed this in #2401. Zotero has behavior I didn't expect around trashed items. I think I have it correct this time.

Thank you for verifying the problem addressed. I'll cut a new release, you will automatically be upgraded to that.
