### ISSUE TITLE
Automatic export 'When Idle' doesn't pause

### ISSUE THREAD

**Issue by glocalglocal** [retorquere/zotero-better-bibtex#2112] opened 2022-04-16 00:01 UTC
Log ID: 7NJTUZ4T-euc

Automatic export 'When Idle' behaves like 'When change'. As I edit one or several  items, BBT exports, pauses for 2-3 seconds and then exports again. This has been happening since the day I installed BBT. Exports freeze Zotero for a few moments every time and really disrupts editing Zotero entries. To make things worse, it looks like an export is triggered even when the field I am editing would not affect the Citation Key and the change should ideally be ignored.

**Comment by retorquere** [comment] 2022-04-16 22:39
This is a duplicate of #2105, can you please subscribe to that issue?

**Closed by retorquere** 2022-04-16 22:39 UTC
