### ISSUE TITLE
[Bug]: BBT does not recognize zh-CN

### ISSUE THREAD

**Issue by ZnqbuZ** [retorquere/zotero-better-bibtex#2391] opened 2023-01-25 12:11 UTC
### Debug log ID

SDZWJFW5-refs-apse

### What happened?

This is a problem of Chinese word segmentation function in cite key generation. My formula is veryshorttitle(2,2). It seems that jieba won't be applied to items with language "zh-CN", but only those with language "zh". 

For example, an item with title "法医学铁道损伤图谱", whose pinyin is "FaYiXueTieDaoSunShangTuPu", will be translated to "FayixueTiedao" when language is set to "zh", while "Fayixuetiedaosunshangtupu" when language is set to "zh-CN".

However, Zotero [recommends](https://www.zotero.org/support/kb/item_types_and_fields) storing language as two letter [ISO language codes](http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) followed by two letter [ISO country codes](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) (e.g., en-US for American English, or de-DE for German), so "zh-CN" should be the "standard" language code, instead of just "zh".

Maybe BBT should regard all languages whose code contain "zh" as Chinese.

**Comment by ZnqbuZ** [comment] 2023-01-25 12:32
By the way, it seems that jieba cannot work properly on Traditional Chinese as well. For example, an item with title "改革歷程" (this is Traditional Chinese) will be translated to "GaigeLiCheng", whose capitalization is wrong; but if I change the title to "改革历程", which is the traditional version of "改革歷程", then it will be translated to "GaigeLicheng", which is expected.

I don't think this is a bug of jieba, since I have tested the string in the [demo of jieba](https://pulipulichen.github.io/jieba-js/), and it gives correct segmentation.

**Comment by ZnqbuZ** [comment] 2023-01-25 13:10
The function also fails when title contains English word. For example, "Windows 内核安全与驱动开发" is translated to "WindowS", which is obviously wrong, but if I change the title to "Windows内核安全与驱动开发" (deleting the space after "Windows"), then BBT works fine and gives 'WindowsNeihe", which is expected.

**Comment by ZnqbuZ** [comment] 2023-01-25 16:41
> The function also fails when title contains English word. For example, "Windows 内核安全与驱动开发" is translated to "WindowS", which is obviously wrong, but if I change the title to "Windows内核安全与驱动开发" (deleting the space after "Windows"), then BBT works fine and gives 'WindowsNeihe", which is expected.
> 
> As another example, "Unreal Engine 4 蓝图完全学习教程" is translated to "UnreaEngin". while "UnrealEngine4蓝图完全学习教程" is translated to "UnrealEngine4Lantu"

This is not a bug of BBT: the demo of jieba-js converts "Windows 内核安全与驱动开发" to "window- 内核 安全 驱动 开发" ("window- Neihe Anquan Qudong Kaifa" in pinyin), but BBT could circumvent this problem by replacing all non-CJK words by spaces before sending the string to jieba, and inserting them back after processed, so that jieba won't touch those English words.

Maybe a carefully designed formula could achieve this. I'm not sure.

**Comment by retorquere** [comment] 2023-01-25 16:45
That seems like something better addressed in `jieba`?

**Comment by ZnqbuZ** [comment] 2023-01-25 16:49
Another problem: still the example "Windows 内核安全与驱动开发". The character "与" means "and" in English, which is an empty word, and hence should not be in the cite key. Actually, jieba automatically delete "与" ("Yu" in pinyin) in its demo, but the citation key still contains it.

In brief, jieba demo:
"内核安全与驱动开发" -> "内核 安全 驱动 开发" -> "Neihe Anquan Qudong Kaifa"
but BBT:
"内核安全与驱动开发" -> "Neihe Anquan _Yu_ Qudong Kaifa"

**Comment by ZnqbuZ** [comment] 2023-01-25 16:53
> That seems like something better addressed in `jieba-js`?

Indeed. I don't think they should have overlooked this situation. I'll try to investigate their documentation to see if there's a solution.

**Comment by ZnqbuZ** [comment] 2023-01-25 17:16
> :robot: this is your friendly neighborhood build bot announcing [test build 6.7.53.3694](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.53.3694.xpi) ("fixes #2391, part 1")
> 
> Install in Zotero by downloading [test build 6.7.53.3694](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.53.3694.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

Confirmed this works. Thanks a lot.

**Comment by retorquere** [comment] 2023-01-25 17:39
I'm using this jieba lib btw: https://www.npmjs.com/package/ooooevan-jieba

There are javascript jieba libs with more recent updates, but I'm restricted to pure-javascript libs, and a number of the more recent ones use a C library under the hood, which I can't use.

**Comment by retorquere** [comment] 2023-01-25 17:40
> By the way, it seems that the segmentation function cannot work properly on Traditional Chinese as well. For example, an item with title "改革歷程" (this is Traditional Chinese) will be translated to "GaigeLiCheng", whose capitalization is wrong; but if I change the title to "改革历程", which is the simplified version of "改革歷程", then it will be translated to "GaigeLicheng", which is expected.

I'm still looking into this.

**Comment by retorquere** [comment] 2023-01-25 17:42
> Another problem: still the example "Windows 内核安全与驱动开发". The character "与" means "and" in English, which is an empty word, and hence should not be in the cite key. Actually, jieba automatically delete "与" ("Yu" in pinyin) in its demo, but the citation key still contains it.
> 
> In brief, jieba demo:
> "内核安全与驱动开发" -> "内核 安全 驱动 开发" -> "Neihe Anquan Qudong Kaifa"
> but BBT:
> "内核安全与驱动开发" -> "Neihe Anquan _Yu_ Qudong Kaifa"

You can address this by adding either the Chinese character or its pinyin translation to the hidden pref `skipWords`.

**Comment by retorquere** [comment] 2023-01-25 19:14
This library also works in Zotero and has seen more recent updates, but it's a fair bit slower, so it would have to have some quantifiable quality benefits: https://www.npmjs.com/package/js-jieba

**Comment by retorquere** [comment] 2023-01-25 22:47
Interesting -- ooooevan-jieba cuts `改革歷程` to `[ '改革', '歷', '程' ]`, where js-jieba cuts to `[ '改革', '歷程' ]`. I don't know which of these is right.

js-jieba is also just very slow to start up -- once it's loaded it's actually significantly faster than ooooevan-jieba.

**Comment by ZnqbuZ** [comment] 2023-01-26 03:52
> Interesting -- ooooevan-jieba cuts `改革歷程` to `[ '改革', '歷', '程' ]`, where js-jieba cuts to `[ '改革', '歷程' ]`. I don't know which of these is right.
> 
> js-jieba is also just incredibly slow to start up -- once it's loaded it's actually significantly faster than ooooevan-jieba.

`[ '改革', '歷程' ]` is correct.

Actually, you could convert all chinese strings to simplified ones before sending them to jieba, and then convert them back. This way is more accurate and won't be very time consuming.

Some reasons:

1. jieba was developed for Simplified Chinese at first, so I think its dict only contains words in Simplified form...

2. Simplified Chinese is just to convert traditional characters to simplified ones. For example, "歷" goes to "历"; both "繞" and "遶" go to "绕". Therefore, the simplification is basically a surjection from the set of Traditional characters to the set of Simplified ones. Indeed, some Traditional characters could be converted to multiple Simplified ones, such as "乾" goes to both "乾" and "干", but it's a very rare case.

**Comment by ZnqbuZ** [comment] 2023-01-26 03:58
> This library also works in Zotero and has seen more recent updates, but it's a fair bit slower, so it would have to have some quantifiable quality benefits: https://www.npmjs.com/package/js-jieba
> 
> edit: it cuts `Unreal Engine 4 蓝图完全学习教程` to `Unreal-Engine-4-蓝-图-完全-学-习-教程` (`tw` mode) or `Unreal-Engine-4-蓝图-完全-学习-教程` (`cn` mode). But it is *slow*.

Well, in the demo of jieba-js, as long as I disable Porter Stemmer, it'll just ignore English words.

**Comment by retorquere** [comment] 2023-01-26 07:38
> you could convert all chinese strings to simplified ones before sending them to jieba

I wouldn't know how to.

> but it's a very rare case

Which is why I want to leave this to libraries created by people who actually read and write Chinese (which is not me).

> in the demo of jieba-js, 

which I can't use, because it uses a C library under the hood

> as long as I disable Porter Stemmer

I don't know what this means.

If jieba-js does the right thing, I'll use that. If another pure-javascript library does better, I'll test that.

**Comment by ZnqbuZ** [comment] 2023-01-26 08:15
> > you could convert all chinese strings to simplified ones before sending them to jieba
> 
> I wouldn't know how to.
> 
> > but it's a very rare case
> 
> Which is why I want to leave this to libraries created by people who actually read and write Chinese (which is not me).
> 
> > in the demo of jieba-js,
> 
> which I can't use, because it uses a C library under the hood
> 
> > as long as I disable Porter Stemmer
> 
> I don't know what this means.
> 
> If jieba-js does the right thing, I'll use that. If another pure-javascript library does better, I'll test that.

There is a trad->simp converter named [opencc-js](https://github.com/nk2028/opencc-js).

Porter Stemmer is a feature of the [demo of jieba-js](https://pulipulichen.github.io/jieba-js/), which can be disabled in "Configuration".

Honestly, I think it's better to send only CJK characters to jieba, namely [4E00 ~ 9FFF](https://en.wikipedia.org/wiki/CJK_Unified_Ideographs_(Unicode_block)), and it seems that [ooooevan-jieba](https://www.npmjs.com/package/ooooevan-jieba) have implemented this at least in `cutHMM`, by using regex. Have you tried cut(str, true)? It gives correct segmentation in the readme of [ooooevan-jieba](https://www.npmjs.com/package/ooooevan-jieba)

**Comment by ZnqbuZ** [comment] 2023-01-26 08:28
> > Another problem: still the example "Windows 内核安全与驱动开发". The character "与" means "and" in English, which is an empty word, and hence should not be in the cite key. Actually, jieba automatically delete "与" ("Yu" in pinyin) in its demo, but the citation key still contains it.
> > In brief, jieba demo:
> > "内核安全与驱动开发" -> "内核 安全 驱动 开发" -> "Neihe Anquan Qudong Kaifa"
> > but BBT:
> > "内核安全与驱动开发" -> "Neihe Anquan _Yu_ Qudong Kaifa"
> 
> You can address this by adding either the Chinese character or its pinyin translation to the hidden pref `skipWords`.

Shouldn't `skipWords` be automatically applied to `veryshorttitle` (I'm using it)? I've tried [test build 6.7.53.3698](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.53.3698.xpi) ("fixes https://github.com/retorquere/zotero-better-bibtex/issues/2391, part 2"), but it doesn't seem to fix anything?

**Comment by EroyalBoy** [comment] 2023-01-26 08:45
I also suffer this the same puzzle.
All citation key have changed lowercase to Capitals in first such as xiaofeng2017 to XiaoFeng2017, which makes my all notes that should be in tune with this change.

**Comment by ZnqbuZ** [comment] 2023-01-26 08:50
> I also suffer this the same puzzle. All citation key have changed lowercase to Capitals in first such as xiaofeng2017 to XiaoFeng2017, which makes my all notes that should be in tune with this change.

Do you mean that your author names are mistakenly capitalized? If you would like not to change language to "zh", you could use `author.transliterate.clean.lower`.

**Comment by retorquere** [comment] 2023-01-26 08:56
> Have you tried cut(str, true)? It gives correct segmentation in the readme of [ooooevan-jieba](https://www.npmjs.com/package/ooooevan-jieba)

I'll try that

**Comment by EroyalBoy** [comment] 2023-01-26 08:59
> 

ok ,i’ll try

**Comment by retorquere** [comment] 2023-01-26 09:02
> Porter Stemmer is a feature of the [demo of jieba-js](https://pulipulichen.github.io/jieba-js/), which can be disabled in "Configuration".

Which, again, I cannot use, because it uses a C library under the hood. We need to stop discussing the issue in terms of what this specific library can or cannot do. There are other libraries I can actually use, which we're also looking at.

> Shouldn't `skipWords` be automatically applied to `veryshorttitle` (I'm using it)? I've tried [test build 6.7.53.3698](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.53.3698.xpi) ("fixes #2391, part 2"), but it doesn't seem to fix anything?

It is applied, but you must still add `yu` or `与` to the skipWords.

> Have you tried cut(str, true)? It gives correct segmentation in the readme of [ooooevan-jieba](https://www.npmjs.com/package/ooooevan-jieba)

I have tried it, and it cuts to `[ '改革', '歷', '程' ]`

**Comment by ZnqbuZ** [comment] 2023-01-26 09:11
> > Porter Stemmer is a feature of the [demo of jieba-js](https://pulipulichen.github.io/jieba-js/), which can be disabled in "Configuration".
> 
> Which, again, I cannot use, because it uses a C library under the hood. We need to stop discussing the issue in terms of what this specific library can or cannot do. There are other libraries I can actually use, which we're also looking at.
> 
> > Shouldn't `skipWords` be automatically applied to `veryshorttitle` (I'm using it)? I've tried [test build 6.7.53.3698](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.53.3698.xpi) ("fixes #2391, part 2"), but it doesn't seem to fix anything?
> 
> It is applied, but you must still add `yu` or `与` to the skipWords.
> 
> > Have you tried cut(str, true)? It gives correct segmentation in the readme of [ooooevan-jieba](https://www.npmjs.com/package/ooooevan-jieba)
> 
> I have tried it, and it cuts to `[ '改革', '歷', '程' ]`

I see. Adding `与` to the `json` file works. Thanks.

I meant that `cut(str, true)` should cuts English words correctly, as the doc shows. At least `cutHMM` should cuts English words correctly, since [ooooevan-jieba](https://www.npmjs.com/package/ooooevan-jieba) says it uses regex to jgnore English.

**Comment by retorquere** [comment] 2023-01-26 09:23
> I see. Adding `与` to the `json` file works. Thanks.

To what json file?

> I meant that `cut(str, true)` should cuts English word correctly, as the doc shows.

But that wouldn't really be a solution if it then still cuts Chinese wrongly

**Comment by ZnqbuZ** [comment] 2023-01-26 09:34
> To what json file?

I exported preferences to a json file, edited `skipWords` there, and imported the file back, since I did not find the right place for editing it in GUI...

> But that wouldn't really be a solution if it then still cuts Chinese wrongly

Well, at least it should solve the problem of "Unreal Engine 4 ……". For the problem that jieba cuts Traditional Chinese wrongly, it's mainly a problem of jieba rather than BBT, but still BBT can do something to avoid this - it's up to you:

I think one of these should be enough:
1. pre-conversion before jieba, by using maybe opencc-js as I said;
2. add a Traditional Chinese user dict to jieba - you could let users do this themselves.

**Comment by ZnqbuZ** [comment] 2023-01-26 09:37
> 🤖 this is your friendly neighborhood build bot announcing [test build 6.7.53.3703](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.53.3703.xpi) ("js-jieba cuts differently")
> 
> Install in Zotero by downloading [test build 6.7.53.3703](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.53.3703.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

Confirmed this works, for those Chinese-English mixed titles.

**Comment by retorquere** [comment] 2023-01-26 09:46
> I exported preferences to a json file, edited `skipWords` there, and imported the file back, since I did not find the right place for editing it in GUI...

Ah I see, you can edit them in the [hidden preferences](https://www.zotero.org/support/preferences/hidden_preferences).

> Did it? I mean the result it gives does not differ from the one the original method gives, so at least it did not become worse.

It was mentioned earlier that `改革歷程` should be cut to `[ '改革', '歷程' ]` (which `js-jieba` does), not `[ '改革', '歷', '程' ]` (which is what `ooooevan-jieba` does, regardless of the 2nd parameter to `cut`).

> For the problem that jieba cuts Traditional Chinese wrongly, it's mainly a problem of jieba rather than BBT, but still BBT can do something to avoid this - it's up to you:
> 
> I think one of these should be enough:
> 
>     1. pre-conversion before jieba, by using maybe opencc-js as I said;

I don't see why I should prefer this over using `js-jieba`, which apparently does the right thing by default.

>     2. add a Traditional Chinese user dict to jieba - you could let users do this themselves.

I prefer solutions that do not add new preferences to the already overwhelming set that BBT has.

**Comment by ZnqbuZ** [comment] 2023-01-26 10:05
> It was mentioned earlier that `改革歷程` should be cut to `[ '改革', '歷程' ]` (which `js-jieba` does), not `[ '改革', '歷', '程' ]` (which is what `ooooevan-jieba` does, regardless of the 2nd parameter to `cut`).

Well, certainly you could use `js-jieba`. It's better. I meant just in case you would like to stick to `ooooevan-jieba`, then the problem can be solved too.

Just note that `js-jieba` cannot cut Simplified Chinese strings correctly in `tw` mode, as this example shows:

> edit: it cuts `Unreal Engine 4 蓝图完全学习教程` to `Unreal-Engine-4-蓝-图-完全-学-习-教程` (`tw` mode) or `Unreal-Engine-4-蓝图-完全-学习-教程` (`cn` mode). But it is _slow_.

Maybe BBT should use `tw` mode only when language set to `zh-TW`.

**Comment by retorquere** [comment] 2023-01-26 10:07
I'm currently just not using `tw` mode.

**Comment by ZnqbuZ** [comment] 2023-01-26 10:13
> I'm currently just not using `tw` mode.

I think `tw` mode may be better processing `zh-TW`, for after all it provides this mode independently... but as a user I'm OK with both as long as it works well.

**Comment by retorquere** [comment] 2023-01-26 10:22
Language handling in BBT revolves around the languages supported by [babel](https://github.com/latex3/babel/tree/main/locale), I don't see anything about `tw` there. Changing language handling would be too big a change to take on right now.

**Comment by ZnqbuZ** [comment] 2023-01-26 10:30
> Language handling in BBT revolves around the languages supported by [babel](https://github.com/latex3/babel/tree/main/locale), I don't see anything about `tw` there. Changing language handling would be too big a change to take on right now.

Actually, what I meant was BBT could refer to the language field in Zotero's items.

You could use `tw` for all Traditional Chinese locales, namely `zh-Hant*`, `chinese-hant*` and `Chinese-traditional*`. There are 9 such files in the `zh` folder.

**Comment by retorquere** [comment] 2023-01-26 10:36
> Actually, what I meant was BBT could refer to the language field in Zotero's items.

I understand that, but from the myriads of values that could be in the language field, I need to bring it back to a domain of languages that I know how to deal with. I take info from the ini files in the babel repo. Adding `zh-TW` would be a special case. I might consider it, but I don't like special-case exceptions, generally.

> You could use tw for all Traditional Chinese locales, namely zh-Hant*, chinese-hant* and Chinese-traditional*. There are 9 such files in the zh folder.

I'm not even sure what `tw` means in the context of the current discussion. I'd strongly prefer it if such information could be added to the babel administration.

**Comment by ZnqbuZ** [comment] 2023-01-26 10:52
`tw` means Taiwan, an island of China whose main language Traditional Chinese. Therefore, `zh-TW` is exactly `zh-Hant` or `chinese-traditional` - just like `zh-CN` is `zh-Hans` or `chinese-simplified`, and `zh` is just abbr of `zh-CN`, since China mainland uses Simplified Chinese.

**Comment by retorquere** [comment] 2023-01-26 11:48
Babel in turn derives from https://cldr.unicode.org/, and there's nothing about `tw` there either. Locale-handling is surprisingly complicated, and if CLDR hasn't gotten to it, I'll wait it out too rather than trying my own. If babel updates, BBT automatically follows suit, as I import their config during the build.

**Comment by ZnqbuZ** [comment] 2023-01-26 11:56
> Babel in turn derives from https://cldr.unicode.org/, and there's nothing about `tw` there either. Locale-handling is surprisingly complicated, and if CLDR hasn't gotten to it, I'll wait it out too rather than trying my own. If babel updates, BBT automatically follows suit, as I import their config during the build.

If you do a search in the [cldr repo](https://github.com/unicode-org/cldr), you'll find that `zh-TW` is implicitly `zh-Hant`, such as in [this file](https://github.com/unicode-org/cldr/blob/main/tools/cldr-code/src/main/java/org/unicode/cldr/tool/LanguageCodeConverter.java)

**Comment by ZnqbuZ** [comment] 2023-01-26 13:10
Here is a table of the correspondence between codes of all Chinese variants.
| language - country/region (Zotero) | language - script (Babel) |
|------------------------------------|---------------------------|
| zh, zh-CN, zh-Hans-CN              | chinese                   |
| zh-HK, zh-Hant-HK                  | chinese-hant-hk           |
| zh-Hans-HK                         | chinese-hans-hk           |
| zh-MO, zh-Hant-MO                  | chinese-hant-mo           |
| zh-Hans-MO                         | chinese-hans-mo           |
| zh-SG, zh-Hans-SG                  | chinese-hans-sg           |
| zh-Hant-SG                         | chinese-hant-sg           |
| zh-TW, zh-hant-TW                  | chinese-hant              |

**Comment by retorquere** [comment] 2023-01-26 13:15
> If you do a search in the [cldr repo](https://github.com/unicode-org/cldr), you'll find that zh-TW is implicitly zh-Hant, such as in [this file](https://github.com/unicode-org/cldr/blob/main/tools/cldr-code/src/main/java/org/unicode/cldr/tool/LanguageCodeConverter.java).

Babel doesn't seem to follow suit though.

> I notice that BBT convert en-US to american and en-CA to candian, so why not do the same to zh-*?

Because those are the [primary name babel uses for en-CA](https://github.com/latex3/babel/blob/main/locale/en/babel-en-CA.ini#L16) and [en-US](https://github.com/latex3/babel/blob/main/locale/en/babel-en-US.ini#L16), respectively. If Babel adds an ini-file for `zh-TW`, I will absolutely do the same to zh-* -- it's automated in fact.

**Comment by ZnqbuZ** [comment] 2023-01-26 13:26
I see. Thanks for your patience. Confirmed that [test build 6.7.53.3703](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.53.3703.xpi) works well with "改革歷程", so all problems are fixed, and thus I will close this issue.

**Comment by retorquere** [comment] 2023-01-26 13:33
A new build is incoming that adds two things:

* if the language on the item is `zh-hant-TW` or `zh-TW`, it will apply `tw` mode when cut is called implicitly. I hate that this is a special case though, so I'd love it if you could submit a request to `babel`.
* The `.jieba` filter can now be called as `.jieba(cn)` (same as `.jieba`) or as `.jieba(tw)`.

**Comment by ZnqbuZ** [comment] 2023-01-26 13:54
> * if the language on the item is `zh-hant-TW` or `zh-TW`, it will apply `tw` mode when cut is called implicitly. I hate that this is a special case though, so I'd love it if you could submit a request to `babel`.

Sorry, I did not realize that babel does not support `zh-TW`, so now I think it's better to apply `tw` to and only to `zh-Hant` which means exactly `zh-Hant-TW`, and do nothing to `zh-TW` (just like `zh-HK`, `zh-MO`, etc)

**Comment by retorquere** [comment] 2023-01-26 13:57
New build incoming.

**Comment by retorquere** [comment] 2023-01-26 14:01
> There is some intricate political stuff behind the region TW, so I'm afraid babel would not change it for at least several years...

If `babel` does not want to touch it, I probably do not either.

**Comment by ZnqbuZ** [comment] 2023-01-26 14:05
> If `babel` does not want to touch it, I probably do not either.

I agree, so I think to at most apply `tw` to `zh-Hant` is enough

**Comment by retorquere** [comment] 2023-01-26 14:08
> I agree, so I think to at most apply `tw` to `zh-Hant` is enough

That sounds like something else than cutting though. Can you elaborate?

**Comment by ZnqbuZ** [comment] 2023-01-26 14:09
By the way, isn't `zh-CN` also a special case? It seems that `babel` does not use this code as well.

**Comment by ZnqbuZ** [comment] 2023-01-26 14:10
> That sounds like something else than cutting though. Can you elaborate?

I noticed that `babel` has [babel-zh-Hant.ini](https://github.com/latex3/babel/blob/main/locale/zh/babel-zh-Hant.ini), which is in fact `zh-TW`, so maybe BBT can use `tw` when an item's lang is `zh-Hant`

**Comment by ZnqbuZ** [comment] 2023-01-26 14:28
> 🤖 this is your friendly neighborhood build bot announcing [test build 6.7.53.3709](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.53.3709.xpi) ("cut tw")
> 
> Install in Zotero by downloading [test build 6.7.53.3709](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.53.3709.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

Expected `cn` to be applied to all `zh-*` except for `tw` to be applied to `zh-Hant`. Hard to tell if it really works this way, but I'm satisfied with the result it gives.

**Comment by retorquere** [comment] 2023-01-26 14:31
Oh wait you mean for the `language` field. I'll have to look into that.

**Comment by ZnqbuZ** [comment] 2023-01-26 14:44
Let me summarize current behaviour of BBT about this language stuff, so that it may help others in future:

1. when `zh`/`zh-*` is filled in `language` field, BBT regards them as `chinese` (Simplified Chinese);
2. when `zh-Hans`/`zh-Hans-HK`/`zh-Hans-MO`/`zh-Hans-SG` is filled, BBT regards them as `chinese-simplified` or `chinese-simplified-_region_`, respectively;
3. when `zh-Hant`/`zh-Hant-HK`/`zh-Hant-MO` is filled, BBT regards them as `chinese-traditional` or `chinese-traditional-_region_`, respectively;
4. when `zh-Hant` is filled, BBT uses `tw`; otherwise BBT uses `zh`.

I'm satisfied with these.

**Comment by ZnqbuZ** [comment] 2023-01-27 08:12
Great. Previously "新竹的交通大學要在2021年2月1日與台北的陽明大學合併" is cut to "新竹/的/交通/**大學要**/在/2/0/2/1/年/2/月/1/日/與/台北/的/陽明/**大學合/併**" when item's language field is set to `zh-Hans`, which is wrong. (According to the demo of js-jieba it should be cut to "新竹/的/交通/**大學/要**/在/2/0/2/1/年/2/月/1/日/與/台北/的/陽明/**大學/合併**".)  

Now changing the language to `zh-Hant` fixes this problem.

**Comment by retorquere** [comment] 2023-01-27 09:23
Can you submit the sample where you set the language to zh-Hant (right-click and send a debug log)? I want to add that to my test suite to prevent regressions.

**Comment by ZnqbuZ** [comment] 2023-01-27 09:33
I've uploaded logs of 3 items: IZSN8DRM-refs-apse, G84S5263-refs-apse, 8E4QSEHL-refs-apse
The titles of these items are string picked from the demo of js-jieba. All of them has correct segmentation only when language is set to zh-Hant

**Comment by ZnqbuZ** [comment] 2023-01-27 09:35
And I found that pinyin of "於" is wrong. Its pinyin is "Yu" but BBT gives "Wu".

**Comment by ZnqbuZ** [comment] 2023-01-27 09:46
I cannot open BBT preference by `Tools -> Better BibTeX` after installing 3712 -- just nothing happened after I pressed the button. Could you reproduce this?

**Comment by retorquere** [comment] 2023-01-27 09:50
given the citekey formula `auth.fold.lower +"_"+ veryshorttitle(2,2) +"_"+ year`, IZSN8DRM-refs-apse, G84S5263-refs-apse, 8E4QSEHL-refs-apse export to 

```
@book{_MeizhuJinbiao_,
  title = {梅竹錦標對抗賽},
  langid = {chinese-traditional}
}

@book{_XiaomingBiye_,
  title = {小明畢業於國立交通大學資訊科學與工程研究所},
  langid = {chinese-traditional}
}

@book{_XinzhuJiaotong_,
  title = {新竹的交通大學要在2021年2月1日與台北的陽明大學合併},
  langid = {chinese-traditional}
}
```

**Comment by ZnqbuZ** [comment] 2023-01-27 09:53
Wait, I thought my formula was `title.transliterate.capitalize`. If you change formula to this, you will see the difference of cite key between zh and zh-Hant.

**Comment by ZnqbuZ** [comment] 2023-01-27 10:00
I've uploaded a new log FPPGY6P5-refs-apse containing these items. Their languages are set to `zh-Hant` so segmentations are correct. If change it to `zh`, then jieba will give different (hence wrong) segmentations.

**Comment by retorquere** [comment] 2023-01-27 10:03
> Wait, I thought my formula was `title.transliterate.capitalize`. If you change formula to this, you will see the difference of cite key between zh and zh-Hant.

Then I get

```
@book{FayixueTiedaoSunshangTupu,
  title = {法医学铁道损伤图谱},
  author = {肖, 发民},
  date = {2003},
  eprint = {gzA4AAAACAAJ},
  eprinttype = {googlebooks},
  publisher = {{郑州大学出版社}},
  abstract = {本书共收集图片400余幅并附以文字说明,以铁路上常见的各种伤亡为主,内容分为:辗轧伤、撞击、拖擦伤等共9章。},
  isbn = {978-7-81048-761-0},
  langid = {chinese},
  pagetotal = {153}
}

@book{FayixueTiedaoSunshangTupua,
  title = {法医学铁道损伤图谱},
  author = {肖, 发民},
  date = {2013},
  eprint = {gzA4AAAACAAJ},
  eprinttype = {googlebooks},
  publisher = {{郑州大学出版社}},
  abstract = {本书共收集图片400余幅并附以文字说明,以铁路上常见的各种伤亡为主,内容分为:辗轧伤、撞击、拖擦伤等共9章。},
  isbn = {978-7-81048-761-0},
  langid = {chinese},
  pagetotal = {153}
}

@book{GaigeLicheng,
  title = {改革歷程},
  author = {趙, 紫陽},
  date = {2009},
  eprint = {FVaOQQAACAAJ},
  eprinttype = {googlebooks},
  publisher = {{新世紀出版社}},
  isbn = {978-988-17202-7-6},
  langid = {chinese},
  pagetotal = {370}
}

@book{MeizhuJinbiaoDuikangsai,
  title = {梅竹錦標對抗賽},
  langid = {chinese-traditional}
}

@book{XiaomingBiyeWuGuoliJiaotongDaxueZixunKexueYuGongchengYanjiusuo,
  title = {小明畢業於國立交通大學資訊科學與工程研究所},
  langid = {chinese-traditional}
}

@book{XinzhuDeJiaotongDaxueYaoZai2021Nian2Yue1RiYuTaibeiDeYangmingDaxueHebing,
  title = {新竹的交通大學要在2021年2月1日與台北的陽明大學合併},
  langid = {chinese-traditional}
}
```

**Comment by retorquere** [comment] 2023-01-27 10:05
We need to focus on one problem at a time. The conversation is getting fragmented.

**Comment by ZnqbuZ** [comment] 2023-01-27 10:07
> Then I get

These are correct segmentations, should be same with FPPGY6P5-refs-apse

**Comment by retorquere** [comment] 2023-01-27 10:10
So the remaining issues are then:

* prefs do not open
* a problem with pinyin

correct?

**Comment by ZnqbuZ** [comment] 2023-01-27 10:11
Yes

**Comment by retorquere** [comment] 2023-01-27 10:16
Let's look at the prefs window first. Please enable debug logging in the Help menu, open the prefs to replicate the problem, and then send a BBT debug from the Help menu.

**Comment by ZnqbuZ** [comment] 2023-01-27 10:21
I submitted 2 logs: 2DHAVQ4U-apse with version 6.7.50, where the window shows, and 2NFZWHBX-apse with version build 3712, where the problem occurs

**Comment by ZnqbuZ** [comment] 2023-01-27 10:29
I installed Zotero and build 3712 on a fresh new virtual machine, and the problem still occurs. The debug log was submitted as 67ZW7L7V-apse

**Comment by retorquere** [comment] 2023-01-27 10:32
I don't see any activity indicating the prefs are opened in `67ZW7L7V-apse` and `2NFZWHBX-apse`. Is that what you're seeing? The prefs window does not open at all?

**Comment by retorquere** [comment] 2023-01-27 10:35
Oh wait, forget Tools->Better BibTeX, just open the Zotero prefs. I'll remove that item under the Tools menu, that's not supposed to be there yet.

**Comment by ZnqbuZ** [comment] 2023-01-27 10:38
> Oh wait, forget Tools->Better BibTeX, just open the Zotero prefs. I'll remove that item under the Tools menu, that's not supposed to be there yet.

Ah, I see. Then the only remaining is the problem of pinyin of `於`, as you see BBT converts it to `Wu` when language is set to `zh`, which is wrong, but if I change language to anything else BBT will convert it correctly to `Yu`. Quite strange.

**Comment by ZnqbuZ** [comment] 2023-01-27 13:48
Tested 3717 and the pinyin of "於" is correct now. Thank you.

**Closed** 2023-01-27 13:54 UTC
Labels: reopened
