### ISSUE TITLE
Option to export with shortDOIs

### ISSUE THREAD

**Issue by adunning** [retorquere/zotero-better-bibtex#660] opened 2017-05-05 11:30 UTC
Might it be possible to have an option to replace DOIs with shortDOIs in the BBT export?

This would greatly simplify the appearance of bibliographies. Presumably, however, requesting them would slow down export immensely, and they would need to be cached somewhere, which I have a feeling would add too much complexity – if so, feel free to close this immediately.

This was something @njbart was also interested in a few years back for Pandoc, but I don't think anything came of it.

**Comment by njbart** [comment] 2017-05-05 14:13
I’m a big fan of shortDOIs, too.

I’m not sure I ever proposed anything for pandoc (or at least its core, as opposed to filters), since pandoc will happily process anything it finds in a biblio database’s DOI field, so the easiest way is to preprocess the biblio database.

What I actually did back then was to write a pandoc filter that replaces each DOI with a corresponding shortDOI, to be used in a Zotero → pandoc-zotxt → pandoc-citeproc workflow (written in R, available at https://github.com/njbart/pandoc-tools/blob/master/pandoc-zotxt-shortdoi.r, no cacheing whatsoever, but still tolerable speed).

It’d sure be nice to have BBT output shortDOIs – but then again this functionality could also be provided by a standalone script, even with cacheing, that would postprocess BBT’s output (whether bibtex, CSL JSON, or CSL YAML).

It’d definitely be much neater if Zotero had a dedicated shortDOI field itself, so LO/Word users could benefit, too, and if Zotero automatically looked up the shortDOI for each item with a long DOI – but when I suggested this to the Zotero folks a few years back, it got quickly shot down. 

The only workaround I see here is that BBT might be able to insert shortDOIs into the Extra field, using the “cheater syntax”. If we could convince Frank Bennett to let a cheater DOI field overwrite a regular DOI field (something citeproc-js does indeed for all dates but not for other variables), shortDOIs would be available in LO/Word, too.

**Comment by retorquere** [comment] 2017-05-05 23:44
I'm not against having it in BBT until it shows up more structurally. My main question would be what to d about cache invalidation. For performance reasons I'd probably want to cache both hits and failures to the service, but specifically failures would have "interesting" edge cases, such as DOIs that don't resolve now but will later, or network failures. Thoughts?

**Comment by adunning** [comment] 2017-05-06 09:52
Brilliant. In theory, shortDOIs themselves shouldn't change, whether or not they resolve.

**Comment by retorquere** [comment] 2017-05-06 09:59
I'm not worried about them changing, it's more that I don't know exactly when they're assigned, so I don't know if there can be the situation where it doesn't resolve today (not yet assigned) but does tomorrow. If that can happen I'd cachr the long doi as not resolvable and would never again pick up the short doi. Also, network failures, same problem.

**Comment by adunning** [comment] 2017-05-06 10:49
shortDOIs are assigned only as requested; so yes, in the case of a network/system failure, there could be a situation where one isn't available at the moment but will be in the future.

**Comment by retorquere** [comment] 2017-11-13 19:39
You mean "as requested by the author" or "as requested through the API"?

I'm of two minds how to do this. I can do this during export but that means exports could get slower as extra HTTP calls are done (even though I intend to cache the results). The other option is to resolve the short DOIs in the background and just have them available to the export, but that means potentially you could do an export which wouldn't have them, and an export just later would.

**Comment by adunning** [comment] 2017-11-14 14:18
That is a dilemma: I would personally go for the background option. Not having them done by the time of export will rarely be the absolute end of the world, whereas it's ideal to cut down the time when Zotero is unresponsible wherever possible. But there may be other considerations.

**Comment by retorquere** [comment] 2017-11-14 18:43
WRT shortDOI resolution: You mean "as requested by the author" or "as requested through the API"? IOW, are they requested by the author, or auto-generated whenever anyone requests a match? And what should I so with the "isNew" field in the returned shortDOI?

**Comment by njbart** [comment] 2017-11-14 19:58
I’d agree with @adunning, and also go for the background option. 

The "isNew" field can safely be discarded: it merely indicates whether shortdoi.org “saw” that (long) DOI for the first time (an hence had to generate a shortDOI that did not exist before) or not.

**Comment by retorquere** [comment] 2017-11-17 18:57
Hard choices: there are multiple ways of getting a DOI into a reference; one is if the Zotero reference has a proper `DOI` field, but I've just now spotted a few references in my test suite that use the CSL-var cheater syntax.

The stuff in the `extra` field is parsed out only during export. I am really loathe to change this, mainly because it would be lots of work and it would add to the BBT memory usage. Lots of work is not a smart thing to do. The PhD aside, a family member just fell seriously ill, and we'll have our hands full and then some.

So that realistically leaves two choices:

* do the background thing, but miss the cheater-syntax added DOIs. There are several Zotero reference types that don't have DOIs (such as book sections). I suppose the reference types that should realistically have DOIs mostly have the field in Zotero, but then there's e.g. 10.1007/978-3-642-11218-8_6. And I'd have to find an efficient way to do scanning because Zotero isn't super-happy when I do frequent DB access.
* do the shortDOI resolution just before the reference is sent out during the export. This would mean the doi would be picked up regardless of how it got into the reference, but it'd mean network access during the export. This is slow for shortDOIs I don't have cached and could potentially fail (networks aren't perfect), and if it does fail I'd have no choice but to abort that export rather unceremoniously (because unceremonious abort is the only way to let the user know something's amiss -- causing Zotero to show the "export has failed" popup).

I don't like any of these two options a whole lot, but such are the breaks.

**Comment by adunning** [comment] 2017-11-17 19:32
Ouch, yes, neither of those is particularly good. Might be better just to put it on ice for now and see whether Zotero proper would be willing to integrate it.

**Comment by adunning** [comment] 2017-11-17 21:24
Oh, note that DOIs will be properly integrated as a field for all item types in Zotero 5.1, so the 'cheater' syntax won't be required after that.

**Comment by retorquere** [comment] 2017-11-17 21:30
Hmm. That would put a vote in for only supporting it where the field is present.

**Comment by retorquere** [comment] 2017-11-17 21:34
Another option would be to add a right-click option to convert between long/short DOIs on the references themselves (gleaned from that 2015 thread).

**Comment by adunning** [comment] 2017-11-17 21:54
Interesting idea. The downside of that would be that Zotero couldn't then use the DOI to detect duplicates, and the address stops being active in the interface if it's not in the format of `10\.\d+/.*?` (or something like that). I can't imagine a situation where one would want to mix long and short DOIs in a single work, so best to keep it as a background operation.

I think this may as well wait until Zotero 5.1 when the main problem will be solved; there's nothing urgent about it. (Which is to say, shortDOIs really do result in a serious reduction in character counts and general ugliness, but I'm not aware of any editors right now breathing down authors' necks to demand this.)

**Comment by njbart** [comment] 2017-11-18 10:50
> I can't imagine a situation where one would want to mix long and short DOIs in a single work

I can’t either – but what about providing the option to have BBT batch change all of the DOIs in the Zotero database to shortDOIs and vice versa *at once*? (TBH, I have no idea at all what this would mean performance-wise …)

This would mean that we wouldn’t need a dedicated shortDOI field, but BBT would have to maintain a database/cache of corresponding DOIs and shortDOIs, which it would have to update in the background whenever a user enters a new DOI or shortDOI. A shortDOI or DOI that could not be resolved (yet) would at least stick out in an eyeball search (e.g., with display mode set to shortDOI, any long DOI visible in the interface would indicate a problem) – or maybe could be colour-coded somehow, as could DOIs (and shortDOIs) that fail to resolve because they are invalid.

Still, we’d have to get Zotero to fix the issue of the address not being active in the interface if it’s not in the format of a long DOI – but I guess the Zotero team could be much more easily motivated to do this than to introduce a dedicated shortDOI field.

**Comment by retorquere** [comment] 2017-11-18 11:31
It's not the performance impact I'm worried about as much that it has struck me that (by my own suggestion) BBT would be crossing a boundary that might not be appropriate - from representing Zotero data to changing Zotero data. The one place where I actually change references is by adding to the "extra" field (at the suggestion of the zotero devs).

This unwritten policy of not touching the references (to the point of maintaining a shadow database) has made it safe for me as a one-man whirlwind to go wild in what I do in BBT; if something goes horribly wrong, uninstalling BBT gets me out of trouble while I figure out a fix.

So yeah, in retrospect I'd rather not touch the DOI field. What I *could* do is either still do the background scan, or add way to easily add a shortdoi to the extra field, cheater-syntax style. Or do it during export.

**Comment by blip-bloop** [comment] 2017-11-18 12:22
:robot: this is your friendly neighborhood build bot announcing [test build 4838](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.42.4838.issue-660.xpi) ("prep for shortDOI").

**Comment by retorquere** [comment] 2017-11-19 00:33
This one is pretty blunt in that it scans missing shortDOIs at the start rather than slowly in the background. After the initial scan it should be zippy and new/changed references will be updated as needed. look for `shortDOI` in the hidden prefs; it's empty by default, you can set it to `scan` and it will look for DOI fields + cheater syntax, any other non-empty string will just look at the DOI fields.

**Comment by njbart** [comment] 2017-11-19 16:48
> test build 4874 

Looks good for biblatex. Could you add support for shortDOIs in the “Better CSL JSON” and “Better CSL YAML” export formats, too?

> BBT would be crossing a boundary that might not be appropriate - from representing Zotero data to changing Zotero data

Understandable. Personally, I wouldn’t mind at all, since I trust BBT *at least* as much as I trust Zotero itself – but if you don’t want to go that path, fine with me. From a minimalist perspective, the “4874” approach is indeed all one needs to obtain shortDOIs in one’s formatted text documents.

**Comment by adunning** [comment] 2017-11-19 16:52
Yes, second that. Strictly speaking, there's no real reason to have the shortDOI stored with the item.

**Comment by njbart** [comment] 2017-11-19 17:31
One more thing, though: *Invalid* DOIs do make it into BBT’s output unchanged. It’d be great if BBT could flag these up somehow, either by adding something like “[INVALID]” to the exported field, or possibly by adding something like “BBT warning: DOI is invalid” to Zotero’s “Extra” field, or both.

Note that `curl -sS http://shortdoi.org/10.12334/567890` returns useful information (an HTML page containing the string “`is not a valid DOI name`” – whereas `curl -sS http://shortdoi.org/10.12334/567890?format=json`, much less helpfully, returns nothing at all.

**Comment by blip-bloop** [comment] 2017-11-19 17:48
:robot: this is your friendly neighborhood build bot announcing [test build 4883](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.42.4883.issue-660.xpi) ("shortDOI for CSL").

**Comment by retorquere** [comment] 2017-11-19 17:50
CSL support is now in a 4883 near you.

> Personally, I wouldn’t mind at all, since I trust BBT *at least* as much as I trust Zotero itself

That's flattering, but for a variety of reasons, Zotero and BBT have very different development philosophies; Zotero moves slow and steady, BBT moves fast and breaks things and relies on the test suite to pick out regressions and where that fails (and it does) lives by fast turnaround on bug reports to make that acceptable. "Move fast and break things" is good for stuff that is easily reversible. Data changes are not easily reversible when screwed up, so I tend to shy away from those.

> Note that curl -sS http://shortdoi.org/10.12334/567890 returns useful information (an HTML page containing the string “is not a valid DOI name”) – whereas curl -sS http://shortdoi.org/10.12334
/567890?format=json, much less helpfully, returns nothing at all.

Technically, it does return something (try adding `-v` to the call) -- it yields a `400 Bad Request`. I could look at getting that in the quality report. But flagging these in the UI should really be done by Zotero (translation: I hate UI work)

**Comment by retorquere** [comment] 2017-11-19 17:52
Mind that even 4883 is not yet a candidate for release as-is. The cache invalidation aspects are only partially handled right now, I need to think about those.

**Comment by retorquere** [comment] 2017-11-19 20:29
Re: invalid DOIs: another option is to test the DOI before even submitting them to shortDOI. [This](https://www.npmjs.com/package/doi-regex) claims it can give a say-so on validity.

**Comment by njbart** [comment] 2017-11-19 20:58
[This](https://www.npmjs.com/package/doi-regex) just seems to check whether a string complies with the formal rules for constructing a DOI, but not whether it actually resolves at doi.org (or shortdoi.org). I’ve come across quite a few that are listed, e.g., on publishers’ websites, but do not actually resolve at doi.org – I will try to dig up a few examples if needed.

**Comment by retorquere** [comment] 2017-11-19 21:16
No need, I believe you. I've asked doi.org whether that 400 bad request reliably means "not a valid doi"

**Comment by njbart** [comment] 2017-11-19 21:25
Ok, but just for the record, one such example is http://www.tandfonline.com/doi/abs/10.1080/02255189.2010.9669289

**Comment by retorquere** [comment] 2017-11-22 10:07
More ponderings... doing to in the background is possible and a change in the DOI could trigger a re-fetch of the shortDOI, but if you have auto-export set up, the auto-exporter may be kicked off before the shortDOI resolves. 

TBH it's not very likely to happen often, as the auto-export has a non-configurable delay of 1 second to prevent "contact bounce", so the DOI resolution would have at least that full second. But it's still possible, and that happening is going to be hard to explain. And the fix would be "just make a random change again to that item and then undo that change" to kick off the export with the now-fetched DOI. I don't like that behavior, conceptually, even if it's not going to happen often.

The easy way around this is to just do the resolution before I kick off the auto-export. In day-to-day operation, there would be no difference between

* reference changed => schedule a shortDOI resolution, when scheduled task gets to the front of the queue, resolve, and
* reference changed => resolve shortDOI

and it'd mean that the shortDOI is resolved before the auto-export kicks off. The main difference would be if you start up for the first time with a massive library (and I've seen 40k refs in libraries), this would mean potentially 40k HTTP calls, and even if I do parallelize those (to the extent that Javascript allows parallelization, which it doesn't really), it would still be a very noticable startup delay. Same goes really if this were to become an at-will toggle; it's currently set up to only do batch resolve at start, but if it were supported that you could turn this on without a restart, flipping a toggle could well mean your Zotero gets very, very slow until the batch clears. I don't know. I've not tried. But it would be slower than the initial scan for citekeys.

For the curious BTW, the 1-second delay is to prevent unnecessary exports. If you edit a reference field and it loses focus, I get a notification of the reference changing, which kicks off auto-export. But if that focus loss is because you just jumped to the next field to edit that, I'd be kicking off a series of exports unnecessarily, each overwriting the former, until the edits to that item "settle". With the contact-bounce-delay, any edit you make that would affect an auto-export pushes the export for that collection ahead a further second.

**Comment by retorquere** [comment] 2017-11-22 16:49
If one of you knows someone at DOI.org... I've not gotten an answer yet on the HTTP response code 400 unambiguously meaning invalid DOI. The other option would be to query the Proxy Server REST API before resolving the shortDOI, but that would mean two HTTP calls for each shortDOI resolution.

**Comment by retorquere** [comment] 2017-11-29 08:45
no one with contacts at DOI.org?

**Comment by adunning** [comment] 2017-11-29 12:11
I know people at DataCite, but that likely won't help. I do know that it won't generate a shortDOI for any invalid DOI, though of course it could become valid in the future. For example, the article at <http://classics.oxfordre.com/view/10.1093/acrefore/9780199381135.001.0001/acrefore-9780199381135-e-8233> is listed as having the DOI `10.1093/acrefore/9780199381135.013.8233`, but it doesn't resolve at the moment, and the shortDOI service won't do anything with it.

**Comment by njbart** [comment] 2017-11-29 12:17
I don’t have contacts at doi.org, sorry. But if a request containing an invalid DOI returns `400 Bad Request` – isn’t that sufficiently clear? (I mean, the server actually returning something indicates the network is up – is there anything else that could cause such a response?) Or, only if http://shortdoi.org/10.0000/xxx?format=json returns `400 Bad Request`, you could try http://shortdoi.org/10.0000/xxx next, which returns “Sorry. Your request failed. 10.0000/xxx is not a valid DOI name.” – about as unambiguous as it gets. This second step would only be required for invalid DOIs, which I wouldn’t expect to turn up too frequently in Zotero’s sources, and, subsequently, in users’ databases.

**Comment by retorquere** [comment] 2017-11-29 12:30
I'm just not sure whether `400` has other meanings; I'd be inclined to treat a `400` as `don't try this DOI` again, but if there are transient errors that also get a `400`, that would not work.

Requesting the non-JSON url is indeed unambiguous but I'd rather not have to parse user-oriented (non-semantic) HTML.

**Comment by njbart** [comment] 2017-11-29 15:22
> Requesting the non-JSON url is indeed unambiguous but I'd rather not have to parse user-oriented (non-semantic) HTML.

Understandable in general, but that particular page is fairly standardized – you’d just have to grep for `is not a valid DOI name`.

**Comment by retorquere** [comment] 2017-11-29 16:21
Ah, yeah, that makes sense, but then I can query the doi proxy server and I don't have to scrape.

**Comment by retorquere** [comment] 2017-11-29 21:08
https://forums.zotero.org/discussion/69146/new-plugin-zotero-shortdoi-lookup#latest

**Comment by bwiernik** [comment] 2018-06-23 17:38
Yes, I’d recommend that BBT not deal with shortDOIs and leave it to DOI Manager simply populate the DOI field.

**Closed** 2018-06-23 20:33 UTC
Labels: enhancement
