### ISSUE TITLE
Export to bib fails + debug log fails

### ISSUE THREAD

**Issue by Baumtomographie** [retorquere/zotero-better-bibtex#2894] opened 2024-05-30 20:19 UTC
### Debug log ID

N/A

### What happened?

Attempting to export bibliography to *.bib fails with error. Trying to send a debug log had no result for an hour, so there is no log ID. If every item threw an error, it would be >25,000 items. Maybe that's too many?
Before one of the last updates, log IDs were shown.
So, no helpful information, but thought I'd might report it anyway.

**Comment by Baumtomographie** [comment] 2024-05-30 20:23
The nearest possible equivalent to  “Help” > “Send debug log to file.io” gave a debug log ID of BWRBW3XJ-euc/6.7.202-6

**Comment by retorquere** [comment] 2024-05-30 22:40
you're running out of memory; Zotero 6 on Windows is memory-constrained. Zotero 7 will likely work; I'm independently working on a solution that will work on both (which will reduce memory use and would make exports faster) but I'm hitting some barriers that I'm discussing with the Zotero devs, so I can't currently provide an ETA on that.

**Comment by retorquere** [comment] 2024-06-01 19:27
This is a duplicate of #2315. I expect to have a fix in the coming weeks.

**Closed by retorquere** 2024-06-01 19:27 UTC
Labels: awaiting-user-feedback
