### ISSUE TITLE
Better BibTex not working after last night's Zoter beta reelase

### ISSUE THREAD

**Issue by satikusala** [retorquere/zotero-better-bibtex#1905] opened 2021-08-29 16:28 UTC
*Please verify **all** of the below before submitting*:

1. you have picked the right category for the issue in the previous screen.
2. You are on the latest release of Zotero
3. in the Zotero addons screen you can see that you have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest)
4 you are posting a single question.
5. the issue has a subject that succinctly describes the problem or question.
6. you are available for follow-up questions and testing.

Picking the right issue category is really important. Each category (`Export`, `General error`, `Import`, `Key generation`, `Question`) has different instructions for gathering the data necessary required to resolve the issue you are experiencing

**Your question/suggestion:**
Hey there, I updated to the latest beta release this morning and Better BibTex is no longer loading. I have Better BibTex for Zotero 5.4.28 installed. And Zotero 5.0.97-beta.40+952663de7. installed. It was all working fine yesterday. Broke this morning when updating to the new Zotero release. I tried going back to an old Zotero release and it said my database was no longer up to date. Can you help?

**Comment by retorquere** [comment] 2021-08-29 16:47
Duplicate of #1899

**Closed by retorquere** 2021-08-29 16:47 UTC
Labels: question
