### ISSUE TITLE
[Bug]: citation key field and menu disappears after closing/reopening Zotero window

### ISSUE THREAD

**Issue by champagnealexandre** [retorquere/zotero-better-bibtex#2574] opened 2023-07-13 14:29 UTC
### Debug log ID

A9VLYPLS-refs-euc

### What happened?

Steps to reproduce:
- start Zotero
- close the window (e.g., with CMD-W)
- reopen Zotero (e.g., clicking on the Zotero icon)

The "Citation key" field in the Info pane has now disappeared. The "Better Bibtex" menu (when right-clicking on items) as well.

This seems new, and I see the plugin has been updated two days ago so could be related to new commits.

Zotero version: 6.0.26
BBT version: 6.7.93

I have sent the debug log but I’m not sure it will contain anything useful because when reproducing the bug the BBT menu disappears until I restart Zotero (and logging then gets disabled).

**Comment by retorquere** [comment] 2023-07-21 21:15
This is a duplicate of #2541; I'm trying to solve both as part of #2522.

**Closed** 2023-07-21 21:15 UTC
Labels: bug, awaiting-user-feedback
