### ISSUE TITLE
Better Bibtex isn't automatically pinning citation keys despite the setting to do so after 1 sec

### ISSUE THREAD

**Issue by odysseus90210** [retorquere/zotero-better-bibtex#2960] opened 2024-08-27 22:57 UTC
### Debug log ID

ZNPERUAA-refs-euc/6.7.225-7

### What happened?

Although I have set an auto pin delay of 1 sec, references aren't being automatically pinned (although manual pinning works). I don't understand why not.

**Comment by retorquere** [comment] 2024-08-28 06:33
I don't see a change to any item in the log.

**Comment by odysseus90210** [comment] 2024-08-28 11:45
I don't know why the auto-pinning wasn't working. Selecting all the references and choosing to "Refresh BibTex key" (even though the keys were already there) seems to have fixed the problem.

**Comment by odysseus90210** [comment] 2024-08-28 14:03
I believe autopin has been on the whole time. What exactly does pinning do?

**Comment by retorquere** [comment] 2024-08-28 15:03
> I believe autopin has been on the whole time.

I can't tell what your scenario was without a log taken while the behavior occurred.

> What exactly does pinning do?

It writes the key to the Extra field after which it will no longer change (without you forcing it). The benefit of doing that is that these keys will sync across machines and will show up in the Overleaf integration.

At some point Zotero will add a real citation key field (it's been in their plans for a while), and at that point it will migrate automatically out of the extra field.

**Comment by retorquere** [comment] 2024-08-30 23:42
I don't think there's anything else I can do right now?

**Comment by odysseus90210** [comment] 2024-08-31 03:11
I guess not, but when I was unable to insert references because of "invalid key" situation, the key was indeed in the extra field, which is strange.

**Comment by retorquere** [comment] 2024-08-31 03:20
I don't understand? If the key is in the extra field it has a key?

**Comment by odysseus90210** [comment] 2024-08-31 03:20
On you can know why your plugin wasn't finding it.

**Comment by retorquere** [comment] 2024-09-04 07:37
I find this response so strange. I'm saying I don't understand what you're saying and your response is that "you should understand because it is your plugin"?

I do not understand the situation you were describing, and I can't derive understanding from a log I don't have. I don't know what was happening at the time on a system I have no access to; the behavior isn't structural because all my tests in the test suite would fail. Without a log covering the problem or local replicability there is just not much I can do, and it isn't yet clear to me that we're actually talking about a BBT problem (see below).

> I guess not, but when I was unable to insert references because of "invalid key" situation, the key was indeed in the extra field, which is strange.

1. If the key is in the extra field, it has a *citation* key, and
2. I don't know what you mean by "inserting references" in the context of BBT citation keys; if it is about inserting in Word, BBT citation keys play no role there.

BBT doesn't have the string "invalid key" anywhere, I don't know what "invalid key" would mean to BBT, and the only place that I see "invalid key" in the Zotero source has to do with syncing, and those keys are the technical item keys that Zotero assigns to items, not citation keys.

**Comment by odysseus90210** [comment] 2024-09-04 08:03
Sorry. These tools are so complex (Zotero has its plugins, Logseq has its plugins …) that I get confused. Your plugin is great and the fact that you’re doing this for free, on your own spare time, is amazing!

**Comment by retorquere** [comment] 2024-09-04 08:13
Ah you're inserting something in LogSeq. I don't know about that integration, if you get the author of that plugin involved maybe we can get to the bottom of this.

**Comment by retorquere** [comment] 2024-09-05 11:40
Are you going to get the author of the logseq integration involved? Otherwise we can close this issue.

**Comment by odysseus90210** [comment] 2024-09-05 15:01
Sorry for the confusion, but this issue is about auto-pinning not occurring. And as a matter of fact, I'm seeing that now. I had Zotero download a reference using the "Add Items by Identifier" toolbar icon. Better Bibtex still hasn't put the citation key in the Extra field for reasons that escape me. How can we troubleshoot?

**Comment by retorquere** [comment] 2024-09-05 15:11
Reproduce, send a log

**Comment by odysseus90210** [comment] 2024-09-05 16:17
It stopped being correctly installed. How could it appear under Tools > Plugins without a corresponding pane in Zotero's settings?

You can close this issue.

**Comment by retorquere** [comment] 2024-09-06 08:05
When you say 

> Better Bibtex still hasn't put the citation key in the Extra field

I assumed you have BBT installed. If it is not installed, it obviously won't do anything. Are you saying now you cannot install BBT?

I have a sense you are trying to talk about many things at once; I have no idea what you want(ed) help with. I'd love to help, but I am thoroughly confused on what problem you want addressed.

> You can close this issue.

OK....

**Closed by retorquere** 2024-09-06 08:05 UTC
Labels: question
