### ISSUE TITLE
BetterBibTex on Windows 11 with Zotero: cannot open BBT preferences

### ISSUE THREAD

**Issue by mariagrundmann** [retorquere/zotero-better-bibtex#2860] opened 2024-05-01 11:47 UTC
### Debug log ID

TCEW6RUL-refs-euc/6.7.179-6

### What happened?

When going to Edit -> Preferences -> BBT -> Open Better Bib Tex Preferences I get the following error message.

XML Parsing Error: undefined entity
Location: chrome://zotero-better-bibtex/content/preferences.xul
Line Number 425, Column 15:              <checkbox class="bbt-autoexport-options bbt-autoexport-BetterBibLaTeX bbt-prefs-2col-span" data-ae-field="biblatexChicago" label="&better-bibtex_preferences_auto-export_fields_biblatexChicago.label;" oncommand="Zotero.BetterBibTeX.PrefPane.autoexport.edit(this)"/>
--------------^

I dont think it has sth to do with certain documents, but I created a debug log ID anyway. I hope I understood correctly.

**Comment by stefan-kuepper** [comment] 2024-05-01 11:56
Seems like a duplicate of #2858

**Comment by mariagrundmann** [comment] 2024-05-01 12:00
> Seems like a duplicate of #2858

you are right, I apologise.

**Closed** 2024-05-01 12:09 UTC
Labels: question
