### ISSUE TITLE
Escape underscore in DOI

### ISSUE THREAD

**Issue by basxto** [retorquere/zotero-better-bibtex#1341] opened 2019-11-27 10:16 UTC
**Report ID:**

2U8KSCCH-euc

**Exporter used:**

Better BibTeX, but looks the same  in better BibLaTeX

**Expected behavior:**

Underscores being escaped in DOIs, since LaTeX adds $s otherwise, throws errors and breaks the reference section.

**Actual behavior:**

They don’t get escaped.

**Comment by retorquere** [comment] 2019-11-27 10:20
Duplicate of https://github.com/retorquere/zotero-better-bibtex/issues/1336 , and in biblatex these are per spec not escaped, as `doi` is a verbatim field.

**Comment by retorquere** [comment] 2019-11-28 13:32
Does this give you enough information?

**Comment by retorquere** [comment] 2019-11-28 13:32
Does this give you enough information?

**Closed** 2019-11-28 21:29 UTC
Labels: awaiting-user-feedback, question

**Comment by blip-bloop** [comment] 2019-12-01 10:42
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.164.5238](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.164.5238.xpi) ("warn for doi and url fields -- fixes #1341")

Install in Zotero by downloading [test build 5.1.164.5238](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.164.5238.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".
