### ISSUE TITLE
Error ID XADRN3E6 - BBT not loading/disabled

### ISSUE THREAD

**Issue by jrennstich** [retorquere/zotero-better-bibtex#607] opened 2016-11-11 06:48 UTC
Under Zotero > Preferences, the BBT tab states "Better BibTeX has been disabled" followed by the following code:
Initialize failed: Invalid bound parameter [object Object] in [
    "0": [object Object] {
        "_id": 322843
        "_libraryID": 2064660
        "_name": "oncreate"
        "_description": ""
        "_editable": true
        "_filesEditable": true
        "_loaded": true
        "_changed": false
        "_hasCollections": null
        "_hasSearches": null
        "_init": function ) {...}

        "objectType": "group"
        "id": 322843
        "libraryID": 2064660
        "name": "oncreate"
        "description": ""
        "editable": true
        "filesEditable": true
        "_get": function field) {...}

        "_set": function field, val) {...}

        "load": function ) {...}

        "loadFromRow": function row) {...}

        "exists": function ) {...}

        "hasCollections": function ) {...}

        "hasSearches": function ) {...}

        "clearCollectionCache": function ) {...}

        "clearSearchCache": function ) {...}

        "getCollections": function parent) {...}

        "hasItem": function itemID) {...}

        "save": function ) {...}

        "erase": function ) {...}

        "serialize": function ) {...}

        "_prepFieldChange": function field) {...}

    }
] [QUERY: SELECT libraryID FROM groups WHERE groupID=?]

Error ID XADRN3E6

<img width="897" alt="screenshot_147" src="https://cloud.githubusercontent.com/assets/22581234/20206760/07b0d252-a7e3-11e6-9b10-66fdafc4d3d1.png">

**Comment by retorquere** [comment] 2016-11-11 06:56
Duplicate of #606

**Closed by retorquere** 2016-11-11 06:56 UTC
