### ISSUE TITLE
not compatible with Zotero 5.0.2

### ISSUE THREAD

**Issue by stfl** [retorquere/zotero-better-bibtex#684] opened 2017-07-12 12:07 UTC
zotero version: `Zotero Zotero 5.0.2, Copyright (c) 2006-2017`

zotero-better-bibtex-1.6.100.xpi

```
1499861075895   addons.xpi      WARN    Add-on better-bibtex@iris-advies.com is not compatible with application version.
```

**Comment by retorquere** [comment] 2017-07-12 12:14
duplicate of #555

**Closed by retorquere** 2017-07-12 12:14 UTC
