### ISSUE TITLE
Better BibTeX hangs at startup "Starting key manager..." (data from early betas in DB)

### ISSUE THREAD

**Issue by jogrue** [retorquere/zotero-better-bibtex#799] opened 2017-11-18 12:56 UTC
I do not know which update this is related to (or if it is), but Zotero and Better BibTeX have received updates recently. And now Better BibTeX hangs at "Starting key manager..." after startup:

![image](https://user-images.githubusercontent.com/7724599/32980493-94a7719e-cc67-11e7-81d5-9e4d769776a3.png)

 I can still access the menu and send a bug report (ID: UU9X7EUI). But it is not possible to access my library. In the bug report, it gives an error for one item. This item has the following information in Extra: "bibtex*:almohammad-theory-2016". I do not remember that I changed anything for this item recently, I think it was added a year ago.

And this is all on Windows, I have not tried it on the Linux machine I usually work on yet.

**Comment by blip-bloop** [comment] 2017-11-18 14:15
:robot: this is your friendly neighborhood build bot announcing [test build 4847](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.42.4847.issue-799.xpi) ("add logging for #799").

**Comment by blip-bloop** [comment] 2017-11-18 14:36
:robot: this is your friendly neighborhood build bot announcing [test build 4848](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.42.4848.issue-799.xpi) ("make scrubbing configurable").

**Comment by retorquere** [comment] 2017-11-18 16:09
Can you install 4848, enable the hidden config parameter "scrubDatabase", and restart?

**Comment by schmattes** [comment] 2017-11-18 19:09
I'm facing the same problem. Installing 4348, enabling the hidden config parameter "scrubDatabase", and restarting does not solve it for me. Zotero 5.0.27 (OS X) and test build 4848

**Comment by retorquere** [comment] 2017-11-18 19:17
@schmattes can you get me a debug report?

**Comment by schmattes** [comment] 2017-11-18 21:04
For sure.
Report ID: 4LYMGVF7

**Comment by blip-bloop** [comment] 2017-11-18 22:05
:robot: this is your friendly neighborhood build bot announcing [test build 4867](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.42.4867.issue-799.xpi) ("scrub harder").

**Comment by retorquere** [comment] 2017-11-18 22:06
Can you try 4867?

**Comment by schmattes** [comment] 2017-11-19 09:14
Problem still occurs 😢
Report ID: 7RQ3SPER

**Comment by blip-bloop** [comment] 2017-11-19 09:55
:robot: this is your friendly neighborhood build bot announcing [test build 4878](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.42.4878.issue-799.xpi) ("scrub javascript, not ruby :roll_eyes:").

**Comment by retorquere** [comment] 2017-11-19 09:57
4878 ought to be better

**Comment by schmattes** [comment] 2017-11-19 10:37
It seems to work fine now. Thank very much!

**Comment by jogrue** [comment] 2017-11-19 17:54
Wow. Thanks, it works for me as well. Any need for further bug reports or can this be closed?

**Comment by retorquere** [comment] 2017-11-19 18:09
Cool. I'll fold this into master and release. You can turn off the scrub setting btw, it won't do anything except slow down startup now.

**Comment by averter** [comment] 2017-11-27 20:50
Hi. I am also affected by this one. Even with the latest version. Report number is ADTE6MAN.

**Comment by retorquere** [comment] 2017-11-28 06:29
Can you enable the [scrub Database](https://github.com/retorquere/zotero-better-bibtex/wiki/Configuration#scrubdatabase) setting and restart Zotero?

**Comment by averter** [comment] 2017-11-28 09:28
I have no config editor in zotero advanced preferences tab, so I cannot see the hidden preferences, including scrub database.  I am using Zotero 5.0.23. Is it normal?

**Comment by averter** [comment] 2017-11-28 10:14
Nevermind. I was working at the advanced tab from better bibtex. Stupid mistake. Yes. With the scrub Database enabled it works. Here goes the new report. LUS8MHJV

**Comment by retorquere** [comment] 2017-11-28 10:51
If you can now start as usual, you can turn off the setting, the problem has been fixed in your DB.

**Comment by averter** [comment] 2017-11-28 10:54
Yes. Just did so. Thanks for the help. So for future reference anyone with this problem just has to turn the scrub database off and on again.

**Comment by retorquere** [comment] 2017-11-28 10:59
The problem should not happen again -- it is caused by you being an early beta-tester which put data in your DB which is no longer in-spec. Now that that has been fixed, your DB is in spec -- should absolutely not happen again, so if it *does* happen again, please open a new issue, as it's a different problem.

**Comment by pkalikman** [comment] 2017-11-28 16:26
Hi--I'm also having this issue, even after trying the DB scrub step above.

G7UV4JTH

Thanks!

**Comment by retorquere** [comment] 2017-11-28 18:54
@pkalikman so then please open a new issue, as it must be a different problem.

**Comment by retorquere** [comment] 2017-11-29 07:53
@pkalikman I can see the error in your log, but it's a different problem, and I will need your help for the diagnosis. Please open a new issue, it allows for a more focused discussion for this particular problem.

**Comment by pkalikman** [comment] 2017-11-29 16:38
Oops--sorry. Standby.

**Comment by YuanboBQ** [comment] 2018-03-09 01:42
Hi, everyone,
I encountered a the same problem, which stuck at Starting key manager.

Below is my Errors and debug log.

```
Application: Zotero 5.0.35.1 en-US
Platform: MacIntel Intel Mac OS X 10.13
Addons:
  Markdown Here (2.13.2, extension)
  Zotero Scholar Citations (1.9.2, extension)
  Zotero Word for Mac Integration (5.0.12.SA.5.0.35.1, extension)
  Zotero LibreOffice Integration (5.0.10.SA.5.0.35.1, extension)
  Zotero Better Bib(La)Tex (5.0.99, extension)
  ZotFile (5.0.7, extension, disabled)
Settings:
  DOIandURL = "doi"
  asciiBibLaTeX = true
  asciiBibTeX = true
  autoAbbrev = false
  autoAbbrevStyle = ""
  autoExport = "off"
  autoExportIdleWait = 10
  autoPin = false
  biblatexExtendedDateFormat = true
  biblatexExtendedNameFormat = false
  bibtexParticleNoOp = false
  bibtexURL = "off"
  cacheFlushInterval = 5
  citeCommand = "cite"
  citekeyFold = true
  citekeyFormat = "[zotero]"
  citekeyScan = "5.0.2.master.3925"
  citeprocNoteCitekey = false
  csquotes = ""
  debug = false
  itemObserverDelay = 100
  jabrefFormat = 0
  jurismPreferredLanguage = ""
  keyConflictPolicy = "change"
  lockedInit = false
  parseParticles = true
  postscript = ""
  preserveBibTeXVariables = false
  qualityReport = false
  quickCopyMode = "pandoc"
  quickCopyPandocBrackets = true
  rawLaTag = "#LaTeX"
  scanCitekeys = false
  scrubDatabase = false
  skipFields = ""
  skipWords = "a,ab,aboard,about,above,across,after,against,al,along,amid,among,an,and,anti,around,as,at,before,behind,below,beneath,beside,besides,between,beyond,but,by,d,da,das,de,del,dell,dello,dei,degli,della,dell,delle,dem,den,der,des,despite,die,do,down,du,during,ein,eine,einem,einen,einer,eines,el,en,et,except,for,from,gli,i,il,in,inside,into,is,l,la,las,le,les,like,lo,los,near,nor,of,off,on,onto,or,over,past,per,plus,round,save,since,so,some,sur,than,the,through,to,toward,towards,un,una,unas,under,underneath,une,unlike,uno,unos,until,up,upon,versus,via,von,while,with,within,without,yet,zu,zum"
  strings = ""
  suppressTitleCase = false
  testing = false
  warnBulkModify = 10
  Zotero: export.quickCopy.setting = "bibliography=http://www.zotero.org/styles/chicago-note-bibliography"
```
## Errors
```
JavaScript Error: "ReferenceError: module is not defined" {file: "chrome://zoteroscholarcitations/content/scripts/zoteroscholarcitations.js" line: 234}]
@chrome://zoteroscholarcitations/content/scripts/zoteroscholarcitations.js:234:1

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/." {file: "chrome://zotero/content/xpcom/streamer.js" line: 155}]
[JavaScript Error: "WebSocket connection closed: 1006 "]
[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/." {file: "chrome://zotero/content/xpcom/streamer.js" line: 155}]
[JavaScript Error: "WebSocket connection closed: 1006 "]
[JavaScript Error: "Style with ID http://www.zotero.org/styles/apa_zh_pulipuli already loaded from apa_zh_pulipuli.csl" {file: "chrome://zotero/content/xpcom/style.js" line: 184}]
Zotero.Styles</_readStylesFromDirectory<@chrome://zotero/content/xpcom/style.js:184:8
tryCatcher@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/util.js:16:16
module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/generators.js:97:18
module.exports/Promise.prototype._settlePromise@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/promise.js:574:17
module.exports/Promise.prototype._settlePromise0@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/promise.js:614:5
module.exports/Promise.prototype._settlePromises@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/promise.js:693:13
Async.prototype._drainQueue@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/async.js:133:13
Async.prototype._drainQueues@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/async.js:143:5
Async/this.drainQueues@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/async.js:17:9

[JavaScript Error: "Style with ID http://www.zotero.org/styles/apa_zh_pulipuli already loaded from apa_zh_pulipuli.csl" {file: "chrome://zotero/content/xpcom/style.js" line: 184}]
Zotero.Styles</_readStylesFromDirectory<@chrome://zotero/content/xpcom/style.js:184:8
tryCatcher@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/util.js:16:16
module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/generators.js:97:18
module.exports/Promise.prototype._settlePromise@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/promise.js:574:17
module.exports/Promise.prototype._settlePromise0@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/promise.js:614:5
module.exports/Promise.prototype._settlePromises@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/promise.js:693:13
Async.prototype._drainQueue@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/async.js:133:13
Async.prototype._drainQueues@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/async.js:143:5
Async/this.drainQueues@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/async.js:17:9

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/." {file: "chrome://zotero/content/xpcom/streamer.js" line: 155}]
[JavaScript Error: "WebSocket connection closed: 1006 "]
[JavaScript Error: "Style with ID http://www.zotero.org/styles/apa_zh_pulipuli already loaded from apa_zh_pulipuli.csl" {file: "chrome://zotero/content/xpcom/style.js" line: 184}]
Zotero.Styles</_readStylesFromDirectory<@chrome://zotero/content/xpcom/style.js:184:8
tryCatcher@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/util.js:16:16
module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/generators.js:97:18
module.exports/Promise.prototype._settlePromise@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/promise.js:574:17
module.exports/Promise.prototype._settlePromise0@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/promise.js:614:5
module.exports/Promise.prototype._settlePromises@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/promise.js:693:13
Async.prototype._drainQueue@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/async.js:133:13
Async.prototype._drainQueues@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/async.js:143:5
Async/this.drainQueues@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/async.js:17:9

[JavaScript Error: "Style with ID http://www.zotero.org/styles/apa_zh_pulipuli already loaded from apa_zh_pulipuli.csl" {file: "chrome://zotero/content/xpcom/style.js" line: 184}]
Zotero.Styles</_readStylesFromDirectory<@chrome://zotero/content/xpcom/style.js:184:8
tryCatcher@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/util.js:16:16
module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/generators.js:97:18
module.exports/Promise.prototype._settlePromise@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/promise.js:574:17
module.exports/Promise.prototype._settlePromise0@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/promise.js:614:5
module.exports/Promise.prototype._settlePromises@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/promise.js:693:13
Async.prototype._drainQueue@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/async.js:133:13
Async.prototype._drainQueues@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/async.js:143:5
Async/this.drainQueues@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/async.js:17:9

[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/." {file: "chrome://zotero/content/xpcom/streamer.js" line: 155}]
[JavaScript Error: "WebSocket connection closed: 1006 "]
[JavaScript Error: "The connection was refused when attempting to contact wss://stream.zotero.org/." {file: "chrome://zotero/content/xpcom/streamer.js" line: 155}]
[JavaScript Error: "WebSocket connection closed: 1006 "]
```
## Debug log
```
[JavaScript Error: "ReferenceError: module is not defined" {file: "chrome://zote…
@chrome://zoteroscholarcitations/content/scripts/zoteroscholarcitations.js:234:1


[JavaScript Error: "The connection was refused when attempting to contact wss://…

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "The connection was refused when attempting to contact wss://…

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "Style with ID http://www.zotero.org/styles/apa_zh_pulipuli…
Zotero.Styles</_readStylesFromDirectory<@chrome://zotero/content/xpcom/style.js:…
tryCatcher@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zoter…
module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://gre/modules/c…
module.exports/Promise.prototype._settlePromise@resource://gre/modules/commonjs/…
module.exports/Promise.prototype._settlePromise0@resource://gre/modules/commonjs…
module.exports/Promise.prototype._settlePromises@resource://gre/modules/commonjs…
Async.prototype._drainQueue@resource://gre/modules/commonjs/toolkit/loader.js…
Async.prototype._drainQueues@resource://gre/modules/commonjs/toolkit/loader.js…
Async/this.drainQueues@resource://gre/modules/commonjs/toolkit/loader.js ->…


[JavaScript Error: "Style with ID http://www.zotero.org/styles/apa_zh_pulipuli…
Zotero.Styles</_readStylesFromDirectory<@chrome://zotero/content/xpcom/style.js:…
tryCatcher@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zoter…
module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://gre/modules/c…
module.exports/Promise.prototype._settlePromise@resource://gre/modules/commonjs/…
module.exports/Promise.prototype._settlePromise0@resource://gre/modules/commonjs…
module.exports/Promise.prototype._settlePromises@resource://gre/modules/commonjs…
Async.prototype._drainQueue@resource://gre/modules/commonjs/toolkit/loader.js…
Async.prototype._drainQueues@resource://gre/modules/commonjs/toolkit/loader.js…
Async/this.drainQueues@resource://gre/modules/commonjs/toolkit/loader.js ->…


[JavaScript Error: "The connection was refused when attempting to contact wss://…

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "Style with ID http://www.zotero.org/styles/apa_zh_pulipuli…
Zotero.Styles</_readStylesFromDirectory<@chrome://zotero/content/xpcom/style.js:…
tryCatcher@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zoter…
module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://gre/modules/c…
module.exports/Promise.prototype._settlePromise@resource://gre/modules/commonjs/…
module.exports/Promise.prototype._settlePromise0@resource://gre/modules/commonjs…
module.exports/Promise.prototype._settlePromises@resource://gre/modules/commonjs…
Async.prototype._drainQueue@resource://gre/modules/commonjs/toolkit/loader.js…
Async.prototype._drainQueues@resource://gre/modules/commonjs/toolkit/loader.js…
Async/this.drainQueues@resource://gre/modules/commonjs/toolkit/loader.js ->…


[JavaScript Error: "Style with ID http://www.zotero.org/styles/apa_zh_pulipuli…
Zotero.Styles</_readStylesFromDirectory<@chrome://zotero/content/xpcom/style.js:…
tryCatcher@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zoter…
module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://gre/modules/c…
module.exports/Promise.prototype._settlePromise@resource://gre/modules/commonjs/…
module.exports/Promise.prototype._settlePromise0@resource://gre/modules/commonjs…
module.exports/Promise.prototype._settlePromises@resource://gre/modules/commonjs…
Async.prototype._drainQueue@resource://gre/modules/commonjs/toolkit/loader.js…
Async.prototype._drainQueues@resource://gre/modules/commonjs/toolkit/loader.js…
Async/this.drainQueues@resource://gre/modules/commonjs/toolkit/loader.js ->…


[JavaScript Error: "The connection was refused when attempting to contact wss://…

[JavaScript Error: "WebSocket connection closed: 1006 "]

[JavaScript Error: "The connection was refused when attempting to contact wss://…
```

**Comment by retorquere** [comment] 2018-03-09 06:17
Hi, the key manager not finishing loading is usually a side effect from another error. Can you open a new issue, submit a BBT error log through the menu, and post the debug ID there?

**Closed** 2018-03-09 08:00 UTC
Labels: awaiting-user-feedback, bug

**Comment by retorquere** [comment] 2018-03-10 15:15
Hi, I still really want to address this, but it's almost certainly not the same problem as reported here (or it'd be fixed now), and if we were to continue here all the previous participants would be getting notifications. Please do open a new issue, with a bbt debug log.
