### ISSUE TITLE
add date, origdate functions, and format-date filter

### ISSUE THREAD

**Issue by Ypot** [retorquere/zotero-better-bibtex#1488] opened 2020-04-12 16:21 UTC
KP76A4AB-euc

For citekeys referring to forum posts, I want to see complete date, with day and month. For books I use origyear.
So I want to use complete Date when no origyear exists. I have tried:
[origyear:(Date)]

But it doesn't work as I intended, because if there is a date in the fields, not origyear, it doesn't show the month and day, it just shows the year.
If I would edit it to:
[Date]
I works fine, showing year, month and day.

**Comment by blip-bloop** [comment] 2020-04-14 08:42
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.21.6365](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6365.xpi) ("adjust tests")

Install in Zotero by downloading [test build 5.2.21.6365](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6365.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment] 2020-04-14 08:53
In `[origyear:(Date)]`, `(Date)` means the literal text `Date`. This is something I inherited when I decided tp copy the JabRef format -- in retrospect I should just have designed my own, but that's water under the bridge now.

For now, you might be helped using something like 

```
[=forumPost][shorttitle][date] | [shorttitle][origyear]
```

In this:

* `[=forumPost]` means "break off key generation unless the item is a forum post". You can specify multiple types by separating them with a `/`.
* ` | ` means "If the pattern so far hasn't generated any text, restart with the following pattern". You can have multiple of these.
* `[date]` is new in 6365, and means "date if you have it, origdate if not"
* `[origdate]` is new in 6365, and means "origdate if you have it, date if not"
* `[year]` means "year if you have it, origyear if not"
* `[origyear]` means "origyear if you have it, year if not"

**Comment by blip-bloop** [comment] 2020-04-14 09:15
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.21.6366](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6366.xpi) ("docs")

Install in Zotero by downloading [test build 5.2.21.6366](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6366.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment] 2020-04-17 06:55
Can you test whether 6366 provides a sufficient solution for you?

**Comment by blip-bloop** [comment] 2020-04-17 20:54
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.21.6396](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6396.xpi) ("fixes #1488")

Install in Zotero by downloading [test build 5.2.21.6396](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6396.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by Ypot** [comment] 2020-04-18 11:20
Hi.
XUGAXILI-euc
It doesn't work it seems:

[origyear:(Date):prefix=.] generates-> .2019 
[Date:prefix=.] generates -> .2019/01/2809:10:00

**Comment by retorquere** [comment] 2020-04-18 12:10
> [origyear:(Date):prefix=.] generates-> .2019

The filter `(X)` means "if the current block hasn't generated any text yet, output the literal text `X`, where `X` is `Date` in this case. But since `origyear` generates text, that will just be returned, prefixed with a `.`

> [Date:prefix=.] generates -> .2019/01/2809:10:00

Here `Date` is a function, not a filter, and `Date` just means "whatever is in the `Date` field in zotero". I've added a filter `format-date` that will parse the date and change it into something regular. The default format is `0y-0m-0d`, where a leading `0` means "right-adjust and fill with `0` if necessary, `y` means year, `m` means month, and `d` means day. Everything that's not one of those is just copied to the output. If you'd do `[Date:format=date-0y-0m]` you'd get `2019-01`, if you do `[Date:format-date=m.d.y]` you'd get `1.28.2019`, etc.

There isn't a way to say "if the current block didn't generate any text, call this function instead". There is a very limited way to do something like this with `[>0]` and `|` but `[>0]` looks at all blocks before it and starts the next pattern, it does not retain anything that's been partially generated.

**Comment by Ypot** [comment] 2020-04-18 14:00
Thanks, the I did it as explained in post https://github.com/retorquere/zotero-better-bibtex/issues/1488#issuecomment-613313449

This is my Citekey generator:
`[Auth:lower:capitalize][=forumPost/WebPage][Date:prefix=.][shorttitle3_3:lower:capitalize:prefix=.][Pages:prefix=.p.][Volume:prefix=.Vol.][NumberofVolumes:prefix=de] | [origyear:prefix=.][shorttitle3_3:lower:capitalize:prefix=.][Pages:prefix=.p.][Volume:prefix=.Vol.][NumberofVolumes:prefix=de]`

Just the Date+hour doesn't fit well, I suppose format-date still can't parse the hour?

**Comment by retorquere** [comment] 2020-04-18 14:14
> Thanks, then I did it as explained in post [#1488 (comment)](https://github.com/retorquere/zotero-better-bibtex/issues/1488#issuecomment-613313449)

It's not the same. That comment describes `date`, you are using `Date`. These are not the same. `[date]` corresponds to `[Date:format-date=0y-0m-0d]`.


> `[Auth:lower:capitalize][=forumPost/WebPage][Date:prefix=.][shorttitle3_3:lower:capitalize:prefix=.][Pages:prefix=.p.][Volume:prefix=.Vol.][NumberofVolumes:prefix=de] | [Auth:lower:capitalize][origyear:prefix=.][shorttitle3_3:lower:capitalize:prefix=.][Pages:prefix=.p.][Volume:prefix=.Vol.][NumberofVolumes:prefix=de]`

The usual notation BTW is to put `[=<type>]` at the start. This will work all the same; `[=<type>]` just aborts the current pattern if there's a itemtype mismatch regardless of what was generated before.

> Just the Date+hour doesn't fit well, I suppose format-date still can't parse the hour?

`:format-date` does not produce hour fields.

For all functions that start with a capital letter you must do all processing yourself. Functions that start with a lowercase letter have varying amounts of processing already applied. But if you request `[Date:prefix=.]`, you'll get whatever is in the Zotero `Date` field, prefixed with a `.`, with no processing applied at all, and that will yield the time in the key if the time is in the `Date` field in Zotero.

**Comment by Ypot** [comment] 2020-04-18 14:42
Thanks. I used "Date" because I want time in the Citekey: for Twitter or forums it can be important.

**Comment by blip-bloop** [comment] 2020-04-19 00:26
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.21.6406](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6406.xpi) ("that was quite the rabbit hole")

Install in Zotero by downloading [test build 5.2.21.6406](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6406.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment] 2020-04-19 00:37
In the citekey? To each their own 🤷 . 

Man, that was quite the rabbithole. 6406 adds time support to format-date; I've also changed the spec format to be strftime-alike; I should be using (de facto or otherwise) standards more often instead of going it my own. That would make the date-and-time format: `[Date:format-date=%Y-%m-%d.%H\:%M]` (the backslash in the pattern is required to distinguish it from a start of a new filter). Not all strftime formatters are available, currently just `yYmdHMS`, and there's one minor addition in that `yYmd` can be prefixed with `o` to get their `orig` equivalents.

**Comment by Ypot** [comment] 2020-04-19 09:13
Thanks a lot. It works great:
`[=forumPost/WebPage][Auth:lower:capitalize][Date:format-date=%Y-%m-%d.%H\:%M\:%S:prefix=.][PublicationTitle1_1:lower:capitalize:prefix=.][shorttitle3_3:lower:capitalize:prefix=.][Pages:prefix=.p.][Volume:prefix=.Vol.][NumberofVolumes:prefix=de] | [Auth:lower:capitalize][origyear:prefix=.][PublicationTitle1_1:lower:capitalize:prefix=.][shorttitle3_3:lower:capitalize:prefix=.][Pages:prefix=.p.][Volume:prefix=.Vol.][NumberofVolumes:prefix=de]`

A doubt: why are we using Date (with a capital letter) instead of date?

I'm not sure if the "o" prefix is working: [Date:format-date=%oY] nor [date:format-date=%oY]
KPKAIVCU-euc

**Comment by blip-bloop** [comment] 2020-04-19 23:25
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.21.6408](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6408.xpi) ("also uses extra-fields for orig-date for #1488")

Install in Zotero by downloading [test build 5.2.21.6408](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6408.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment] 2020-04-19 23:41
Man that was another rabbit-hole.

> A doubt: why are we using Date (with a capital letter) instead of date?

because before 6408, `[date]` was just an alias for `[Date:format-date=%Y-%m-%d]`, as I outlined above. 

> I'm not sure if the "o" prefix is working: [Date:format-date=%oY] nor [date:format-date=%oY]

Using `[date:format-date=%Y]` would only work because `format-date` parses the input into a date, and the date resulting from `[date]` is easy to parse, but `[date:format-date=%H]` would always yield an empty string, because `[date]` never includes time info. `[Date]` is just the contents of the Zotero `Date` field. Whatever is in that field is present in `[Date]`.

So, the explanation: `%oY` does work, but your `Date` field doesn't have `orig` info (it can, but in your case it is in another field), so there's nothing to pick up. The `orig` info is in the `extra` field, and `Date` doesn't look there.

6408 changes things a bit. `[date]` is still an alias for `[Date:format-date=%Y-%m-%d]`, but `[date]` can now take a format string directly, and `[date]` does merge orig-date from the `extra` field. So `[date=%oY]` will also pick up an orig-date from the extra field. I'll need to update the docs for all of that.

**Comment by retorquere** [comment] 2020-04-21 22:25
So it works to your satisfaction now?

**Comment by retorquere** [comment] 2020-04-22 05:57
I'd really prefer to know it works for you as intended before merging.

**Comment by retorquere** [comment] 2020-04-23 13:47
I'm looking to cut a new release in the next few days and I'd prefer to roll this into that release. But for that I really do need to know that no other changes will be required for your use-case.

**Comment by Ypot** [comment] 2020-04-23 16:30
Hi.
Sorry for the delay. It already worked great, now trying the new update 5.2.21.6408, something happened. It sent an error message saying that there were problems generating citekeys, and the addon started a setup like if a new installation.

**Comment by retorquere** [comment] 2020-04-23 16:33
Dammit. What was the format you used before?

**Comment by retorquere** [comment] 2020-04-23 16:35
Oh hold on, I see it. On it.

**Comment by Ypot** [comment] 2020-04-23 16:37
5.2.21.6406 works like a charm though. For me it's good.
HV4E6J8A-euc

**Comment by retorquere** [comment] 2020-04-23 16:38
Damn. OK, so your format has an error, and that's checked during startup, but BBT should have allowed you to correct it. 6408 does stricter checking on errors.

The key has `PublicationTitle1_1`, and that's not meaningful to the format parser. I'll have to think about how to handle that on startup.

**Comment by retorquere** [comment] 2020-04-23 16:40
What 6406 does is not good perse because it allows you to enter gibberish without feedback.

**Comment by retorquere** [comment] 2020-04-23 16:42
And specifically, 6408 would never have allowed you to enter it.

**Comment by blip-bloop** [comment] 2020-04-23 20:59
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.21.6430](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6430.xpi) ("strip invalid parts from pattern on start")

Install in Zotero by downloading [test build 5.2.21.6430](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6430.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment] 2020-04-23 21:05
6430 will remove the invalid parts during startup and notify you about them but will leave the pattern unchanged otherwise.

**Comment by blip-bloop** [comment] 2020-04-23 22:09
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.21.6431](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6431.xpi) ("save when valid")

Install in Zotero by downloading [test build 5.2.21.6431](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.21.6431.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment] 2020-04-24 10:43
> And specifically, 6408 would never have allowed you to enter it.

I had posted an explanation of this, but I don't see it anymore. Don't know what happened to it, but here goes again:

If you fill out a pattern, you'll have noticed that during typing, the field turns orange, and the tooltip shows an error. As long as the pattern is invalid, the field stays orange; if you get to a point where the pattern is valid, the field turns white.

The pattern is only saved when it's valid. If you take the focus away from the edit field, by e.g. tabbing to another field, clicking another field, or closing the preferences screen (indicating you are done editing the pattern) while it is still orange, the pattern is restored to the previous, assumed valid version. This assumption is in place because a) BBT really can't work without a key generator, and b) because you start with a valid pattern at first-run of BBT, and you can only save valid patterns, the previous pattern should always be valid.

versions before 6408 were slightly broken in that there was one specific edge case (being invalid input at the end of a property field -- fields that start with a capital letter) would be ignored by accident. It would never generate any output, so it would be useless in the pattern, but it was not recognized as an error by the formatter. So these versions would allow saving of an invalid pattern.

6408 and later checks for existence of property fields (and coincidentally allows for misspellings -- `NumberofVolumes` should have been an error in < 6408 but is now valid) so it detected the error, but then during startup demands a valid pattern, so falls back to the initial default.

6431 will strip invalid parts from the pattern during startup, and will notify you about that it does this. The valid parts remain. I have added the key you entered in the test suite so that this stripping is tested. If all parts end up being stripped, BBT will still fall back to the initial default.

Can you try 6431?

**Comment by Ypot** [comment] 2020-04-24 20:25
Yes, it seems it removed this part: [PublicationTitle1_1:lower:capitalize:prefix=.]

**Comment by Ypot** [comment] 2020-04-24 20:37
I had it on my config [to add chapter to the citekey](https://github.com/retorquere/zotero-better-bibtex/issues/1388), but in fact I am not using citekeys for chapters, so it's ok.

For me, the update is good. But maybe you need to know that I think [date=%oY] doesn't seem to work.
And, BTW, if you think original date should be in a different field, let me know. I just prefer this date, over the edition publication date ;)

**Comment by retorquere** [comment] 2020-04-24 20:52
`[date=%oY]` does work for me. If it doesn't work for you, I'll need a new debug log. But your previous pattern had `[date:%oY]` (which is not valid, there is no function `%oY`), not `[date=%oY]`.

**Comment by retorquere** [comment] 2020-04-24 20:53
`[PublicationTitle1_1]` is not valid; "functions" that start with a capital letter fetch zotero item fields, and there is no field `PublicationTitle1_1`, just `PublicationTitle`.

**Comment by retorquere** [comment] 2020-04-24 20:54
Zotero doesn't have a field for original date; I was just explaining why `Date` didn't pick it up, not saying you should do it differently.

**Comment by retorquere** [comment] 2020-04-24 20:57
The equivalent for `PublicationTitle1_1` is `[PublicationTitle:select=1,1:capitalize]`

**Comment by retorquere** [comment] 2020-04-25 07:13
I really need to know about the `%oY` issue. I need to cut a new release and I want to include this change.

**Comment by Ypot** [comment] 2020-04-25 10:31
> 
> 
> I really need to know about the `%oY` issue. I need to cut a new release and I want to include this change.

It works! 
Thanks for the alternative option for PublicatioTitle ^^

`[=forumPost/WebPage][Auth:lower:capitalize][Date:format-date=%Y-%m-%d.%H\:%M\:%S:prefix=.][shorttitle3_3:lower:capitalize:prefix=.][Pages:prefix=.p.][Volume:prefix=.Vol.][NumberofVolumes:prefix=de] | [Auth:lower:capitalize][date=%oY:prefix=.][shorttitle3_3:lower:capitalize:prefix=.][Pages:prefix=.p.][Volume:prefix=.Vol.][NumberofVolumes:prefix=de]`
Just for the record ;)

**Comment by retorquere** [comment] 2020-04-25 11:27
Thanks for the confirmation, I'll probably cut the release this weekend, still a few more issues to get closure on.

Wrt property access, it's not an alternative, this is just how property access has worked all along. BBT < 6408 would silently ignore the error, but  the way you wrote it earlier would never under any circumstance have yielded output under any version of bbt all the way back to the first version. When I said "equivalent" I meant "I see what you mean, here's how to do it" rather than "that doesn't work anymore, here's how to do it now".

**Closed** 2020-04-25 12:47 UTC
Labels: awaiting-user-feedback, enhancement
