### ISSUE TITLE
BBT doesn't re-initialize properly after MacOS soft-close.

### ISSUE THREAD

**Issue by ltalirz** [retorquere/zotero-better-bibtex#863] opened 2018-01-03 15:48 UTC
- [x] I am on the latest release of BBT and Zotero
- [x] I am posting a single question, bug or feature request
- [x] I have included a descriptive subject of the problem
- [x] I am available for follow-up questions and testing

OS: MacOS 10.13.2

Problem: Sometimes, when I export my library using BetterBibTeX (e.g. Bibtex, but same for Biblatex) I get an error message:

![screen shot 2018-01-03 at 16 40 16](https://user-images.githubusercontent.com/1053245/34527315-82c51c9e-f0a5-11e7-9dd9-21266d08acb6.png)

After I get this error message:
 * if I repeat the export with betterbibtex exporters, I get the error message again
 * if I repeat the export with regular zotero exporters, there is no error
 * if I close & reopen zotero and repeat the export with betterbibtex, it works fine

I currently have no clue what triggers the error; it should be something in the state of zotero/betterbibtex that is reset when zotero is restarted.

I've enabled logging, please see Debug ID D355848559

Cheers,
Leo

**Comment by retorquere** [comment] 2018-01-03 16:39
Hi, I can't see the regular debug logs, those go to the Zotero devs; I'd need a 'better bibtex error report".

**Comment by retorquere** [comment] 2018-01-03 16:39
(unfortunately I cannot customize this error message, it's Zotero showing it, and there's no other way to inform the user something's gone wrong)

**Comment by ltalirz** [comment] 2018-01-05 16:22
sorry for the delay, I had to wait until the error resurfaced with betterbibtex logging enabled.

here is the Report ID: ACKVLV5F

**Comment by retorquere** [comment] 2018-01-05 20:22
Does that mean you cannot reproduce this at will? I don't really understand the error in the log, I'd like to add more detailed logging.

**Comment by blip-bloop** [comment] 2018-01-05 20:31
:robot: this is your friendly neighborhood build bot announcing [test build 5280](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.66.5280.issue-863.xpi) ("keymanager.init fails on setTimeout?").

**Comment by ltalirz** [comment] 2018-01-05 20:34
I just checked and it turns out, the procedure is the same as for #792 
The problem occurs, when you open zotero, then close it with the "red x" button and then open it again by clicking on the zotero icon.

**Comment by blip-bloop** [comment] 2018-01-05 21:26
:robot: this is your friendly neighborhood build bot announcing [test build 5282](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.66.5282.issue-863.xpi) ("everyday I like macos a little less").

**Comment by retorquere** [comment] 2018-01-07 00:48
Ok, it's reproducible, but I haven't yet found a fix.

I hate this behavior of macos. Such a pain.

**Comment by NaoBerlin** [comment] 2018-01-15 12:42
Hi, I have the same issue but it can't be resolved by closing and reopening Zotero. When I try to export my library, the same message of error appears. I've closed and reopened Zotero several times (from the red button and from right click) and the problem remains. If I can be of any help to understand where the problem comes from, I'll be happy to send the log.

**Comment by retorquere** [comment] 2018-01-15 13:22
@NaoBerlin if it isn't fixed by fully quitting (cmd-quite) and restarting Zotero, it's a different issue. Please open a new issue and we'll sort this out.

**Comment by retorquere** [comment] 2018-01-17 11:49
My macbook is starting to act all wonky, so I may have problems fixing macos-specific issues going forward. I'll try to get this one done before it dies.

@NaoBerlin, please open a separate issue for the problem you're experiencing.

**Comment by NaoBerlin** [comment] 2018-01-17 14:48
Hi @retorquere, sorry for my late reply, I'm between cities right now. I think this is the same problem as described above actually; it's just that sometimes closing Zotero once is not enough. On Monday (15th January) for instance I had to close and re-open Zotero at least 5 times in a row before it worked. But since then, everything is perfectly fine. 

I don't need to open a separate issue since I was actually rather offering "help", i.e. I can send you message errors or logs when it happens. But otherwise I assume I just have to be patient when it does not work. 

Many thanks again!

**Comment by retorquere** [comment] 2018-01-17 14:53
I'd appreciate a log, yes, but if a cmd-quit is not enough to resolve the problem, it is not the same problem. #863 is caused by the init being ran a second time since startup. After cmd-Q, Zotero starts anew, so it runs the init only one time after startup.

**Comment by NaoBerlin** [comment] 2018-01-17 15:09
Ok, I understand. Since I didn't have the problem since then, I suggest opening a new thread when/if it happens again. I'll include all the logs.

**Comment by blip-bloop** [comment] 2018-08-31 10:38
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.195.2691](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.195.2691.xpi) ("scanaux has to live somewhere, might as well be root").

**Comment by retorquere** [comment] 2018-08-31 10:56
Can you guys give 2691 a go? On my initial tests it seems to work.

**Comment by ltalirz** [comment] 2018-08-31 12:01
@retorquere I just tried:

 * export selection using better bibtex
 * close window, clicking on red X
 * export selection again using better bibtex

and got no errors. Fix confirmed 👍

**Comment by retorquere** [comment] 2018-08-31 12:26
(but thanks for the confirmation because I also see that and it means I'm on the right track)

**Comment by retorquere** [comment] 2018-08-31 12:27
This version will work better than the released version but will still require cmd-Q occasionally. I have a few leads.

**Comment by blip-bloop** [comment] 2018-09-04 21:41
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.197.2734](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.197.2734.xpi) ("man I'll be glad when Zotero moves to Electron")

Install in Zotero by downloading [test build 5.0.197.2734](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.197.2734.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment] 2018-09-04 21:42
I think I have it. Could you please try 2734?

**Comment by ltalirz** [comment] 2018-09-05 21:33
I confirm that 2734 also has the issue fixed.
If there are any other things I should try, let me know.

**Comment by retorquere** [comment] 2018-09-05 21:48
Cool, thanks, 5.0.198 will drop in a few minutes.

**Comment by ltalirz** [comment] 2018-09-05 21:58
Thanks to you!

**Closed** 2018-09-05 22:01 UTC
Labels: bug
