### ISSUE TITLE
generating new cite key when copying to a group

### ISSUE THREAD

**Issue by bobkummerfeld** [retorquere/zotero-better-bibtex#1877] opened 2021-07-21 01:29 UTC
This problem remains, even when clearing trash etc.

This is what I did:

- emptied trash in all libraries and groups
- removed the bbt addon
- restarted Zotero
- dragged an item with "extras: Citation Key: blah other stuff" to a group.
        the CItation Key remained in extras in the group
- removed the item in the group and emptied trash
- restarted Zotero
- installed latest version of bbt from github
- restarted Zotero
- dragged an item with "extras: Citation Key: blah other stuff" to a group.
        the CItation Key was removed in the group

I can make a screen cast if you want to see more detail.

Support log ID:

**Comment by retorquere** [comment] 2021-07-21 05:32
Let's just skip ahead to the part where I ask for a copy of your profile + data dir (but again without sync credentials please)

**Comment by bobkummerfeld** [comment] 2021-07-21 05:46
Sure :-)

Bob.

**Comment by retorquere** [comment] 2021-07-21 06:57
Let me know when they're up.

**Comment by bobkummerfeld** [comment] 2021-07-21 07:28
Done.

zot.tgz is the ~/Zotero directory
zot-profile.tgz ~/Library/Application Support/Zotero

Bob.

**Comment by retorquere** [comment] 2021-07-21 07:57
What item were you moving to what group? Because, alas, I cannot reproduce. I hate these Heisenbugs.

**Comment by bobkummerfeld** [comment] 2021-07-21 08:18
This time is used a paper with the title: "A "pile" metaphor for supporting
casual organization of information"

It has an "extra" field of:
Citation Key: Mander1992PSHp627
Publisher: ACM Press New York, NY, USA

and the "Citation Key" part disappears after the move to a group leaving:

Publisher: ACM Press New York, NY, USA

Bob.

**Comment by retorquere** [comment] 2021-07-21 08:23
Not for me.

To any group?

**Comment by retorquere** [comment] 2021-07-21 10:29
You know the drill by now.

**Comment by retorquere** [comment] 2021-07-21 11:21
BTW the item being reused from the bin instead of being copied over explains why I didn't see the loggin trigger on the "copy". Baffling behavior though.

**Comment by bobkummerfeld** [comment] 2021-07-21 12:12
After I installed version 1240 it now works......

I'll revert to the current release from github and try again.

Bob.

**Comment by bobkummerfeld** [comment] 2021-07-21 12:15
The version from github (zotero-better-bibtex-5.4.25.xpi)  does NOT work.


Bob.

**Comment by retorquere** [comment] 2021-07-21 12:20
That is expected, 1203+ is built on 5.4.25 and the changes won't show up until I cut a new release. If 1240 works, I can cut that new release.

**Comment by bobkummerfeld** [comment] 2021-07-21 12:28
Excellent!   1240 works!

Bob.

**Closed** 2021-07-21 12:44 UTC
Labels: citekey
