### ISSUE TITLE
Not compatible with Zotero 5.0 beta

### ISSUE THREAD

**Issue by werunom** [retorquere/zotero-better-bibtex#636] opened 2017-01-26 07:00 UTC
Hello!

Just tried the xpi with Zotero 5.0 beta and it did not work. Wanted to know when this would be enabled?

**Comment by retorquere** [comment] 2017-01-26 07:42
Duplicate of #555

**Closed by retorquere** 2017-01-26 07:42 UTC
Labels: duplicate

**Comment by werunom** [comment] 2017-01-26 13:30
Excuse. My bad that I didnt search for existing queries properly [I did search though; but 555 didnt come up in the results].

First of all, thanks for this nice extension. Has made working with latex seamless. And acknowledge the effort and time that this new change is demanding. Appreciate your effort and contribution. 

Have a nice day!

**Comment by retorquere** [comment] 2017-01-26 13:35
No worries.
