### ISSUE TITLE
citr taking long time to access Zotero database with large database

### ISSUE THREAD

**Issue by jrennstich** [retorquere/zotero-better-bibtex#1391] opened 2020-01-12 19:31 UTC
`citr` is taking a considerably long time (90-100 sec) to connect to the Zotero database with my large database. 

**Report ID:**
WF6BPCRX-euc

**Comment by retorquere** [comment] 2020-01-12 22:06
I see 3 requests for the fill library in that log, and some pings to see if BBT is available. Even assuming #1389 fixed, that would still mean 5-10 seconds to complete for those full-library requests. Do you have an idea what you did that may trigger citr to re-fetch the library?

**Comment by jrennstich** [comment] 2020-01-12 22:36
Nope. Simply clicked on "reconnect" once.

**Comment by retorquere** [comment] 2020-01-12 22:46
Then what citr is doing seems a little excessive for large libraries. I'm going to think of a way that citr can check whether what it wants to download has changed since it last fetched it.

**Comment by retorquere** [comment] 2020-01-13 08:37
I've opened an issue over at citr to coordinate at https://github.com/crsh/citr/issues/58. I'll need your presence on this since I'm not a citr user.

**Comment by jrennstich** [comment] 2020-01-13 11:03
I have subscribed.

**Comment by jrennstich** [comment] 2020-01-13 20:28
Report ID: LGZGM3UI-euc

**Comment by ukuvainik** [comment] 2020-02-05 14:11
I have a similar issue. Loading Zotero from citr takes ~2 minutes, also when reupdating.

A typical use case is that I am writing in Rmarkdown. I then realise i need to cite a paper not in my library. I add a paper Zotero via browser. To see that paper in citr, I need to reconnect the Zotero library, which means 2 minutes of waiting to use R.

My library is 4100 items.

**Comment by blip-bloop** [comment] 2020-02-05 14:21
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.14.5836](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5836.xpi) ("test file existence only when needed")

Install in Zotero by downloading [test build 5.2.14.5836](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5836.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment] 2020-02-05 14:24
@ukuvainik can you do the following:

* install 5836 and enable debug logging from the help menu
* connect `citr` to Zotero
* stop rstudio and start it again
* connect `citr` to Zotero again
* send a BBT debug  log from the help menu

**Comment by retorquere** [comment] 2020-02-05 14:36
(same goes for @jkr - 5836 has a tweak that makes exports like citr more efficient)

**Comment by ukuvainik** [comment] 2020-02-05 14:45
thanks for the effort, Report ID: ZSGXIMTV-euc

**Comment by retorquere** [comment] 2020-02-05 15:03
I see 2 exports in that log:

* 2 items, total duration 0.18s
* 4134 items, total duration 5.451s

so if citr takes considerably more time than 6s, it's either something citr is doing that doesn't involve BBT, or citr requests something more of BBT, but then I'm not seeing that in the log.

**Comment by ukuvainik** [comment] 2020-02-05 15:35
> I see 2 exports in that log:
> 
> * 2 items, total duration 0.18s
> * 4134 items, total duration 5.451s
> 
> so if citr takes considerably more time than 6s, it's either something citr is doing that doesn't involve BBT, or citr requests something more of BBT, but then I'm not seeing that in the log.

Ok, I will ask citr about this. Thank you for looking into this. https://github.com/crsh/citr/issues/64

**Comment by retorquere** [comment] 2020-02-05 15:41
https://github.com/crsh/citr/issues/64 might be a duplicate of https://github.com/crsh/citr/issues/58

**Comment by blip-bloop** [comment] 2020-02-05 18:07
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.14.5837](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5837.xpi) ("speed up CSL exports")

Install in Zotero by downloading [test build 5.2.14.5837](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5837.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by jrennstich** [comment] 2020-02-05 18:12
> (same goes for @jkr - 5836 has a tweak that makes exports like citr requests more efficient, assuming a filled cache)

I am on it. This takes much longer in my case...so I won't break up the current attempt and install 5837 after that. Will send two different reports.

**Comment by retorquere** [comment] 2020-02-05 18:21
@jrennstich wat. Performance has regressed for you? Say it ain't so.

**Comment by retorquere** [comment] 2020-02-05 18:22
Oh wait - also on the 2nd run? Unless you have "retain cache" on, installing this build would have dropped the export cache.

**Comment by jrennstich** [comment] 2020-02-05 18:54
> @jrennstich wat. Performance has regressed for you? Say it ain't so.

No, no, it's as speedy as previously (you can see the timings in the reports) - I am talking `citr` connection/reloading.

Report ID (with 5836): BE86BA4X-euc

Report ID (with 5837): AQPF4PGY-euc

**Comment by retorquere** [comment] 2020-02-05 19:10
*phew* 😥 

BE86BA4X-euc: 256.57s (cold), 467.05s (cold), 27.594s (hot)
AQPF4PGY-euc: 226.216s (cold), 575.543s (cold), 12.318s (hot)

I'm going to rig something together so you can view these yourself.

**Comment by jrennstich** [comment] 2020-02-05 19:34
> Oh wait - also on the 2nd run? Unless you have "retain cache" on, installing this build would have dropped the export cache.

No, I meant connecting to `citr`, then Zotero. That takes me usually more than 180 sec when (re)connecting for first time.

**Comment by retorquere** [comment] 2020-02-05 20:31
So assuming you're connecting with a hot cache, what is it doing the other 150 seconds?

**Comment by jrennstich** [comment] 2020-02-06 06:09
beats me

**Comment by blip-bloop** [comment] 2020-02-07 00:01
:robot: this is your friendly neighborhood build bot announcing [test build 5.2.14.5851](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5851.xpi) ("the beta shuffles the extra field...")

Install in Zotero by downloading [test build 5.2.14.5851](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.2.14.5851.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by jrennstich** [comment] 2020-02-07 07:56
Installed it last night, no major changes. I will post a report later.

**Comment by retorquere** [comment] 2020-02-07 08:21
There are only minor changes in this version. It should provide a very modest speedup, but mostly just discloses the stats. I'm still working on an R script to fetch and visualize them. Such a horrid language, R, but easy to make pretty graphs with once you have the data.

**Comment by jrennstich** [comment] 2020-02-07 10:22
Report ID: XLQKMMKQ-euc
With `citr`
Report ID: 4L5IRCPW-euc

**Comment by retorquere** [comment] 2020-02-07 13:48
Neither of those reports show an export being ran. You can look at these yourself now (doesn't require debug logging on), but man I hope someone around here is better with `R` than me:

```
library(jsonlite)
library(RCurl)
stats = fromJSON(getURL('http://127.0.0.1:23119/better-bibtex/translations/stats'))

show <- function(n) {
  plot(
    c(stats$prep$duration[[n]], stats$export$duration[[n]]),
    ylab = "duration",
    main = paste(stats$translator[n], ((stats$cached$serializer[n] + stats$cached$export[n]) * 100) / (stats$items[n] * 2), "%", stats$prep$total[n] + stats$export$total[n], "ms"),
    col = c(rep('red', length(stats$prep$duration[[n]])), rep('blue', length(stats$export$duration[[n]])))
  )
}

show(1)
```

**Comment by jrennstich** [comment] 2020-02-07 14:00
Thanks for sending the `R` script. What would you like me to run? A cold export followed by a hot one? Or rather simply using `citr`?

**Comment by retorquere** [comment] 2020-02-07 14:56
You can use this script (or any improvement you make on it) to peer inside the export performance, which will be helpful once the `citr` side gets going (for one thing, you wouldn't need to send debug logs and install custom builds). But I think I've wrangled pretty much all speedup I could out of this, and if our earlier measurements  are correct, BBT accounts for ~9% of the time of the data exchange. Effort seems at this stage better spent improving on the other 91%.

I'm ready to merge these changes into a new release, but I genuinely don't see what else I could do at this point.

**Comment by jrennstich** [comment] 2020-02-07 15:30
Again: thanks so much. This has been very helpful!

**Comment by retorquere** [comment] 2020-02-07 16:01
My pleasure. I'm running a few more tests tonight to see if I can get juris-m beta running again, and then I'll cut a new release. For citr, we'll have to wait for activity on https://github.com/crsh/citr/issues/58.

**Closed by retorquere** 2020-02-07 16:01 UTC
Labels: bug
