### ISSUE TITLE
duplicate: citekey crushed zotero (sorry i didn't see the previous issue, please ignore)

### ISSUE THREAD

**Issue by xf15** [retorquere/zotero-better-bibtex#1825] opened 2021-05-25 19:28 UTC
**Support log ID:**  I clicked on "Send Better BibTeX suupport log" but nothing poped up, here is my log from zotero side 
```
[JavaScript Error: "Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 280}]

[JavaScript Error: "Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 280}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:280:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:246:19
getField@chrome://zotero/content/xpcom/itemTreeView.js:1538:16
fieldCompare@chrome://zotero/content/xpcom/itemTreeView.js:1561:48
rowSort@chrome://zotero/content/xpcom/itemTreeView.js:1584:17
Zotero.ItemTreeView.prototype.sort/<@chrome://zotero/content/xpcom/itemTreeView.js:1669:14
Zotero.ItemTreeView.prototype.sort@chrome://zotero/content/xpcom/itemTreeView.js:1665:5
Zotero.ItemTreeView.prototype.refresh<@chrome://zotero/content/xpcom/itemTreeView.js:422:5
tryCatcher@resource://zotero/loader.jsm -> resource://zotero/bluebird/util.js:16:16
module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://zotero/loader.jsm -> resource://zotero/bluebird/generators.js:97:18
module.exports/Promise.prototype._settlePromise@resource://zotero/loader.jsm -> resource://zotero/bluebird/promise.js:609:17
module.exports/Promise.prototype._settlePromise0@resource://zotero/loader.jsm -> resource://zotero/bluebird/promise.js:649:5
module.exports/Promise.prototype._settlePromises@resource://zotero/loader.jsm -> resource://zotero/bluebird/promise.js:729:13
_drainQueueStep@resource://zotero/loader.jsm -> resource://zotero/bluebird/async.js:93:9
_drainQueue@resource://zotero/loader.jsm -> resource://zotero/bluebird/async.js:86:9
Async.prototype._drainQueues@resource://zotero/loader.jsm -> resource://zotero/bluebird/async.js:102:5
Async/this.drainQueues@resource://zotero/loader.jsm -> resource://zotero/bluebird/async.js:15:9


[JavaScript Error: "An error has occurred. Please restart Zotero.

You can report this error by selecting "Report Errors…" from the Help menu."]

[JavaScript Error: "this.crash@chrome://zotero/content/xpcom/zotero.js:1241:21
ZoteroPane 5.0.96.2, platform => MacIntel, oscpu => Intel Mac OS X 10.15, locale => en-US, appName => Zotero, appVersion => 5.0.96.2, extensions => Zotero LibreOffice Integration (5.0.25.SA.5.0.96.2, extension), Zotero Word for Mac Integration (5.0.36.SA.5.0.96.2, extension), Better BibTex for Zotero (5.4.16, extension)
```

**Expected behavior:**

**Actual behavior:**
zotero goes blank after restarting, before restarting, citekeys disappeared. 
![image](https://user-images.githubusercontent.com/29473163/119556554-0690fd80-bd54-11eb-8bdf-03b2bd68f154.png)

a bunch of people reported this error on zotero forum within a day. 
https://forums.zotero.org/discussion/89887/error-an-error-has-occurred-please-restart-zotero-does-not-resolve-upon-restart#latest

https://forums.zotero.org/discussion/89886/better-bibtex-stops-generating-citekeys-report-id-996233735#latest

https://forums.zotero.org/discussion/89895/all-my-citations-are-gone-from-local-zotero-an-error-has-occurred#latest

**Comment by retorquere** [comment] 2021-05-25 19:31
Duplicate of #1821

**Closed by retorquere** 2021-05-25 19:31 UTC
Labels: bug, needs-support-log
