### ISSUE TITLE
autoPinDelay not work

### ISSUE THREAD

**Issue by tdegeus** [retorquere/zotero-better-bibtex#2102] opened 2022-04-08 11:44 UTC
I set `autoPinDelay: 5`, but the citation keys are currently not pinned (before they were).

<details><summary>better sent as a log ID</summary>

```
Application: Zotero 6.0.5-beta.2+c510d9146 en-US
Platform: MacIntel Intel Mac OS X 10.16
Addons:
  Zotero Citation Counts Manager (1.3.0, extension)
  Zotero LibreOffice Integration (6.0.0.SA.6.0.5-beta.2+c510d9146, extension)
  Zotero Word for Mac Integration (6.0.0.SA.6.0.5-beta.2+c510d9146, extension)
  Better BibTex for Zotero (6.4.3, extension)
Settings:
  autoAbbrev = true
  autoPinDelay = 5
  caching = false
  citekeyFold = false
  citekeyFormat = "[auth][year]"
  citekeySearch = false
  DOIandURL = "doi"
  platform = "mac"
  postscript = "if (Translator.BetterBibTeX) {\n    if (reference.has.abstract) {\n        reference.remove('abstract');\n    }\n    if (reference.has.note) {\n        reference.remove('note');\n    }\n    if (reference.has.month) {\n        reference.remove('month');\n    }\n    if (reference.has.keywords) {\n        reference.remove('keywords');\n    }\n    if (reference.has.file) {\n        reference.remove('file');\n    }\n    if (item.arXiv.id) {\n        reference.add({name: 'arxivid', value: item.arXiv.id});\n        if (!reference.has.journal) { \n            reference.add({\n                name: 'journal', \n                bibtex: `{arXiv preprint: ${item.arXiv.id}}` \n            }); \n        }\n    }\n}"
Settings at default:
  ascii = ""
  asciiBibLaTeX = false
  asciiBibTeX = true
  autoAbbrevStyle = ""
  autoExport = "immediate"
  autoExportDelay = 5
  autoExportIdleWait = 10
  autoExportPathReplaceDiacritics = false
  autoExportPathReplaceDirSep = "-"
  autoExportPathReplaceSpace = " "
  automaticTags = true
  auxImport = false
  baseAttachmentPath = ""
  biblatexExtendedDateFormat = true
  biblatexExtendedNameFormat = false
  biblatexExtractEprint = true
  bibtexParticleNoOp = false
  bibtexURL = "off"
  cacheFlushInterval = 5
  charmap = ""
  citeCommand = "cite"
  csquotes = ""
  exportBibTeXStrings = "off"
  exportBraceProtection = true
  exportTitleCase = true
  extraMergeCitekeys = false
  extraMergeCSL = false
  extraMergeTeX = false
  git = "config"
  import = true
  importBibTeXStrings = true
  importCaseProtection = "as-needed"
  importCitationKey = true
  importExtra = true
  importJabRefAbbreviations = true
  importJabRefStrings = true
  importSentenceCase = "on+guess"
  importUnknownTexCommand = "ignore"
  itemObserverDelay = 5
  jabrefFormat = 0
  jieba = false
  keyConflictPolicy = "keep"
  keyScope = "library"
  kuroshiro = false
  mapMath = ""
  mapText = ""
  mapUnicode = "conservative"
  parseParticles = true
  patchDates = ""
  postscriptOverride = ""
  preferencesOverride = ""
  qualityReport = false
  quickCopyEta = ""
  quickCopyMode = "latex"
  quickCopyOrgMode = "zotero"
  quickCopyPandocBrackets = false
  quickCopySelectLink = "zotero"
  rawImports = false
  rawLaTag = "#LaTeX"
  relativeFilePaths = false
  retainCache = false
  scrubDatabase = false
  separatorList = "and"
  separatorNames = "and"
  skipFields = ""
  skipWords = "a,ab,aboard,about,above,across,after,against,al,along,amid,among,an,and,anti,around,as,at,before,behind,below,beneath,beside,besides,between,beyond,but,by,d,da,das,de,del,dell,dello,dei,degli,della,dell,delle,dem,den,der,des,despite,die,do,down,du,during,ein,eine,einem,einen,einer,eines,el,en,et,except,for,from,gli,i,il,in,inside,into,is,l,la,las,le,les,like,lo,los,near,nor,of,off,on,onto,or,over,past,per,plus,round,save,since,so,some,sur,than,the,through,to,toward,towards,un,una,unas,under,underneath,une,unlike,uno,unos,until,up,upon,versus,via,von,while,with,within,without,yet,zu,zum"
  startupProgress = "popup"
  strings = ""
  stringsOverride = ""
  testing = false
  verbatimFields = "url,doi,file,ids,eprint,verba,verbb,verbc,groups"
  warnBulkModify = 10
  warnTitleCased = false
  workers = 1
  Zotero: export.quickCopy.setting = "bibliography=http://www.zotero.org/styles/ieee"
Zotero.Debug.enabled: true
Zotero.Debug.enabled at start: true
LocaleDateOrder: mdy
Total export workers started: 0, currently running: 0
```

</details>

**Comment by tdegeus** [comment] 2022-04-08 11:47
[KAHEL672-refs-euc.zip](https://github.com/retorquere/zotero-better-bibtex/files/8451492/KAHEL672-refs-euc.zip)

**Comment by retorquere** [comment] 2022-04-08 11:53
Does the regular log ID submission not work for you? It is really a lot easier for me than logs being pasting/attached here. Does KAHEL672-refs-euc have a change to an item that should have auto-pinned? I don't see any item changes in that log.

**Comment by tdegeus** [comment] 2022-04-08 11:56
For uploading I got:
```
Exception... "Component not initialized"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: chrome://zotero-better-bibtex/content/better-bibtex.js :: node_modules/jszip/dist/jszip.min.js/</<[54]</e.exports< :: line 138857"  data: no] (X3KA2H5R-refs-euc, items: true)
```

Then, I generate this log by clicking on my latest added entry that is indeed not pinned.

**Comment by retorquere** [comment] 2022-04-08 22:01
Can you generate a new log using build 2323? It has extra logging, and may have a fix for log submission using the regular send method.

**Comment by tdegeus** [comment] 2022-04-09 14:07
The new build seems to autoPin again. So I guess I will close this until the problem reappears. Thanks anyway!

**Comment by retorquere** [comment] 2022-04-09 14:42
Strange, because I only added a few logging changes aside changing the log format. Can you try to submit an support log to see if that works again too?

**Comment by tdegeus** [comment] 2022-04-09 14:45
Yes! ABGQZSWW-euc

**Comment by retorquere** [comment] 2022-04-09 15:48
Awesome, thanks for the confirmation.

**Comment by retorquere** [comment] 2022-04-10 09:02
I've removed the logging, can you verify autopin still works for you?

**Comment by abehr** [comment] 2022-04-18 02:06
I'm getting this same issue as well. Occasionally keys get auto-pinned, but other times they don't. I enabled logging but get the same "component not initialized" error [as described above](https://github.com/retorquere/zotero-better-bibtex/issues/2102#issuecomment-1092783794). Tried downloading [build 2323](https://github.com/retorquere/zotero-better-bibtex/issues/2102#issuecomment-1093367991) as suggested to log pinning activity but I think the link no longer exists.

**Comment by abehr** [comment] 2022-04-19 20:54
Thanks - I installed that version, and waited. My most common way of adding entries into Zotero is with Zotero Connector for Chrome.  The issue is intermittent, so the first 5-10 papers I added since then were auto-pinned properly. Then, I just added one where it didn't auto-pin, so I just sent a support log: id F5L2IR3W-euc

**Comment by retorquere** [comment] 2022-04-20 10:00
I see a possible cause, but it's not an easy fix. Zotero is re-loading the main interface, and since that's where BBT starts up, that may throw things out of whack.

**Comment by abehr** [comment] 2022-04-20 16:43
Gotcha. I'm not 100% sure what that means, but if it helps, I think I found some consistency with the behavior:
- After launching Zotero, auto-pin works properly for some time when adding new entries
- At some point, auto-pin stops working when adding new entries. After this point, auto-pin no longer works for any new entries.
- If I quit and re-start the Zotero app, auto-pin resumes working (until the next time it stops).

**Comment by retorquere** [comment] 2022-04-25 15:57
It means I have work to do.

**Comment by abehr** [comment] 2022-04-25 21:34
Yikes - well I'm happy to help with testing at any point, just let me know.

**Comment by retorquere** [comment] 2022-05-30 22:17
I have an idea on how to fix this, but I'm waiting for feedback from the zotero devs.

**Comment by Navla956** [comment] 2023-03-15 23:54
Hello, 

I am still experiencing the same issue! Has this case been closed?

**Comment by retorquere** [comment] 2023-03-16 06:53
I need a debug log. Can't help you without a debug log.

**Comment by tdegeus** [comment] 2023-03-16 09:42
On a note: still issue reappears intermittently but usually disappears after restarting Zotero. Ik you are interested I can post a debug log from time-to-time ?

**Comment by retorquere** [comment] 2023-03-17 07:14
Not necessary at this time, thanks.

**Comment by nowgabis** [comment] 2023-03-22 04:15
My autoPinDelay not working now either. Debug log ID: BPBTS2H2-apse

**Comment by retorquere** [comment] 2023-03-22 06:45
@nowgabis can it be the case that autoPin stops working for you after you closed the last Zotero window but did not quit Zotero (not a cmd-Q quit), opened a new Zotero window, and then autoPin doesn't work anymore? That is currently a known problem. I'm working to resolve this but it requires a big overhaul to how BBT works. cmd-Q and starting Zotero should reliably fix it.

**Comment by nowgabis** [comment] 2023-03-23 02:16
Great, thank you!

---

Gabby Moir
Learning and Development
Consultant | Facilitator | Leadership

**Comment by retorquere** [comment] 2024-01-25 16:36
This ought to be fixed in the last few releases.

**Comment by tdegeus** [comment] 2024-01-25 16:38
Thanks. I'm fine to close and to reopen if the problem reappears.

**Closed** 2024-01-25 16:39 UTC
