### ISSUE TITLE
Unable to change Active citation key formula

### ISSUE THREAD

**Issue by mausgrau** [retorquere/zotero-better-bibtex#3036] opened 2024-10-24 08:14 UTC
### Debug log ID

3TZ4RPFA-refs-euc/6.7.246-7

### What happened?

I cannot seem to change the active citation key formula in the GUI on BBT.
![2024-10-24_10-13](https://github.com/user-attachments/assets/3c042791-baee-4232-be61-6801955eb527)

**Comment by retorquere** [comment] 2024-10-24 08:18
Duplicate of #3031

**Comment by mausgrau** [comment] 2024-10-24 08:21
OK, I was confused because [#3031 ](https://github.com/retorquere/zotero-better-bibtex/issues/3031) was actively renamed to exclude "Unable to change Active citation key formula"

**Comment by retorquere** [comment] 2024-10-24 09:06
I didn't mean it as criticism. I renamed #3031 because the prefs being broken covers more issues - like this one.

**Comment by retorquere** [comment] 2024-10-24 09:07
#3031 has a temporary fix that should get you going. I'm working on a proper fix.

**Closed** 2024-10-24 09:06 UTC
Labels: reopened
