### ISSUE TITLE
[Bug]:  quick copy setting not working

### ISSUE THREAD

**Issue by QiangF** [retorquere/zotero-better-bibtex#2432] opened 2023-03-02 09:22 UTC
### Debug log ID

`quick copy` is not a debug log ID

### What happened?

I have this setting:

     export > quick copy > cite keys

But all the citation is copied.

**Comment by retorquere** [comment] 2023-03-02 19:46
I cannot help without a debug log. Please provide one, or I will have to close the issue.

**Comment by QiangF** [comment] 2023-03-03 01:45
[debug_on_machine_that_not_work.txt](https://github.com/retorquere/zotero-better-bibtex/files/10877348/debug_on_machine_that_not_work.txt)
[debug_on_machine_that_works.txt](https://github.com/retorquere/zotero-better-bibtex/files/10877349/debug_on_machine_that_works.txt)

**Comment by QiangF** [comment] 2023-03-03 01:47
I have used tara to sync zotero settings. https://github.com/l0o0/tara
It works on one maching and doesn't work on another.

**Comment by retorquere** [comment] 2023-03-03 05:55
I don't see an export using quick-copy in that log. Please perform a quick copy, and then follow the steps at point 1. above. I much prefer a debug log ID over an attached log BTW, I have utilities that aid in debugging that depend on having a debug ID.

**Comment by juancarlosfarah** [comment] 2023-03-04 15:11
@QiangF, in case this might help, I was bumping into the same (or a similar issue) in trying to use Better BibLaTeX as a quick copy setting. The error logs pointed to a missing JS file. Had to restart to update Better Bibtex to `v6.7.56`. I see in your debug files that you don't have the same Better Bibtex versions in both machines. Perhaps that is the issue.

Hope that helps!

**Comment by retorquere** [comment] 2023-03-04 18:20
Strange that a file would be missing though, all js files are bundled in the plugin, and the file names don't change.

I still need to see a debug log for diagnosis.

**Comment by QiangF** [comment] 2023-03-05 00:52
@retorquere The fix is manually install the latest add on. The issue might be caused by update through Zotero add on manager. I will close this now, since it is not a common issue and can be fixed easily.

**Comment by juancarlosfarah** [comment] 2023-03-07 16:25
@ retorquere, I believe I managed to reproduce this in another computer:

Zotero Debug Log ID: `D1412893820`
Better BibTeX Debug Log ID: `23HQQX6B-euc`

Indeed it seems to be caused by the version.

**Comment by retorquere** [comment] 2023-03-07 17:43
I have no access do `D<number>` logs, and I see no trace of an export happening in `23HQQX6B-euc`.

**Comment by retorquere** [comment] 2023-03-07 17:50
@juancarlosfarah do you mean you get biblatex output when using quick-copy? You have quick-copy set to `Better BibLaTeX` under Zotero prefs -> Export -> Item Format.

**Comment by retorquere** [comment] 2023-03-07 17:56
@QiangF on the machine where it does not work you have quick copy set to Chicago Note.

**Comment by juancarlosfarah** [comment] 2023-03-07 18:29
@retorquere, yes, I have quick-copy set to `Better BibLaTeX` under Zotero prefs -> Export -> Item Format.

**Comment by retorquere** [comment] 2023-03-07 19:06
So what is going wrong then?

**Comment by juancarlosfarah** [comment] 2023-03-07 22:49
The quick copy shortcut didn't work. Pasting after doing a quick copy would paste the previous contents of the clipboard. There seemed to be an error in the debug logs that I shared with you.

Updating the plugin solves the problem (as previously mentioned).

**Comment by QiangF** [comment] 2023-03-08 00:03
> @QiangF on the machine where it does not work you have quick copy set to Chicago Note.

No, I triple checked that it is "cite keys". I think there might be entanglement with other plugins. I am OK with installing an update manually.

**Comment by retorquere** [comment] 2023-03-08 06:53
Can you please send a screenshot of this screen in the settings on the machines where it doesn't work:

<img width="688" alt="image" src="https://user-images.githubusercontent.com/132108/223640454-45049a12-7b33-4c9d-8220-d722fe2c6168.png">

**Comment by retorquere** [comment] 2023-03-09 07:06
> I am OK with installing an update manually.

That wouldn't help unless I find a problem and fix it, but I don't think there is a problem to fix.

According to [debug_on_machine_that_not_work.txt](https://github.com/retorquere/zotero-better-bibtex/files/10877348/debug_on_machine_that_not_work.txt), you have Zotero's quick-copy format `export.quickCopy.setting` (from the screenshot above) set to `bibliography=http://www.zotero.org/styles/chicago-note-bibliography`, which explains why you're seeing a bibliography entry (in chicago note format). You have BBTs quick-copy mode set to `citekeys`, but you have not set **Zotero's** quick-copy format to BBT quick copy.

**Comment by retorquere** [comment] 2023-03-15 21:31
I need more information, or I will have to close the issue. As far as I can tell it's a misconfiguration problem, not a bug.

**Comment by retorquere** [comment] 2023-03-16 22:17
If you comment on this issue it will reopen.

**Comment by QiangF** [comment] 2023-03-17 01:04
> You have BBTs quick-copy mode set to `citekeys`, but you have not set **Zotero's** quick-copy format to BBT quick copy.

That was the exact problem! It's a config issue. Thank you!

**Comment by juancarlosfarah** [comment] 2023-04-05 08:53
@retorquere, this issue is happening again for me. Yesterday, I was able to do a quick copy using Cmd + Shift C. However, this morning, (having not closed Zotero or restarted my computer) it is no longer working. I have sent you the debug log.

ID: V9WJKV9G-euc

Also, here's the relevant debug log from Zotero itself (D2047117798):

```
(3)(+0016063): unloading ErrorReport

(3)(+0000087): unloaded ErrorReport

(3)(+0002062): Keyboard shortcut: copySelectedItemsToClipboard

(3)(+0000002): {better-bibtex} +207649 worker export skipped, user has chosen foreground export for Better BibLaTeX

(4)(+0000000): Translate: Binding sandbox to http://www.example.com/

(3)(+0000002): Getting contents of undefined

(1)(+0000005): Error: Unsupported type 'undefined' for source Zotero.File</this.getContentsAsync<@chrome://zotero/content/xpcom/file.js:292:13 tryCatcher@resource://zotero/loader.jsm -> resource://zotero/bluebird/util.js:16:16 module.exports/PromiseSpawn.prototype._promiseFulfilled@resource://zotero/loader.jsm -> resource://zotero/bluebird/generators.js:97:18 module.exports/Promise.coroutine/<@resource://zotero/loader.jsm -> resource://zotero/bluebird/generators.js:201:9 From previous event: captureStackTrace@resource://zotero/loader.jsm -> resource://zotero/bluebird/debuggability.js:915:23 CapturedTrace@resource://zotero/loader.jsm -> resource://zotero/bluebird/debuggability.js:807:5 longStackTracesCaptureStackTrace@resource://zotero/loader.jsm -> resource://zotero/bluebird/debuggability.js:482:19 module.exports/Promise.method/<@resource://zotero/loader.jsm -> resource://zotero/bluebird/method.js:13:9 Zotero.Translate.Export.prototype.translate@chrome://zotero/content/xpcom/translate/src/translation/translate.js:2585:10 Zotero_Translate_Export_prototype_translate@chrome://zotero-better-bibtex/content/better-bibtex.js:387536:12 trampoline@chrome://zotero-better-bibtex/content/better-bibtex.js:2602:66 _translate@chrome://zotero/content/fileInterface.js:250:7 exportItemsToClipboard@chrome://zotero/content/fileInterface.js:299:7 ZoteroPane</this.copySelectedItemsToClipboard@chrome://zotero/content/zoteroPane.js:2655:9 oncommand@chrome://zotero/content/standalone/standalone.xul:1:1
```

If I go to the settings, I notice that this is what the **Item Format** is set to (though I did not change it):

<img width="666" alt="image" src="https://user-images.githubusercontent.com/1707188/230031096-6dfad0b2-3d90-43e9-a761-d076b7ae3681.png">

On Better BibTeX, it's set to LaTeX citation:

<img width="665" alt="image" src="https://user-images.githubusercontent.com/1707188/230031234-98af51fe-a057-44fa-ba7d-733bcb61c01d.png">

I also noticed that there was an update ready for restart.

<img width="701" alt="image" src="https://user-images.githubusercontent.com/1707188/230031477-e232f787-3872-4f45-99af-9591d84f6258.png">

If I restart, the issue goes away, but given that it's the third time that I encounter this issue, I wanted to report it anyway.

**Comment by retorquere** [comment] 2023-04-14 12:20
Current version is 6.7.74

**Comment by retorquere** [comment] 2023-04-22 12:28
Closing for inactivity

**Closed by retorquere** 2023-04-22 12:28 UTC
Labels: awaiting-user-feedback, question, reopened
