### ISSUE TITLE
cleared citation key format

### ISSUE THREAD

**Issue by dmbortz** [retorquere/zotero-better-bibtex#728] opened 2017-09-14 18:31 UTC
I added my custom citation key format in the preferences, but that field keeps getting cleared when I open up the preferences again.  It seems to export ok, as the bibtex file is fine.  And, even after the field is cleared, BBT seems to remember my custom format, i.e., the export has the correct keys.

Report ID: R59AGCEF

**Comment by retorquere** [comment] 2017-09-14 18:53
duplicate of #724 (no issue, but the work on it will be tracked there)

**Closed by retorquere** 2017-09-14 18:53 UTC
