### ISSUE TITLE
Z5 v5.0.22: error when exporting library to Better BibTex .bib file (missing citation key)

### ISSUE THREAD

**Issue by floriandierickx** [retorquere/zotero-better-bibtex#738] opened 2017-09-20 16:01 UTC
Report ID: 5CCKDA9R

When trying to export a library of 4420 items to a Better BibTex file (with option 'keep updated'), the error "An error occurred while trying to export the selected file." appears.

Might be a clue: there is one reference (title: Physical Energy Flow Accounts (PEFA), author: European Commission) that does not seem willing to have a citation key (it does not have a citation key in the list, and when clicking refresh it doesn't add one), and this one also appears in the error part of the log. All the others have a citation key (at least partly defined - because of missing years, authors, but all with content).

**Comment by retorquere** [comment] 2017-09-20 19:04
That reference has as its location `BECH Building – Room Ampere`, correct? Can you right-click that reference and send a new report? The problematic reference doesn't seem to be in the debug report.

The problem is indeed that it didn't get a key. How that came to be is what I need to find out.

**Comment by floriandierickx** [comment] 2017-09-20 19:55
Yes that's correct. The error report ID for the following steps is TZFDR66Z.

1. scroll to item:
> Item type: Report
> Title: Physical Energy Flow Accounts (PEFA)
> Author: European Commission
> Report Number: ENV/ACC/WG/05(2014)
> Place: BECH Building – Room Ampere
> Institution: EUROSTAT Directorate E: Sectoral and regional statistics Unit E-2: Environmental statistics and accounts, sustainable development
> Date: 19 and 20 February 2014 (don't know why I entered it like this, probably because I rely on the automatic 'date' fixing of Zotero to choose the most appropriate one =) )
2. right click + unpin key
3. right click + refresh key (without key being added)

**Comment by retorquere** [comment] 2017-09-21 09:17
:robot: bleep bloop; this is your friendly neighborhood build bot announcing [test build 4316](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.22.4316.issue-738.xpi) ("support for date lists in date parser").

**Comment by floriandierickx** [comment] 2017-09-21 09:23
Cool, this fixes the issue!

**Comment by retorquere** [comment] 2017-09-21 09:34
Thanks for the conformation, merged to master. I'll put out a new release when I have folded in a few more open issues.

**Comment by floriandierickx** [comment] 2017-09-21 11:22
Did a restart and tried again, and got the same error message (both with 4316 and 4317).

**Comment by retorquere** [comment] 2017-09-21 11:27
Can you submit a new error log from 5.0.23?

**Comment by floriandierickx** [comment] 2017-09-21 11:31
Aaargh sorry! I have too many tabs open and I mistakenly commented here instead of in issue #735. In short: there is an error messsage (see issue #735) when trying to submit error reports, since 4316, 4317 and 5.0.23.

**Closed** 2017-09-21 11:32 UTC
Labels: awaiting feedback from user, bug

**Comment by floriandierickx** [comment] 2017-09-21 12:17
I don't know if it is linked to this issue, but when exporting a reference with `2-6 June 2014` in the 'Date' place, it outputs a bibtex reference with `year = {2-6 June 2014}`. If something like `6 June 2014` is entered, it gives as expected `year = {2014}`. I know, in the first place a date should not be defined as a range (I don't think bibtex has a format for this?), but anyway.. I'll look out to correctly input reference dates :)

**Comment by retorquere** [comment] 2017-09-21 13:01
It's related but a different problem -- can you open a new issue?
