### ISSUE TITLE
Failed export of library

### ISSUE THREAD

**Issue by Jmuccigr** [retorquere/zotero-better-bibtex#618] opened 2016-12-23 19:19 UTC
ID 87FPB37U

Just the normal library export for me, which usually works.

**Comment by retorquere** [comment] 2016-12-23 20:50
That is thoroughly strange... I don't know why this error happens<sup>1</sup>, and I can't reproduce it on my end, but can you see whether [this](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.88-br618-3408.xpi)<sup>2</sup> fixes it for you?

<sup>1</sup> I get a notification from Zotero that an item has changed, which is supposed to happen right after it is saved, but when I try to fetch it in the notifier Zotero complains in your log that I'm trying to fetch an item with unsaved changes... but not on my systems or my test service, as I can't reproduce it.

<sup>2</sup> this just sticks in a delay of half second between the notification and acting on the notification. We can try bringing that number down if it seems to work on your system.

**Comment by Jmuccigr** [comment] 2016-12-23 21:44
Yep, that worked.

**Comment by retorquere** [comment] 2016-12-23 22:51
That is in a sense disappointing, as in that the problem really shouldn't exist. Anyhow, this problem will go away after the 5.0 port anyway as the notification system is wholly different. Can you try [this](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.88-br618-3409.xpi) version? It brings the delay down to 1 millisecond.

**Comment by Jmuccigr** [comment] 2016-12-23 22:55
Yep, that worked too. Thanks.

**Comment by Jmuccigr** [comment] 2016-12-26 17:39
May have to take that back: J287B97G

**Comment by retorquere** [comment] 2016-12-26 19:09
OK, so indeed same error... I've put up a new build [here](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.89-br618-3415.xpi) which makes the delay tweakable. As a) the problem is not supposed to happen anyway, and b) I can't reproduce it, I'm going to need your help to suss out a reasonable delay value.

This build has a new [hidden preference](https://www.zotero.org/support/preferences/hidden_preferences) called `itemObserverDelay` which is `0` by default. You get the behavior of the first build by setting it to `500`, but if you can get away with less you'll have a lesser chance of odd side effects. A change in value only takes effect after a full restart of Zotero, so not just closing the window but actually `Quit`ing it. Sorry to have to ask this but I see no other way.

**Comment by Jmuccigr** [comment] 2016-12-26 19:19
OK, set it at 250 to start and the export ran. We'll see how that goes and then I'll tweak.

**Comment by Jmuccigr** [comment] 2017-01-03 00:07
OK, so somewhere between 40 and 25 ms seems to be the breaking point on my large library. Next step?

**Closed** 2017-01-03 18:51 UTC
Labels: awaiting feedback from user, bug, cannot reproduce

**Comment by retorquere** [comment] 2017-01-03 18:53
I'll just set it to 100 by default to have a bit of margin -- a tenth of a second ought to be unnoticeable. I'll cut a new release when the tests finish, but note that the value you have set will continue to override the default. You can right-click it after the upgrade and reset to default if you wish, or leave it as-is.
