### ISSUE TITLE
The add-on doesn't start or work as intended

### ISSUE THREAD

**Issue by Sienna-Milady** [retorquere/zotero-better-bibtex#1822] opened 2021-05-25 17:07 UTC
### Problem

- When I open Zotero, the add-on's popup doesn't appear at all.
- The citation keys column is there, but the field is nowhere to be seen in my items, so no citekeys are displayed in the column.
- Adding `Citation Key: [some citekey]` to an item's `Extra` field does nothing.
- The citation key format remains blank no matter what text I add. E.g., if I enter `[some pattern]`, close the preferences window and open it again, the field is blank.
- I can't generate support logs because the option to do so does nothing.

### Additional information

- I have the latest version of the add-on.
- I've installed Lubuntu on my laptop after running into several performance issues with the regular Ubuntu.

*Note: I'm open to testing and will provide more information if requested.*

**Comment by Sienna-Milady** [comment] 2021-05-25 17:14
Just to clarify, I can't generate a support log from either approach mentioned in the bot's comment.

**Comment by nomaad** [comment] 2021-05-25 17:28
Same problems here. 

In the debug output I have a multiple occurrence of this error:

`[JavaScript Error: "Error: Invalid field 'citekey" for base field" {file: "chrome://zotero/content/xpcom/data/itemFields.js" line: 280}]
getFieldIDFromTypeAndBase@chrome://zotero/content/xpcom/data/itemFields.js:280:13
Zotero.Item.prototype.getField@chrome://zotero/content/xpcom/data/item.js:246:19
Zotero.ItemTreeRow.prototype.getField@chrome://zotero/content/xpcom/itemTreeView.js:3500:10
Zotero.ItemTreeView.prototype.getCellText@chrome://zotero/content/xpcom/itemTreeView.js:1086:15`

And finally: 

`[JavaScript Error: "TypeError: document.getElementById(...) is null" {file: "chrome://zotero/content/standalone/basicViewer.xul" line: 1}]
oncommand@chrome://zotero/content/standalone/basicViewer.xul:1:1`

`version => 5.0.96.2, platform => MacIntel, oscpu => Intel Mac OS X 10.14, locale => de, appName => Zotero, appVersion => 5.0.96.2, extensions => ZotFile (5.0.16, extension), Zutilo Dienstprogramm für Zotero (3.8.1, extension), Zotero LibreOffice Integration (5.0.25.SA.5.0.96.2, extension), Zotero Word for Mac Integration (5.0.36.SA.5.0.96.2, extension), Better BibTex for Zotero (5.4.17, extension)`

**Comment by retorquere** [comment] 2021-05-25 17:30
Duplicate of #1821 please join there

**Closed by retorquere** 2021-05-25 17:30 UTC
Labels: bug, needs-support-log
