### ISSUE TITLE
Fields do not "refresh" in Zotero 5.0-beta.r67+3f5ead (only "Citation Key" field)

### ISSUE THREAD

**Issue by jrennstich** [retorquere/zotero-better-bibtex#588] opened 2016-10-23 08:56 UTC
When using zotero-better-bib(La)TeX I get the following error:

[Error Report on Zotero Forum](https://forums.zotero.org/discussion/62907/fields-do-not-refresh)

The Debug ID is D851554564.

Report ID 1650428629

1. Booting FF
2. Loading Zotero 5.0-beta.r67+3f5ead / Better-Bib(La)TeX 1.6.78
3. Clicking on database entry. Then next. Only the Citation Key changes, none of the rest.
4. When I click on "Tags" and then back to "Info" the correct information is shown (of the new entry I clicked on)

It worked fine in the beta version before (earlier yesterday, there was an update after the update that fixed the issue with the tags, r66).

**Comment by retorquere** [comment] 2016-10-23 09:34
Duplicate of #555

**Comment by retorquere** [comment] 2016-10-23 09:36
It can't have worked with a previous beta. BBT uses the 4.0 style database access extensively, and this has gone away in 5.0. Everything is broken, and extensive work is needed to get compatibility back.

**Closed** 2016-10-23 09:36 UTC
