### ISSUE TITLE
"type: dataset" exported as @data instead of @dataset for BibLaTeX

### ISSUE THREAD

**Issue by marcschulder** [retorquere/zotero-better-bibtex#1720] opened 2021-01-06 10:50 UTC
**Report ID:** NISGFY7B-euc

**Exporter used:** Better BibLaTeX

**Expected behavior:** Setting "type: dataset" in the Extra field results in an exported item of type `@dataset`

**Actual behavior:** Exported type is of type `@data`

**Details:**
To set up a dataset in Zotero, I specified a custom item type in the Extra field: "type: dataset". When exporting with BetterBibTex, this is correctly converted to `@misc`. However, when exported with BetterBibLaTeX it results in `@data`, which is not a valid BibLaTeX type. Instead, it should be @dataset.

This problem only occurs for "type:", not "tex.referencetype:", presumably as the former triggers some interpretation, while the latter is a hard overwrite instruction.

Sidenote: The exporter does not yet know how to quality check dataset references. As their required fields are specified in the BibLaTeX documentation, that should be fixable.

**Comment by retorquere** [comment] 2021-01-11 10:33
I don't get `@DaTa`, I get `@article`, and BBT only exports lower-case entry types. I cannot reproduce the problem working from `NISGFY7B-euc`.

The quality check is derived from the test.bcf at https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/testfiles/. I must admit I don't fully understand how it is generated.

**Comment by retorquere** [comment] 2021-01-11 10:41
Hmm, [this](https://github.com/plk/biber/blob/dev/data/biber-tool.conf) is probably a better source for a description of what's valid biblatex. I'll take a look at that. But I honestly have no idea how you got `@DaTa`.

**Comment by marcschulder** [comment] 2021-01-11 10:43
Quick clarification regarding the capitalisation: The resulting BibLaTex type is `@data`, not `@DaTa`. I neglected to mark the types as code, so Github identified them as users and applied their preferred capitalisation.

**Comment by retorquere** [comment] 2021-01-11 10:48
Ah OK, that solves one part of the mystery. But the problem remains that when I export `NISGFY7B-euc` with your settings, I get 

```
@article{Doe2021,
  title = {Faulty Dataset Export},
  author = {Doe, John},
  date = {2021},
  type = {dataset}
}
% == BibLateX quality report for Doe2021:
% Unexpected field 'type'
% Missing required field 'journaltitle'
```

**Comment by marcschulder** [comment] 2021-01-11 10:56
Strange. I only get your output when I write `tex.type: dataset` in the Extra field. When I write `type: dataset` I get

```
@data{Doe2021,
  title = {Faulty Dataset Export},
  author = {Doe, John},
  date = {2021}
}
% == BibLateX quality report for Doe2021:
% I don't know how to quality-check data references
```

**Comment by retorquere** [comment] 2021-01-11 11:09
My bad -- I had removed the mapping but forgotten about it. I now get 

```
@dataset{Doe2021,
  title = {Faulty Dataset Export},
  author = {Doe, John},
  date = {2021}
}
% == BibLateX quality report for Doe2021:
% I don't know how to quality-check dataset references
```

I'll look into the quality report rules for datasets.

**Comment by retorquere** [comment] 2021-01-11 13:19
@njbart does #587 still hold? I've looked in the [biblatex manual](http://mirrors.ibiblio.org/CTAN/macros/latex/contrib/biblatex/doc/biblatex.pdf) and like @marcschulder says I see only `@dataset` there, not `@data`. This manual should describe vanilla biblatex right, not biblatex-apa? Or was `@dataset` added since?

**Comment by marcschulder** [comment] 2021-01-11 13:41
`@dataset` is fairly recent. It was added in biblatex v3.13 on 2019-08-17

**Comment by retorquere** [comment] 2021-01-11 13:46
Ah. Jeez. I have no idea how likely it is that people will have upgraded. Meh, can always be fixed with a postscript. A build that outputs `@dataset` and that has the updated QR checker should land here in 10 minutes or so.

**Comment by marcschulder** [comment] 2021-01-11 14:23
Works like a charm.
Regarding users having upgraded: If `@data` was ever part of vanilla BibLaTeX, I don't think it was documented. I had a peek at a documentation version from early 2019 and couldn't spot anything. Current versions of biblatex-apa and biblatex-chicago also use `@dataset`.

**Comment by retorquere** [comment] 2021-01-11 15:48
Cool. Seems reasonable. I'll give @njbart some time to respond but it sounds like he'd agree.

**Comment by njbart** [comment] 2021-01-11 21:13
Fine with me: Back in 2016, only biblatex-apa had a dedicated entry type for datasets, called `@data` (see https://github.com/retorquere/zotero-better-bibtex/issues/587#issuecomment-255577156, note (4)). biblatex added the `@dataset` entry type in 2019-08-17, and biblatex-apa as well as biblatex-chicago (the latter on 2020-04-20) have followed suit. So BBT should use `@dataset` rather than `@data`, too.

**Comment by retorquere** [comment] 2021-01-11 21:16
Super, thanks for the confirmation.

**Closed by retorquere** 2021-01-11 21:16 UTC
Labels: bug
