### ISSUE TITLE
Zotero 5.0.97-beta and Better BibTeX Plugin

### ISSUE THREAD

**Issue by dml0sc** [retorquere/zotero-better-bibtex#1900] opened 2021-08-28 13:13 UTC
In the Zotero 5.0.97-beta, it is not possible to alter the format of Better BibTeX citekeys and it is not possible to export via quickcopy  -- will this be fixed? It is possible to export a library as .bib but with the standard citekey format only

Support log ID:

**Comment by retorquere** [comment] 2021-08-28 13:54
Duplicate of #1899

**Closed by retorquere** 2021-08-28 13:54 UTC
Labels: export
