### ISSUE TITLE
Error when removing an export from Auto-export (Report ID: EY7K7UJQ)

### ISSUE THREAD

**Issue by jrennstich** [retorquere/zotero-better-bibtex#730] opened 2017-09-15 05:16 UTC
Report ID:  EY7K7UJQ

Clicking "remove" (under "Automatic export") results in BBT not showing any Citation key format information any longer. Auto-export did not work for me in the last couple of versions and I always had this kind of behavior as reported here (citation key format disappearing). Restarting Zotero fixes this problem and the information reappears.

**Comment by retorquere** [comment] 2017-09-15 12:44
(possible duplicate of #723): can you try  [4265](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.15.4265.issue-723.xpi)?

**Comment by jrennstich** [comment] 2017-09-15 13:51
Can confirm, that now:
- information in citation key format is not disappearing anymore
- auto-export on change is working as expected (gave it one try only so far, my database is pretty large and so exports take time)

I could not trigger auto-export when idle.

**Comment by retorquere** [comment] 2017-09-15 14:02
The citation key disappearing from the prefs pane is a separate problem that I haven't tackled yet, but I'm working on it.

Exports should really be [fast](https://github.com/retorquere/zotero-better-bibtex/wiki/Performance) after the first export, I haven't yet tested anew, and I don't know how many references you have, but if it's noticeably slow then there may be a problem with the cache handling.

Can you set up an auto-export, change something, let it sit for 30 seconds, and then submit a debug log?

**Comment by jrennstich** [comment] 2017-09-15 15:24
The error report took a really long time to be submitted (over ten minutes). Report ID FR67ME6A.

**Comment by retorquere** [comment] 2017-09-15 15:27
Wow, 250MB of logs to go through. Well, it *is* nearly weekend.

**Comment by jrennstich** [comment] 2017-09-15 17:08
Soooooooory

**Comment by retorquere** [comment] 2017-09-16 17:43
No worries, it's mostly BBTs chatter that makes the logs so big.

Can you try [test build 4278](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.0.15.4278.issue-723.xpi)?

**Comment by jrennstich** [comment] 2017-09-16 18:43
Kudos! Works now as advertised - secondary updates much faster than the first one.

**Comment by retorquere** [comment] 2017-09-16 18:47
Yah, I found a caching problem while I was doing this. The previous tests only did one-shot exports (so didn't hit the cache) and only auto-exported libraries, not collections. I've added both to my test suite now.

I'm going to merge this to master but will leave #723 open until confirmation.

Thanks for your help.

**Closed by retorquere** 2017-09-16 18:47 UTC
Labels: bug
